# **Minicurso FLAI Data Science na Copa do Mundo Qatar 2022 ⚽**

## Importar Bibliotecas e Dados

In [ ]:
# Importando as bibliotecas necessárias

import pandas as pd
import numpy as np
import random
from scipy.stats import poisson

In [ ]:
# URL onde se encontra a base de dados
url = 'https://github.com/adriana-takahagui/copa-mundo-2022/blob/main/dados/DadosCopaDoMundoQatar2022.xlsx?raw=true'

# Carregando dados das seleções e colocando 'Seleção' como índice da tabela
selecoes = pd.read_excel(url, sheet_name = 'selecoes', index_col = 0)

# Carregando dados dos jogos
jogos = pd.read_excel(url, sheet_name = 'jogos')

# Carregando dados dos jogos (Fase 2)
jogos_fase2 = pd.read_excel(url, sheet_name = 'jogos_fase2')

In [ ]:
# Espiando as primeiras linhas de 'selecoes'
selecoes.head()

,Grupo,GrupoNumero,NomeEmIngles,PosiçãoRankingFIFA,ValorDeMercado,PontosRankingFIFA,Confederação,Copas,JogadorDestaque,FotoJogadorDestaque,LinkBandeiraPequena,LinkBandeiraGrande
Seleção,,,,,,,,,,,,
Catar,A,A1,Qatar,48,18.33,1442,AFC,0,Almoez Ali,https://github.com/ricardorocha86/PrevisaoEspo...,https://cloudinary.fifa.com/api/v3/picture/fla...,https://flagdownload.com/wp-content/uploads/Fl...
Equador,A,A2,Ecuador,44,125.80,1464,UEFA,0,Pervis Estupiñán,https://github.com/ricardorocha86/PrevisaoEspo...,https://cloudinary.fifa.com/api/v3/picture/fla...,https://flagdownload.com/wp-content/uploads/Fl...
Senegal,A,A3,Senegal,18,286.50,1585,CAF,0,Sadio Mané,https://github.com/ricardorocha86/PrevisaoEspo...,https://cloudinary.fifa.com/api/v3/picture/fla...,https://flagdownload.com/wp-content/uploads/Fl...
Holanda,A,A4,Netherlands,8,455.75,1679,UEFA,0,Virgil Van Dijk,https://github.com/ricardorocha86/PrevisaoEspo...,https://cloudinary.fifa.com/api/v3/picture/fla...,https://flagdownload.com/wp-content/uploads/Fl...
Inglaterra,B,B1,England,5,1360.00,1737,UEFA,1,Harry Kane,https://github.com/ricardorocha86/PrevisaoEspo...,https://cloudinary.fifa.com/api/v3/picture/fla...,https://flagdownload.com/wp-content/uploads/Fl...

In [ ]:
# Espiando as primeiras linhas de 'jogos'
jogos.head()

,data,hora,grupo,seleção1,seleção2,estádio
0,2022-11-20,13:00:00,A,Catar,Equador,AL BAYT
1,2022-11-21,13:00:00,A,Senegal,Holanda,AL THUMAMA
2,2022-11-21,10:00:00,B,Inglaterra,Irã,INTERNACIONAL KHALIFA
3,2022-11-21,16:00:00,B,Estados Unidos,País de Gales,AHMAD BIN ALI
4,2022-11-22,07:00:00,C,Argentina,Arábia Saudita,NAC. LUSAIL

In [ ]:
# Espiando as primeiras linhas de 'jogos_fase2'
jogos_fase2

,etapa,data,hora,seleção1,seleção2,estádio
0,Oitavas,2022-12-03,12:00:00,Holanda,Estados Unidos,INTERNACIONAL KHALIFA
1,Oitavas,2022-12-03,16:00:00,Argentina,Austrália,AHMAD BIN ALI
2,Oitavas,2022-12-04,12:00:00,França,Polônia,AL BAYT
3,Oitavas,2022-12-04,16:00:00,Inglaterra,Senegal,AL BAYT
4,Oitavas,2022-12-05,12:00:00,Japão,Croácia,AL JANOUB
5,Oitavas,2022-12-05,16:00:00,Brasil,Coreia do Sul,ESTÁDIO 974
6,Oitavas,2022-12-06,12:00:00,Marrocos,Espanha,CIDADE DA EDUCAÇÃO
7,Oitavas,2022-12-06,16:00:00,Portugal,Suíça,NAC. LUSAIL
8,Quartas,2022-12-09,12:00:00,Croácia,Brasil,CIDADE DA EDUCAÇÃO
9,Quartas,2022-12-09,16:00:00,Holanda,Argentina,NAC. LUSAIL
10,Quartas,2022-12-10,12:00:00,Marrocos,Portugal,AL THUMAMA
11,Quartas,2022-12-10,16:00:00,Inglaterra,França,AL BAYT

## Fator de Força com base no Ranking FIFA

In [ ]:
# Analisando o Ranking FIFA de cada seleção para gerar os valores do fator de força

fifa = selecoes['PontosRankingFIFA']
fifa.sort_values(ascending = False)

Seleção
Brasil            1838
Bélgica           1822
Argentina         1771
França            1765
Inglaterra        1737
Espanha           1717
Portugal          1679
Holanda           1679
Dinamarca         1665
Alemanha          1659
México            1650
Uruguai           1641
Estados Unidos    1635
Croácia           1632
Suíça             1621
Senegal           1585
País de Gales     1582
Irã               1559
Marrocos          1558
Japão             1555
Sérvia            1550
Polônia           1546
Coreia do Sul     1526
Tunísia           1508
Costa Rica        1500
Camarões          1485
Austrália         1484
Canadá            1474
Equador           1464
Catar             1442
Arábia Saudita    1436
Gana              1393
Name: PontosRankingFIFA, dtype: int64

In [ ]:
# Transformação linear de escala numérica para fator de força (de acordo com o Ranking FIFA)
# Mapeando o maior (1838) e menor (1393) valor do Ranking FIFA para valores entre 1 e 0.15

a, b = min(fifa), max(fifa)
fa, fb = 0.15, 1
b1 = (fb - fa)/(b-a)
b0 = fb - b*b1
forca = b0 + b1*fifa

forca.sort_values(ascending = False)

Seleção
Brasil            1.000000
Bélgica           0.969438
Argentina         0.872022
França            0.860562
Inglaterra        0.807079
Espanha           0.768876
Portugal          0.696292
Holanda           0.696292
Dinamarca         0.669551
Alemanha          0.658090
México            0.640899
Uruguai           0.623708
Estados Unidos    0.612247
Croácia           0.606517
Suíça             0.585506
Senegal           0.516742
País de Gales     0.511011
Irã               0.467079
Marrocos          0.465169
Japão             0.459438
Sérvia            0.449888
Polônia           0.442247
Coreia do Sul     0.404045
Tunísia           0.369663
Costa Rica        0.354382
Camarões          0.325730
Austrália         0.323820
Canadá            0.304719
Equador           0.285618
Catar             0.243596
Arábia Saudita    0.232135
Gana              0.150000
Name: PontosRankingFIFA, dtype: float64

## Desenvolver funções necessárias

In [ ]:
# Função para calcular a média de gols de cada seleção de acordo com o fator de força de cada seleção
# A função recebe 'selecao1' e 'selecao2' (que são os nomes dos países)
# A função retorna uma lista com:
# - a média de gols da 'selecao1' ('m1')
# - a média de gols da 'selecao2' ('m2')
def MediasPoisson(selecao1, selecao2):
    forca1 = forca[selecao1]
    forca2 = forca[selecao2]
    mgols = 2.75
    m1 = mgols * forca1/(forca1 + forca2)
    m2 = mgols * forca2/(forca1 + forca2)
    return [m1, m2]

# Função que retorna o resultado de uma partida entre 'selecao1' e 'selecao2'
# A função recebe a média de gols da 'selecao1' ('gols1') e a média de gols da 'selecao2' ('gols2')
# A função retorna um caracter:
#   V - vitória da 'selecao1' e derrota da 'selecao2', ou
#   D - derrota da 'selecao1' e vitória da 'selecao2', ou
#   E - empate entre 'selecao1' e 'selecao2'
def Resultado(gols1, gols2):
    if gols1 > gols2:
        resultado = 'V'
    if gols1 < gols2:
        resultado = 'D'
    if gols1 == gols2:
        resultado = 'E'
    return resultado

# Função para gerar os pontos da 'selecao1' e 'selecao2' em uma partida
# A função recebe a média de gols da 'selecao1' ('gols1') e a média de gols da 'selecao2' ('gols2')
# A função retorna uma lista com:
# - pontos1: a quantidade de pontos que a 'selecao1' recebeu na partida
# - pontos2: a quantidade de pontos que a 'selecao2' recebeu na partida
# - resultado: o resultado da partida entre 'selecao1' e 'selecao2' (V - vitória da 'selecao1', D - derrota da 'selecao1', ou E - empate)
def Pontos(gols1, gols2):
    resultado = Resultado(gols1, gols2)
    if resultado == 'V':
        pontos1, pontos2 = 3, 0
    if resultado == 'D':
        pontos1, pontos2 = 0, 3
    if resultado == 'E':
        pontos1, pontos2 = 1, 1
    return [pontos1, pontos2, resultado]

# Função para simular uma partida entre 'selecao1' e 'selecao2' com base na média de gols de cada seleção
# A função recebe 'selecao1' e 'selecao2' (que são os nomes dos países)
# A função retorna um dicionário com:
# - gols1: a média de gols da 'selecao1'
# - gols2: a média de gols da 'selecao2'
# - saldo1: o saldo de gols da 'selecao1'
# - saldo2: o saldo de gols da 'selecao2'
# - pontos1: pontos da 'selecao1'
# - pontos2: pontos da 'selecao2'
# - resultado: o resultado da partida entre 'selecao1' e 'selecao2'
# - placar: o placar da partida
def Jogo(selecao1, selecao2):
    # Médias de gols de cada seleção
    m1, m2 = MediasPoisson(selecao1, selecao2)
    # Gerando números aleatórios com base nas médias de gol ('m1' e 'm2') para definir quantidade de gols de cada seleção
    gols1 = int(np.random.poisson(lam = m1, size = 1))
    gols2 = int(np.random.poisson(lam = m2, size = 1))
    saldo1 = gols1 - gols2
    saldo2 = -saldo1
    pontos1, pontos2, resultado = Pontos(gols1, gols2)
    placar = '{}x{}'.format(gols1, gols2)
    return {'gols1': gols1, 'gols2': gols2,
            'saldo1': saldo1, 'saldo2': saldo2,
            'pontos1': pontos1, 'pontos2': pontos2,
            'resultado': resultado, 'placar': placar}

# Função para calcular a distruibuição de gols de uma seleção em uma partida (0 a 7+ gols) dado a média de gols
# A função recebe média de gols
# A função retorna um Series com as probabilidades de gol em uma faixa de 0 a 7+ gols
def Distribuicao(media):
    probabilidades = []
    # Calcula probabilidade de sair 0 a 7 gols
    for i in range(7):
        # Calcula a probabilidade dentro da distribuição Poisson de sair gol 'i' dado uma média de gol 'media'
        probabilidades.append(poisson.pmf(i, media))
    # Calcula a probabilidade de sair mais de 7 gols
    probabilidades.append(1 - sum(probabilidades))
    return pd.Series(probabilidades, index = ['0', '1', '2', '3', '4', '5', '6', '7+'])

# Função que retorna todas as probabilidades de uma partida entre 'selecao1' e 'selecao2'
# A função recebe 'selecao1' e 'selecao2' (que são os nomes dos países)
# A função retorna um dicionário com:
# - selecao1: nome do país da seleção 1
# - selecao2: nome do país da seleção 2
# - forca1: fator de força da seleção 1
# - forca2: fator de força da seleção 2
# - m1: média de gols da seleção 1
# - m2: média de gols da seleção 2
# - probalidades: as probabilidades em % de vitória, empate e derrota
# - matriz: distribuição Poisson de probabilidades de gols da partida
def ProbabilidadesPartida(selecao1, selecao2):
    m1, m2 = MediasPoisson(selecao1, selecao2)
    d1, d2 = Distribuicao(m1), Distribuicao(m2)

    # Monta a matriz de probabilidades (produto entre d1 e d2)
    matriz = np.outer(d1, d2)

    # Soma o triângulo inferior da matriz
    vitoria = np.tril(matriz).sum() - np.trace(matriz)
    # Soma o triângulo superior da matriz
    derrota = np.triu(matriz).sum() - np.trace(matriz)
    empate = 1 - (vitoria + derrota)

    probalidades = np.around([vitoria, empate , derrota], 3)
    probalidades_perc = [f'{100*i:.1f}%' for i in probalidades]

    nomes = ['0', '1', '2', '3', '4', '5', '6', '7+']
    matriz = pd.DataFrame(matriz, columns = nomes, index = nomes)

    # Adicionando dois índices na matriz final (os gols de 0 a 7+ e o nome da seleção)
    matriz.index = pd.MultiIndex.from_product([[selecao1], matriz.index])
    matriz.columns = pd.MultiIndex.from_product([[selecao2], matriz.columns])

    output = {'seleção1': selecao1, 'seleção2': selecao2,
             'f1': forca[selecao1], 'f2': forca[selecao2],
             'media1': m1, 'media2': m2,
             'probabilidades': probalidades_perc, 'matriz': matriz}
    return output

In [ ]:
# Simulando um jogo entre Brasil e França
Jogo('Brasil', 'França')

{'gols1': 2,
 'gols2': 0,
 'saldo1': 2,
 'saldo2': -2,
 'pontos1': 3,
 'pontos2': 0,
 'resultado': 'V',
 'placar': '2x0'}

In [ ]:
# Simulando um jogo entre Brasil e França e soltando as probabilidades
ProbabilidadesPartida('Brasil', 'França')

{'seleção1': 'Brasil',
 'seleção2': 'França',
 'f1': 1.0,
 'f2': 0.8605617977528088,
 'media1': 1.478048191315901,
 'media2': 1.2719518086840993,
 'probabilidades': ['42.0%', '25.4%', '32.6%'],
 'matriz':              França                                                    \
                   0         1         2         3         4         5
 Brasil 0   0.063928  0.081313  0.051713  0.021926  0.006972  0.001774
        1   0.094488  0.120185  0.076435  0.032407  0.010305  0.002622
        2   0.069829  0.088819  0.056487  0.023950  0.007616  0.001937
        3   0.034404  0.043760  0.027830  0.011800  0.003752  0.000955
        4   0.012713  0.016170  0.010284  0.004360  0.001386  0.000353
        5   0.003758  0.004780  0.003040  0.001289  0.000410  0.000104
        6   0.000926  0.001177  0.000749  0.000318  0.000101  0.000026
        7+  0.000239  0.000303  0.000193  0.000082  0.000026  0.000007


                   6            7+
 Brasil 0   0.000376  8.093932e-05
        1   0.000556  1.196322e-04
        2   0.000411  8.841109e-05
        3   0.000202  4.355862e-05
        4   0.000075  1.609543e-05
        5   0.000022  4.757966e-06
        6   0.000005  1.172084e-06
        7+  0.000001  3.019985e-07  }

---
## **Prever os Jogos da Copa! (Fase 1)**

In [ ]:
# Adicionando mais 3 colunas de probabilidades na tabela 'jogos'
jogos['Vitória'] = None
jogos['Empate'] = None
jogos['Derrota'] = None

# Iterando cada linha da tabela de 'jogos' e adicionando as 3 colunas com as probabilidades de vitória, empate e derrota
for i in range(jogos.shape[0]):
    selecao1 = jogos['seleção1'][i]
    selecao2 = jogos['seleção2'][i]
    v, e, d = ProbabilidadesPartida(selecao1, selecao2)['probabilidades']
    jogos.at[i,'Vitória'] = v
    jogos.at[i,'Empate'] = e
    jogos.at[i,'Derrota'] = d

# Exportando o resultado em uma planilha Excel
jogos.to_excel('outputEstimativasJogosCopa.xlsx')
jogos

,data,hora,grupo,seleção1,seleção2,estádio,Vitória,Empate,Derrota
0,2022-11-20,13:00:00,A,Catar,Equador,AL BAYT,32.3%,25.4%,42.3%
1,2022-11-21,13:00:00,A,Senegal,Holanda,AL THUMAMA,28.3%,24.9%,46.8%
2,2022-11-21,10:00:00,B,Inglaterra,Irã,INTERNACIONAL KHALIFA,54.6%,23.6%,21.8%
3,2022-11-21,16:00:00,B,Estados Unidos,País de Gales,AHMAD BIN ALI,43.0%,25.3%,31.7%
4,2022-11-22,07:00:00,C,Argentina,Arábia Saudita,NAC. LUSAIL,74.2%,17.3%,8.5%
5,2022-11-22,13:00:00,C,México,Polônia,ESTÁDIO 974,49.1%,24.6%,26.3%
6,2022-11-22,10:00:00,D,Dinamarca,Tunísia,CIDADE DA EDUCAÇÃO,56.0%,23.3%,20.7%
7,2022-11-22,16:00:00,D,França,Austrália,AL JANOUB,66.6%,20.3%,13.1%
8,2022-11-23,10:00:00,E,Alemanha,Japão,INTERNACIONAL KHALIFA,48.7%,24.7%,26.6%
9,2022-11-23,13:00:00,E,Espanha,Costa Rica,AL THUMAMA,61.3%,22.0%,16.8%
10,2022-11-23,07:00:00,F,Marrocos,Croácia,AL BAYT,29.2%,25.1%,45.7%
11,2022-11-23,16:00:00,F,Bélgica,Canadá,AHMAD BIN ALI,70.8%,18.7%,10.5%
12,2022-11-24,07:00:00,G,Suíça,Camarões,AL JANOUB,55.8%,23.4%,20.8%
13,2022-11-24,16:00:00,G,Brasil,Sérvia,NAC. LUSAIL,61.9%,21.8%,16.3%
14,2022-11-24,10:00:00,H,Uruguai,Coreia do Sul,CIDADE DA EDUCAÇÃO,51.1%,24.3%,24.6%
15,2022-11-24,13:00:00,H,Portugal,Gana,ESTÁDIO 974,77.9%,15.6%,6.4%
16,2022-11-25,10:00:00,A,Catar,Senegal,AL THUMAMA,17.2%,22.1%,60.6%
17,2022-11-25,13:00:00,A,Holanda,Equador,INTERNACIONAL KHALIFA,64.4%,21.0%,14.6%
18,2022-11-25,07:00:00,B,País de Gales,Irã,AHMAD BIN ALI,40.1%,25.5%,34.4%
19,2022-11-25,16:00:00,B,Inglaterra,Estados Unidos,AL BAYT,46.1%,25.0%,28.9%
20,2022-11-26,10:00:00,C,Polônia,Arábia Saudita,CIDADE DA EDUCAÇÃO,57.5%,22.9%,19.5%
21,2022-11-26,16:00:00,C,Argentina,México,NAC. LUSAIL,47.1%,24.9%,28.0%
22,2022-11-26,07:00:00,D,Tunísia,Austrália,AL JANOUB,41.4%,25.4%,33.1%
23,2022-11-26,13:00:00,D,França,Dinamarca,ESTÁDIO 974,45.3%,25.1%,29.6%
24,2022-11-27,07:00:00,E,Japão,Costa Rica,AHMAD BIN ALI,45.5%,25.1%,29.4%
25,2022-11-27,16:00:00,E,Espanha,Alemanha,AL BAYT,42.2%,25.4%,32.4%
26,2022-11-27,10:00:00,F,Bélgica,Marrocos,AL THUMAMA,60.1%,22.3%,17.6%
27,2022-11-27,13:00:00,F,Croácia,Canadá,INTERNACIONAL KHALIFA,58.8%,22.6%,18.6%
28,2022-11-28,07:00:00,G,Camarões,Sérvia,AL JANOUB,27.6%,24.8%,47.6%
29,2022-11-28,13:00:00,G,Brasil,Suíça,ESTÁDIO 974,54.2%,23.7%,22.1%
30,2022-11-28,10:00:00,H,Coreia do Sul,Gana,CIDADE DA EDUCAÇÃO,66.9%,20.2%,12.9%
31,2022-11-28,16:00:00,H,Portugal,Uruguai,NAC. LUSAIL,40.7%,25.5%,33.8%
32,2022-11-29,12:00:00,A,Holanda,Catar,AL BAYT,68.4%,19.6%,12.0%
33,2022-11-29,12:00:00,A,Equador,Senegal,INTERNACIONAL KHALIFA,20.7%,23.3%,56.0%
34,2022-11-29,16:00:00,B,País de Gales,Inglaterra,AHMAD BIN ALI,24.0%,24.2%,51.8%
35,2022-11-29,16:00:00,B,Irã,Estados Unidos,AL THUMAMA,29.1%,25.0%,45.9%
36,2022-11-30,16:00:00,C,Polônia,Argentina,ESTÁDIO 974,18.8%,22.7%,58.5%
37,2022-11-30,16:00:00,C,Arábia Saudita,México,NAC. LUSAIL,12.5%,19.9%,67.5%
38,2022-11-30,12:00:00,D,Tunísia,França,CIDADE DA EDUCAÇÃO,15.4%,21.4%,63.2%
39,2022-11-30,12:00:00,D,Austrália,Dinamarca,AL JANOUB,17.8%,22.3%,59.9%
40,2022-12-01,16:00:00,E,Japão,Espanha,INTERNACIONAL KHALIFA,22.6%,23.8%,53.6%
41,2022-12-01,16:00:00,E,Costa Rica,Alemanha,AL BAYT,20.1%,23.1%,56.8%
42,2022-12-01,12:00:00,F,Croácia,Bélgica,AHMAD BIN ALI,23.7%,24.1%,52.2%
43,2022-12-01,12:00:00,F,Canadá,Marrocos,AL THUMAMA,24.9%,24.4%,50.7%
44,2022-12-02,16:00:00,G,Camarões,Brasil,NAC. LUSAIL,11.0%,19.0%,70.0%
45,2022-12-02,16:00:00,G,Sérvia,Suíça,ESTÁDIO 974,29.3%,25.1%,45.7%
46,2022-12-02,12:00:00,H,Coreia do Sul,Portugal,CIDADE DA EDUCAÇÃO,21.8%,23.6%,54.5%
47,2022-12-02,12:00:00,H,Gana,Uruguai,AL JANOUB,7.4%,16.5%,76.1%

In [ ]:
# Exportando o resultado dos placares em uma planilha Excel

for i in range(jogos.shape[0]):
    selecao1 = jogos['seleção1'][i]
    selecao2 = jogos['seleção2'][i]
    placares = ProbabilidadesPartida(selecao1, selecao2)['matriz']

    tab_name = 'grupo' + jogos['grupo'][i] + selecao1 + 'x' + selecao2

    if i == 0:
        placares.to_excel('outputPlacaresPartida.xlsx', sheet_name = tab_name)
    else:
        # Append DataFrame em um arquivo Excel existente
        with pd.ExcelWriter('outputPlacaresPartida.xlsx', mode = 'a') as writer:
            placares.to_excel(writer, sheet_name = tab_name)

/usr/local/lib/python3.7/dist-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

---
## **Prever os Jogos da Copa! (Fase 2 - Jogo Mata Mata)**

In [ ]:
# Adicionando mais 3 colunas de probabilidades na tabela 'jogos'
jogos_fase2['Vitória'] = None
jogos_fase2['Derrota'] = None

# Iterando cada linha da tabela de 'jogos_fase2' e adicionando as 2 colunas com as probabilidades de vitória e derrota
for i in range(jogos_fase2.shape[0]):
    selecao1 = jogos_fase2['seleção1'][i]
    selecao2 = jogos_fase2['seleção2'][i]
    v, e, d = ProbabilidadesPartida(selecao1, selecao2)['probabilidades']
    # Como no jogo mata mata não há empate, a probabilidade de empate é dividida igualmente entre as seleções
    aux_v = round(float(v[:-1]) + float(e[:-1])/2, 1)
    aux_d = round(float(d[:-1]) + float(e[:-1])/2, 1)
    jogos_fase2.at[i,'Vitória'] = str(aux_v) + '%'
    jogos_fase2.at[i,'Derrota'] = str(aux_d) + '%'

# Exportando o resultado em uma planilha Excel
jogos_fase2.to_excel('outputEstimativasJogosCopaFase2.xlsx')
jogos_fase2

,etapa,data,hora,seleção1,seleção2,estádio,Vitória,Derrota
0,Oitavas,2022-12-03,12:00:00,Holanda,Estados Unidos,INTERNACIONAL KHALIFA,54.0%,46.0%
1,Oitavas,2022-12-03,16:00:00,Argentina,Austrália,AHMAD BIN ALI,77.0%,23.0%
2,Oitavas,2022-12-04,12:00:00,França,Polônia,AL BAYT,69.6%,30.5%
3,Oitavas,2022-12-04,16:00:00,Inglaterra,Senegal,AL BAYT,63.6%,36.4%
4,Oitavas,2022-12-05,12:00:00,Japão,Croácia,AL JANOUB,41.4%,58.6%
5,Oitavas,2022-12-05,16:00:00,Brasil,Coreia do Sul,ESTÁDIO 974,75.2%,24.8%
6,Oitavas,2022-12-06,12:00:00,Marrocos,Espanha,CIDADE DA EDUCAÇÃO,34.8%,65.2%
7,Oitavas,2022-12-06,16:00:00,Portugal,Suíça,NAC. LUSAIL,55.4%,44.5%
8,Quartas,2022-12-09,12:00:00,Croácia,Brasil,CIDADE DA EDUCAÇÃO,34.8%,65.2%
9,Quartas,2022-12-09,16:00:00,Holanda,Argentina,NAC. LUSAIL,43.0%,57.0%
10,Quartas,2022-12-10,12:00:00,Marrocos,Portugal,AL THUMAMA,37.6%,62.4%
11,Quartas,2022-12-10,16:00:00,Inglaterra,França,AL BAYT,48.0%,52.0%

In [ ]:
# Exportando o resultado dos placares em uma planilha Excel

for i in range(jogos_fase2.shape[0]):
    selecao1 = jogos_fase2['seleção1'][i]
    selecao2 = jogos_fase2['seleção2'][i]
    placares_fase2 = ProbabilidadesPartida(selecao1, selecao2)['matriz']

    tab_name_fase2 = selecao1 + 'x' + selecao2

    if i == 0:
        placares_fase2.to_excel('outputPlacaresPartidaFase2.xlsx', sheet_name = tab_name_fase2)
    else:
        # Append DataFrame em um arquivo Excel existente
        with pd.ExcelWriter('outputPlacaresPartidaFase2.xlsx', mode = 'a') as writer:
            placares_fase2.to_excel(writer, sheet_name = tab_name_fase2)

## **Simular Fase 1 da Copa do Mundo**

In [ ]:
# Verificando as seleções e sua ordem dentro do grupo

for i in list('ABCDEFGH'):
    times = list(selecoes.loc[selecoes['Grupo'] == i].index)
    print(f'Grupo: {i}, Seleção: {times}')

Grupo: A, Seleção: ['Catar', 'Equador', 'Senegal', 'Holanda']
Grupo: B, Seleção: ['Inglaterra', 'Irã', 'Estados Unidos', 'País de Gales']
Grupo: C, Seleção: ['Argentina', 'Arábia Saudita', 'México', 'Polônia']
Grupo: D, Seleção: ['Dinamarca', 'Tunísia', 'França', 'Austrália']
Grupo: E, Seleção: ['Alemanha', 'Japão', 'Espanha', 'Costa Rica']
Grupo: F, Seleção: ['Marrocos', 'Croácia', 'Bélgica', 'Canadá']
Grupo: G, Seleção: ['Suíça', 'Camarões', 'Brasil', 'Sérvia']
Grupo: H, Seleção: ['Uruguai', 'Coreia do Sul', 'Portugal', 'Gana']

In [ ]:
# Função que simula a Fase 1 da Copa de cada grupo
# A função recebe a tabela de seleções, o grupo e o dia (dia em que estamos na Copa)
# A função retorna uma lista com:
# - tabela com os pontos, saldo de gols e gols pró
# - tabela com o resultado de cada jogo do grupo
def JogosGrupo(dados, grupo, dia):

    # lista de todas as 4 seleções pertencentes ao grupo 'grupo'
    times = list(dados.loc[dados['Grupo'] == grupo].index)

    # nome das 4 seleções
    time1, time2, time3, time4 = times

    # Definindo das variáveis para critérios de desempate
    # pontos
    pt1, pt2, pt3, pt4 = 0, 0, 0, 0
    # saldo de gols
    sg1, sg2, sg3, sg4 = 0, 0, 0, 0
    # gols pró
    gp1, gp2, gp3, gp4 = 0, 0, 0, 0

    # Dia 0 - dia anterior ao início da copa, todos os jogos são simulações
    if dia == 'Dia 0':
        jogo1 = Jogo(time1, time2)
        jogo2 = Jogo(time3, time4)
        jogo3 = Jogo(time1, time3)
        jogo4 = Jogo(time2, time4)
        jogo5 = Jogo(time1, time4)
        jogo6 = Jogo(time2, time3)

    # Dia 1 (20 e 21/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 1':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else:
            jogo1 = Jogo(time1, time2)
            jogo2 = Jogo(time3, time4)
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 2 (22/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 2':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else:
            jogo1 = Jogo(time1, time2)
            jogo2 = Jogo(time3, time4)
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 3 (23/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 3':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else:
            jogo1 = Jogo(time1, time2)
            jogo2 = Jogo(time3, time4)
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 4 (24/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 4':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 5 (25/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 5':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 6 (26/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 6':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 7 (27/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 7':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            jogo3 = Jogo(time1, time3)
            jogo4 = Jogo(time2, time4)
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 8 (28/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 8':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Suiça x Brasil
            jogo3 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Camarões x Sérvia
            jogo4 = {'gols1': 3, 'gols2': 3, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '3x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Uruguai x Portugal
            jogo3 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Coreia do Sul x Gana
            jogo4 = {'gols1': 2, 'gols2': 3, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '2x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 9 (29/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 9':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Catar x Holanda
            jogo5 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Equador x Senegal
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Inglaterra x País de Gales
            jogo5 = {'gols1': 3, 'gols2': 0, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x0'}
            # Irã x Estados Unidos
            jogo6 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Suiça x Brasil
            jogo3 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Camarões x Sérvia
            jogo4 = {'gols1': 3, 'gols2': 3, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '3x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Uruguai x Portugal
            jogo3 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Coreia do Sul x Gana
            jogo4 = {'gols1': 2, 'gols2': 3, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '2x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 10 (30/11/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 10':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Catar x Holanda
            jogo5 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Equador x Senegal
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Inglaterra x País de Gales
            jogo5 = {'gols1': 3, 'gols2': 0, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x0'}
            # Irã x Estados Unidos
            jogo6 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Argentina x Polônia
            jogo5 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x México
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Dinamarca x Austrália
            jogo5 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Tunísia x França
            jogo6 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Suiça x Brasil
            jogo3 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Camarões x Sérvia
            jogo4 = {'gols1': 3, 'gols2': 3, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '3x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Uruguai x Portugal
            jogo3 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Coreia do Sul x Gana
            jogo4 = {'gols1': 2, 'gols2': 3, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '2x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 11 (01/12/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 11':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Catar x Holanda
            jogo5 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Equador x Senegal
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Inglaterra x País de Gales
            jogo5 = {'gols1': 3, 'gols2': 0, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x0'}
            # Irã x Estados Unidos
            jogo6 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Argentina x Polônia
            jogo5 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x México
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Dinamarca x Austrália
            jogo5 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Tunísia x França
            jogo6 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Alemanha x Costa Rica
            jogo5 = {'gols1': 4, 'gols2': 2, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x2'}
            # Japão x Espanha
            jogo6 = {'gols1': 2, 'gols2': 1, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x1'}
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Marrocos x Canadá
            jogo5 = {'gols1': 2, 'gols2': 1, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x1'}
            # Croácia x Bélgica
            jogo6 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Suiça x Brasil
            jogo3 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Camarões x Sérvia
            jogo4 = {'gols1': 3, 'gols2': 3, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '3x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Uruguai x Portugal
            jogo3 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Coreia do Sul x Gana
            jogo4 = {'gols1': 2, 'gols2': 3, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '2x3'}
            jogo5 = Jogo(time1, time4)
            jogo6 = Jogo(time2, time3)

    # Dia 12 (02/12/2022) - resultados dos jogos adicionados e os demais jogos simulados
    if dia == 'Dia 12':
        if grupo == 'A':
            # Catar x Equador
            jogo1 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Senegal x Holanda
            jogo2 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Catar x Senegal
            jogo3 = {'gols1': 1, 'gols2': 3, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x3'}
            # Holanda x Equador
            jogo4 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Catar x Holanda
            jogo5 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Equador x Senegal
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'B':
            # Inglaterra x Irã
            jogo1 = {'gols1': 6, 'gols2': 2, 'saldo1': 4, 'saldo2': -4, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '6x2'}
            # Estados Unidos x País de Gales
            jogo2 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Inglaterra x Estados Unidos
            jogo3 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Irã x País de Gales
            jogo4 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Inglaterra x País de Gales
            jogo5 = {'gols1': 3, 'gols2': 0, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x0'}
            # Irã x Estados Unidos
            jogo6 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
        elif grupo == 'C':
            # Argentina x Arábia Saudita
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # México x Polônia
            jogo2 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Argentina x México
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x Polônia
            jogo4 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Argentina x Polônia
            jogo5 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Arábia Saudita x México
            jogo6 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
        elif grupo == 'D':
            # Dinamarca x Tunísia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # França x Austrália
            jogo2 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Dinamarca x França
            jogo3 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Tunísia x Austrália
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Dinamarca x Austrália
            jogo5 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Tunísia x França
            jogo6 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
        elif grupo == 'E':
            # Alemanha x Japão
            jogo1 = {'gols1': 1, 'gols2': 2, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '1x2'}
            # Espanha x Costa Rica
            jogo2 = {'gols1': 7, 'gols2': 0, 'saldo1': 7, 'saldo2': -7, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '7x0'}
            # Espanha x Alemanha
            jogo3 = {'gols1': 1, 'gols2': 1, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '1x1'}
            # Japão x Costa Rica
            jogo4 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Alemanha x Costa Rica
            jogo5 = {'gols1': 4, 'gols2': 2, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x2'}
            # Japão x Espanha
            jogo6 = {'gols1': 2, 'gols2': 1, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x1'}
        elif grupo == 'F':
            # Marrocos x Croácia
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Bélgica x Canadá
            jogo2 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Marrocos x Bélgica
            jogo3 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Croácia x Canadá
            jogo4 = {'gols1': 4, 'gols2': 1, 'saldo1': 3, 'saldo2': -3, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '4x1'}
            # Marrocos x Canadá
            jogo5 = {'gols1': 2, 'gols2': 1, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x1'}
            # Croácia x Bélgica
            jogo6 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
        elif grupo == 'G':
            # Suíça x Camarões
            jogo1 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
            # Brasil x Sérvia
            jogo2 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Suiça x Brasil
            jogo3 = {'gols1': 0, 'gols2': 1, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x1'}
            # Camarões x Sérvia
            jogo4 = {'gols1': 3, 'gols2': 3, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '3x3'}
            # Suiça x Sérvia
            jogo5 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Camarões x Brasil
            jogo6 = {'gols1': 1, 'gols2': 0, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '1x0'}
        else: # Grupo 'H'
            # Uruguai x Coreia do Sul
            jogo1 = {'gols1': 0, 'gols2': 0, 'saldo1': 0, 'saldo2': 0, 'pontos1': 1, 'pontos2': 1, 'resultado': 'E', 'placar': '0x0'}
            # Portugal x Gana
            jogo2 = {'gols1': 3, 'gols2': 2, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '3x2'}
            # Uruguai x Portugal
            jogo3 = {'gols1': 0, 'gols2': 2, 'saldo1': -2, 'saldo2': 2, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '0x2'}
            # Coreia do Sul x Gana
            jogo4 = {'gols1': 2, 'gols2': 3, 'saldo1': -1, 'saldo2': 1, 'pontos1': 0, 'pontos2': 3, 'resultado': 'D', 'placar': '2x3'}
            # Uruguai x Gana
            jogo5 = {'gols1': 2, 'gols2': 0, 'saldo1': 2, 'saldo2': -2, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x0'}
            # Coreia do Sul x Portugal
            jogo6 = {'gols1': 2, 'gols2': 1, 'saldo1': 1, 'saldo2': -1, 'pontos1': 3, 'pontos2': 0, 'resultado': 'V', 'placar': '2x1'}

    # Resultado do Jogo1
    pt1, pt2 = pt1 + jogo1['pontos1'], pt2 + jogo1['pontos2']
    sg1, sg2 = sg1 + jogo1['saldo1'], sg2 + jogo1['saldo2']
    gp1, gp2 = gp1 + jogo1['gols1'], gp2 + jogo1['gols2']

    # Resultado do Jogo2
    pt3, pt4 = pt3 + jogo2['pontos1'], pt4 + jogo2['pontos2']
    sg3, sg4 = sg3 + jogo2['saldo1'], sg4 + jogo2['saldo2']
    gp3, gp4 = gp3 + jogo2['gols1'], gp4 + jogo2['gols2']

    # Resultado do Jogo3
    pt1, pt3 = pt1 + jogo3['pontos1'], pt3 + jogo3['pontos2']
    sg1, sg3 = sg1 + jogo3['saldo1'], sg3 + jogo3['saldo2']
    gp1, gp3 = gp1 + jogo3['gols1'], gp3 + jogo3['gols2']

    # Resultado do Jogo4
    pt2, pt4 = pt2 + jogo4['pontos1'], pt4 + jogo4['pontos2']
    sg2, sg4 = sg2 + jogo4['saldo1'], sg4 + jogo4['saldo2']
    gp2, gp4 = gp2 + jogo4['gols1'], gp4 + jogo4['gols2']

    # Resultado do Jogo5
    pt1, pt4 = pt1 + jogo5['pontos1'], pt4 + jogo5['pontos2']
    sg1, sg4 = sg1 + jogo5['saldo1'], sg4 + jogo5['saldo2']
    gp1, gp4 = gp1 + jogo5['gols1'], gp4 + jogo5['gols2']

    # Resultado do Jogo6
    pt2, pt3 = pt2 + jogo6['pontos1'], pt3 + jogo6['pontos2']
    sg2, sg3 = sg2 + jogo6['saldo1'], sg3 + jogo6['saldo2']
    gp2, gp3 = gp2 + jogo6['gols1'], gp3 + jogo6['gols2']

    # Gerando tabela com os pontos, saldo de gols e gols pró
    # e ordenando as seleções de acordo com os critérios de classificação ('Pontos', 'Saldo de Gols', 'Gols Pró')
    colunas = ['Pontos', 'Saldo de Gols', 'Gols Pró']
    tabela = pd.DataFrame([[pt1, pt2, pt3, pt4],
                           [sg1, sg2, sg3, sg4],
                           [gp1, gp2, gp3, gp4]], index = colunas, columns = times).transpose()
    tabela = tabela.sort_values(['Pontos', 'Saldo de Gols', 'Gols Pró'], ascending = False)
    tabela['Posição'] = [1, 2, 3, 4]

    # Gerando tabela com o resultado de cada jogo do grupo
    partidas = [ time1 + ' x ' + time2,
                 time3 + ' x ' + time4,
                 time1 + ' x ' + time3,
                 time2 + ' x ' + time4,
                 time1 + ' x ' + time4,
                 time2 + ' x ' + time3 ]
    placares = [jogo1['placar'], jogo2['placar'], jogo3['placar'], jogo4['placar'], jogo5['placar'], jogo6['placar']]
    resultados = [jogo1['resultado'], jogo2['resultado'], jogo3['resultado'], jogo4['resultado'], jogo5['resultado'], jogo6['resultado']]
    jogos = pd.DataFrame([partidas, placares, resultados]).transpose()
    jogos.columns = ['Partida', 'Placar', 'Resultado']

    return [tabela, jogos]

In [ ]:
# Fase 1 do Grupo G
exemplo = JogosGrupo(selecoes, 'G')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Brasil         9              9        10        1
 Suíça          3              0         5        2
 Sérvia         3             -4         4        3
 Camarões       3             -5         2        4,
              Partida Placar Resultado
 0    Brasil x Sérvia    5x1         V
 1   Suíça x Camarões    4x0         V
 2     Brasil x Suíça    2x0         V
 3  Sérvia x Camarões    0x2         D
 4  Brasil x Camarões    3x0         V
 5     Sérvia x Suíça    3x1         V]

In [ ]:
exemplo[0]

          Pontos  Saldo de Gols  Gols Pró  Posição
Brasil         9              9        10        1
Suíça          3              0         5        2
Sérvia         3             -4         4        3
Camarões       3             -5         2        4

In [ ]:
exemplo[1]

             Partida Placar Resultado
0    Brasil x Sérvia    5x1         V
1   Suíça x Camarões    4x0         V
2     Brasil x Suíça    2x0         V
3  Sérvia x Camarões    0x2         D
4  Brasil x Camarões    3x0         V
5     Sérvia x Suíça    3x1         V

### **Validando os dados inseridos em cada dia**

In [ ]:
# Fase 1 do Grupo A do Dia 1
exemplo = JogosGrupo(selecoes, 'A', 'Dia 1')
exemplo

[         Pontos  Saldo de Gols  Gols Pró  Posição
 Equador       6              3         5        1
 Holanda       6              2         4        2
 Catar         4             -1         1        3
 Senegal       1             -4         0        4,
              Partida Placar Resultado
 0    Catar x Equador    0x2         D
 1  Senegal x Holanda    0x2         D
 2    Catar x Senegal    0x0         E
 3  Equador x Holanda    1x2         D
 4    Catar x Holanda    1x0         V
 5  Equador x Senegal    2x0         V]

In [ ]:
# Fase 1 do Grupo B do Dia 1
exemplo = JogosGrupo(selecoes, 'B', 'Dia 1')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Inglaterra           9              7        10        1
 País de Gales        4              1         5        2
 Estados Unidos       2             -2         2        3
 Irã                  1             -6         4        4,
                           Partida Placar Resultado
 0                Inglaterra x Irã    6x2         V
 1  Estados Unidos x País de Gales    1x1         E
 2     Inglaterra x Estados Unidos    2x0         V
 3             Irã x País de Gales    1x3         D
 4      Inglaterra x País de Gales    2x1         V
 5            Irã x Estados Unidos    1x1         E]

In [ ]:
# Fase 1 do Grupo C do Dia 2
exemplo = JogosGrupo(selecoes, 'C', 'Dia 2')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Argentina            6              2         5        1
 México               4              1         5        2
 Arábia Saudita       4             -2         3        3
 Polônia              2             -1         0        4,
                       Partida Placar Resultado
 0  Argentina x Arábia Saudita    1x2         D
 1            México x Polônia    0x0         E
 2          Argentina x México    3x1         V
 3    Arábia Saudita x Polônia    0x0         E
 4         Argentina x Polônia    1x0         V
 5     Arábia Saudita x México    1x4         D]

In [ ]:
# Fase 1 do Grupo D do Dia 2
exemplo = JogosGrupo(selecoes, 'D', 'Dia 2')
exemplo

[           Pontos  Saldo de Gols  Gols Pró  Posição
 Dinamarca       7              5         6        1
 França          6              4         8        2
 Tunísia         4             -2         2        3
 Austrália       0             -7         2        4,
                  Partida Placar Resultado
 0    Dinamarca x Tunísia    0x0         E
 1     França x Austrália    4x1         V
 2     Dinamarca x França    3x1         V
 3    Tunísia x Austrália    2x1         V
 4  Dinamarca x Austrália    3x0         V
 5       Tunísia x França    0x3         D]

In [ ]:
# Fase 1 do Grupo E do Dia 3
exemplo = JogosGrupo(selecoes, 'E', 'Dia 3')
exemplo

[            Pontos  Saldo de Gols  Gols Pró  Posição
 Espanha          5              7         9        1
 Japão            5              1         5        2
 Alemanha         4              0         4        3
 Costa Rica       1             -8         3        4,
                  Partida Placar Resultado
 0       Alemanha x Japão    1x2         D
 1   Espanha x Costa Rica    7x0         V
 2     Alemanha x Espanha    1x1         E
 3     Japão x Costa Rica    2x2         E
 4  Alemanha x Costa Rica    2x1         V
 5        Japão x Espanha    1x1         E]

In [ ]:
# Fase 1 do Grupo F do Dia 3
exemplo = JogosGrupo(selecoes, 'F', 'Dia 3')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Bélgica        7              2         3        1
 Marrocos       5              1         2        2
 Croácia        4              0         2        3
 Canadá         0             -3         1        4,
               Partida Placar Resultado
 0  Marrocos x Croácia    0x0         E
 1    Bélgica x Canadá    1x0         V
 2  Marrocos x Bélgica    0x0         E
 3    Croácia x Canadá    1x0         V
 4   Marrocos x Canadá    2x1         V
 5   Croácia x Bélgica    1x2         D]

In [ ]:
# Fase 1 do Grupo G do Dia 4
exemplo = JogosGrupo(selecoes, 'G', 'Dia 4')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Camarões       6              2         4        1
 Suíça          6              1         4        2
 Sérvia         3             -1         3        3
 Brasil         3             -2         3        4,
              Partida Placar Resultado
 0   Suíça x Camarões    1x0         V
 1    Brasil x Sérvia    2x0         V
 2     Suíça x Brasil    3x1         V
 3  Camarões x Sérvia    2x1         V
 4     Suíça x Sérvia    0x2         D
 5  Camarões x Brasil    2x0         V]

In [ ]:
# Fase 1 do Grupo H do Dia 4
exemplo = JogosGrupo(selecoes, 'H', 'Dia 4')
exemplo

[               Pontos  Saldo de Gols  Gols Pró  Posição
 Portugal            6              2         5        1
 Uruguai             5              1         1        2
 Gana                2             -1         3        3
 Coreia do Sul       2             -2         1        4,
                     Partida Placar Resultado
 0   Uruguai x Coreia do Sul    0x0         E
 1           Portugal x Gana    3x2         V
 2        Uruguai x Portugal    1x0         V
 3      Coreia do Sul x Gana    1x1         E
 4            Uruguai x Gana    0x0         E
 5  Coreia do Sul x Portugal    0x2         D]

In [ ]:
# Fase 1 do Grupo A do Dia 5
exemplo = JogosGrupo(selecoes, 'A', 'Dia 5')
exemplo

[         Pontos  Saldo de Gols  Gols Pró  Posição
 Senegal       6              2         6        1
 Holanda       5              2         6        2
 Equador       4              0         4        3
 Catar         1             -4         4        4,
              Partida Placar Resultado
 0    Catar x Equador    0x2         D
 1  Senegal x Holanda    0x2         D
 2    Catar x Senegal    1x3         D
 3  Equador x Holanda    1x1         E
 4    Catar x Holanda    3x3         E
 5  Equador x Senegal    1x3         D]

In [ ]:
# Fase 1 do Grupo B do Dia 5
exemplo = JogosGrupo(selecoes, 'B', 'Dia 5')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Inglaterra           7              5         7        1
 Estados Unidos       5              5         7        2
 Irã                  3             -7         5        3
 País de Gales        1             -3         1        4,
                           Partida Placar Resultado
 0                Inglaterra x Irã    6x2         V
 1  Estados Unidos x País de Gales    1x1         E
 2     Inglaterra x Estados Unidos    0x0         E
 3             Irã x País de Gales    2x0         V
 4      Inglaterra x País de Gales    1x0         V
 5            Irã x Estados Unidos    1x6         D]

In [ ]:
# Fase 1 do Grupo C do Dia 6
exemplo = JogosGrupo(selecoes, 'C', 'Dia 6')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Polônia              7              3         4        1
 México               4              0         2        2
 Argentina            3              0         4        3
 Arábia Saudita       3             -3         2        4,
                       Partida Placar Resultado
 0  Argentina x Arábia Saudita    1x2         D
 1            México x Polônia    0x0         E
 2          Argentina x México    2x0         V
 3    Arábia Saudita x Polônia    0x2         D
 4         Argentina x Polônia    1x2         D
 5     Arábia Saudita x México    0x2         D]

In [ ]:
# Fase 1 do Grupo D do Dia 6
exemplo = JogosGrupo(selecoes, 'D', 'Dia 6')
exemplo

[           Pontos  Saldo de Gols  Gols Pró  Posição
 França          9              7         9        1
 Austrália       4             -2         5        2
 Dinamarca       2             -1         4        3
 Tunísia         1             -4         0        4,
                  Partida Placar Resultado
 0    Dinamarca x Tunísia    0x0         E
 1     França x Austrália    4x1         V
 2     Dinamarca x França    1x2         D
 3    Tunísia x Austrália    0x1         D
 4  Dinamarca x Austrália    3x3         E
 5       Tunísia x França    0x3         D]

In [ ]:
# Fase 1 do Grupo E do Dia 7
exemplo = JogosGrupo(selecoes, 'E', 'Dia 7')
exemplo

[            Pontos  Saldo de Gols  Gols Pró  Posição
 Espanha          7              8        10        1
 Costa Rica       6             -5         4        2
 Japão            3             -1         3        3
 Alemanha         1             -2         4        4,
                  Partida Placar Resultado
 0       Alemanha x Japão    1x2         D
 1   Espanha x Costa Rica    7x0         V
 2     Alemanha x Espanha    1x1         E
 3     Japão x Costa Rica    0x1         D
 4  Alemanha x Costa Rica    2x3         D
 5        Japão x Espanha    1x2         D]

In [ ]:
# Fase 1 do Grupo F do Dia 7
exemplo = JogosGrupo(selecoes, 'F', 'Dia 7')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Marrocos       7              3         3        1
 Bélgica        6              0         3        2
 Croácia        4              2         5        3
 Canadá         0             -5         1        4,
               Partida Placar Resultado
 0  Marrocos x Croácia    0x0         E
 1    Bélgica x Canadá    1x0         V
 2  Marrocos x Bélgica    2x0         V
 3    Croácia x Canadá    4x1         V
 4   Marrocos x Canadá    1x0         V
 5   Croácia x Bélgica    1x2         D]

In [ ]:
# Fase 1 do Grupo G do Dia 8
exemplo = JogosGrupo(selecoes, 'G', 'Dia 8')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Brasil         9              4         5        1
 Suíça          6              1         4        2
 Camarões       1             -2         4        3
 Sérvia         1             -3         5        4,
              Partida Placar Resultado
 0   Suíça x Camarões    1x0         V
 1    Brasil x Sérvia    2x0         V
 2     Suíça x Brasil    0x1         D
 3  Camarões x Sérvia    3x3         E
 4     Suíça x Sérvia    3x2         V
 5  Camarões x Brasil    1x2         D]

In [ ]:
# Fase 1 do Grupo H do Dia 8
exemplo = JogosGrupo(selecoes, 'H', 'Dia 8')
exemplo

[               Pontos  Saldo de Gols  Gols Pró  Posição
 Portugal            9              7         9        1
 Uruguai             4              2         4        2
 Gana                3             -4         5        3
 Coreia do Sul       1             -5         2        4,
                     Partida Placar Resultado
 0   Uruguai x Coreia do Sul    0x0         E
 1           Portugal x Gana    3x2         V
 2        Uruguai x Portugal    0x2         D
 3      Coreia do Sul x Gana    2x3         D
 4            Uruguai x Gana    4x0         V
 5  Coreia do Sul x Portugal    0x4         D]

In [ ]:
# Fase 1 do Grupo A do Dia 9
exemplo = JogosGrupo(selecoes, 'A', 'Dia 9')
exemplo

[         Pontos  Saldo de Gols  Gols Pró  Posição
 Holanda       7              4         5        1
 Senegal       6              1         5        2
 Equador       4              1         4        3
 Catar         0             -6         1        4,
              Partida Placar Resultado
 0    Catar x Equador    0x2         D
 1  Senegal x Holanda    0x2         D
 2    Catar x Senegal    1x3         D
 3  Equador x Holanda    1x1         E
 4    Catar x Holanda    0x2         D
 5  Equador x Senegal    1x2         D]

In [ ]:
# Fase 1 do Grupo B do Dia 9
exemplo = JogosGrupo(selecoes, 'B', 'Dia 9')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Inglaterra           7              7         9        1
 Estados Unidos       5              1         2        2
 Irã                  3             -3         4        3
 País de Gales        1             -5         1        4,
                           Partida Placar Resultado
 0                Inglaterra x Irã    6x2         V
 1  Estados Unidos x País de Gales    1x1         E
 2     Inglaterra x Estados Unidos    0x0         E
 3             Irã x País de Gales    2x0         V
 4      Inglaterra x País de Gales    3x0         V
 5            Irã x Estados Unidos    0x1         D]

In [ ]:
# Fase 1 do Grupo C do Dia 10
exemplo = JogosGrupo(selecoes, 'C', 'Dia 10')
exemplo

[                Pontos  Saldo de Gols  Gols Pró  Posição
 Argentina            6              3         5        1
 Polônia              4              0         2        2
 México               4             -1         2        3
 Arábia Saudita       3             -2         3        4,
                       Partida Placar Resultado
 0  Argentina x Arábia Saudita    1x2         D
 1            México x Polônia    0x0         E
 2          Argentina x México    2x0         V
 3    Arábia Saudita x Polônia    0x2         D
 4         Argentina x Polônia    2x0         V
 5     Arábia Saudita x México    1x2         D]

In [ ]:
# Fase 1 do Grupo D do Dia 10
exemplo = JogosGrupo(selecoes, 'D', 'Dia 10')
exemplo

[           Pontos  Saldo de Gols  Gols Pró  Posição
 França          6              3         6        1
 Austrália       6             -1         3        2
 Tunísia         4              0         1        3
 Dinamarca       1             -2         1        4,
                  Partida Placar Resultado
 0    Dinamarca x Tunísia    0x0         E
 1     França x Austrália    4x1         V
 2     Dinamarca x França    1x2         D
 3    Tunísia x Austrália    0x1         D
 4  Dinamarca x Austrália    0x1         D
 5       Tunísia x França    1x0         V]

In [ ]:
# Fase 1 do Grupo E do Dia 11
exemplo = JogosGrupo(selecoes, 'E', 'Dia 11')
exemplo

[            Pontos  Saldo de Gols  Gols Pró  Posição
 Japão            6              1         4        1
 Espanha          4              6         9        2
 Alemanha         4              1         6        3
 Costa Rica       3             -8         3        4,
                  Partida Placar Resultado
 0       Alemanha x Japão    1x2         D
 1   Espanha x Costa Rica    7x0         V
 2     Alemanha x Espanha    1x1         E
 3     Japão x Costa Rica    0x1         D
 4  Alemanha x Costa Rica    4x2         V
 5        Japão x Espanha    2x1         V]

In [ ]:
# Fase 1 do Grupo F do Dia 11
exemplo = JogosGrupo(selecoes, 'F', 'Dia 11')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Marrocos       7              3         4        1
 Croácia        5              3         4        2
 Bélgica        4             -1         1        3
 Canadá         0             -5         2        4,
               Partida Placar Resultado
 0  Marrocos x Croácia    0x0         E
 1    Bélgica x Canadá    1x0         V
 2  Marrocos x Bélgica    2x0         V
 3    Croácia x Canadá    4x1         V
 4   Marrocos x Canadá    2x1         V
 5   Croácia x Bélgica    0x0         E]

In [ ]:
# Fase 1 do Grupo G do Dia 12
exemplo = JogosGrupo(selecoes, 'G', 'Dia 12')
exemplo

[          Pontos  Saldo de Gols  Gols Pró  Posição
 Brasil         6              2         3        1
 Suíça          6              1         4        2
 Camarões       4              0         4        3
 Sérvia         1             -3         5        4,
              Partida Placar Resultado
 0   Suíça x Camarões    1x0         V
 1    Brasil x Sérvia    2x0         V
 2     Suíça x Brasil    0x1         D
 3  Camarões x Sérvia    3x3         E
 4     Suíça x Sérvia    3x2         V
 5  Camarões x Brasil    1x0         V]

In [ ]:
# Fase 1 do Grupo H do Dia 12
exemplo = JogosGrupo(selecoes, 'H', 'Dia 12')
exemplo

[               Pontos  Saldo de Gols  Gols Pró  Posição
 Portugal            6              2         6        1
 Coreia do Sul       4              0         4        2
 Uruguai             4              0         2        3
 Gana                3             -2         5        4,
                     Partida Placar Resultado
 0   Uruguai x Coreia do Sul    0x0         E
 1           Portugal x Gana    3x2         V
 2        Uruguai x Portugal    0x2         D
 3      Coreia do Sul x Gana    2x3         D
 4            Uruguai x Gana    2x0         V
 5  Coreia do Sul x Portugal    2x1         V]

## **Simular Fase 2 da Copa do Mundo**

In [ ]:
# Função para simular um Jogo Mata Mata entre 'selecao1' e 'selecao2'
# A função recebe 'selecao1' e 'selecao2' (que são os nomes dos países)
# A função retorna a seleção que venceu o jogo
def JogoMataMata(selecao1, selecao2):
    jogo = Jogo(selecao1, selecao2)
    resultado = jogo['resultado']
    if resultado == 'V':
        return selecao1
    elif resultado == 'D':
        return selecao2
    else:
        # se acontecer um empate, independente se prorrogação ou penaltis,
        # está sendo considerado que cada seleção tem 50% de chance de ganhar
        return random.sample([selecao1, selecao2], 1)[0]

# Função que simula uma copa
# A função recebe a tabela de seleções
# A função retorna a simulação de 1 copa
def SimulaCopa(dados, dia, etapa):

    # Criando a tabela para guardar o resultado da simulação
    colunas = ['1st', '2nd', '3rd', '4th', 'Oitavas', 'Quartas', 'Semis', 'Final', 'Campeão', '2 lugar', '3 lugar']
    n = dados.shape[0]
    m = len(colunas)
    aux = np.array(np.zeros(n*m).reshape(n, m))
    info = pd.DataFrame(aux, columns = colunas, index = dados.index)
    info = info.astype(int)

    if etapa == 'Fase 1':
        # Simulando os jogos da Fase 1
        # TOP 16 seleções que passam para a próxima fase (Oitavas)
        top16 = []
        for i in list('ABCDEFGH'):
            # tabela com as seleções em ordem de classificação
            tab_classif = JogosGrupo(dados, grupo = i, dia = dia)[0]
            # guardando as 2 seleções classificadas para formar as TOP 16 seleções
            top16 += tab_classif.index[:2].tolist()
            # preenchendo as seleções de acordo com a classificação obtida durante a Fase 1
            tab_classif_nomes = tab_classif.index.to_list()
            info.at[tab_classif_nomes[0], '1st'] = 1
            info.at[tab_classif_nomes[1], '2nd'] = 1
            info.at[tab_classif_nomes[2], '3rd'] = 1
            info.at[tab_classif_nomes[3], '4th'] = 1

        # Simulando os jogos das Oitavas de Final
        # Resultando nos Finalistas das Quartas de Final
        qf1 = JogoMataMata(top16[0], top16[3])   # 1º A x 2º B
        qf2 = JogoMataMata(top16[2], top16[1])   # 1º B x 2º A
        qf3 = JogoMataMata(top16[4], top16[7])   # 1º C x 2º D
        qf4 = JogoMataMata(top16[6], top16[5])   # 1º D x 2º C
        qf5 = JogoMataMata(top16[8], top16[11])  # 1º E x 2º F
        qf6 = JogoMataMata(top16[10], top16[9])  # 1º F x 2º E
        qf7 = JogoMataMata(top16[12], top16[15]) # 1º G x 2º H
        qf8 = JogoMataMata(top16[14], top16[13]) # 1º H x 2º G

        # TOP 8 seleções que passam para a próxima fase (Quartas)
        top8 = [qf1, qf2, qf3, qf4, qf5, qf6, qf7, qf8]

        # Simulando os jogos das Quartas de Final
        # Resultando nos Finalistas da Semifinal
        sf1 = JogoMataMata(qf1, qf3)
        sf2 = JogoMataMata(qf2, qf4)
        sf3 = JogoMataMata(qf5, qf7)
        sf4 = JogoMataMata(qf6, qf8)

        # TOP 4 seleções que passam para a próxima fase (Semifinal)
        top4 = [sf1, sf2, sf3, sf4]

        # Simulando os jogos das Semifinais
        # Resultando nos Finalistas da Final
        f1 = JogoMataMata(sf1, sf3)
        f2 = JogoMataMata(sf2, sf4)

        # Jogo para definir o 3º lugar
        # Encontrar o primeiro perdedor
        if f1 == sf1:
            perdedor1 = sf3
        else:
            perdedor1 = sf1

        # Encontrar o segundo perdedor
        if f2 == sf2:
            perdedor2 = sf4
        else:
            perdedor2 = sf2

        lugar3 = JogoMataMata(perdedor1, perdedor2)

        # TOP 2 seleções que passam para a próxima fase (Final)
        top2 = [f1, f2]

        # Simulando o jogo da Final
        # Resultando no Campeão da Copa
        top1 = JogoMataMata(f1, f2)

        # Resultado do 2º lugar
        if top1 == f1:
            lugar2 = f2
        else:
            lugar2 = f1

    if etapa == 'Oitavas':
        # Simulando os jogos da Fase 1
        # TOP 16 seleções que passam para a próxima fase (Oitavas)
        top16 = []
        for i in list('ABCDEFGH'):
            # tabela com as seleções em ordem de classificação
            tab_classif = JogosGrupo(dados, grupo = i, dia = 'Dia 12')[0]
            # guardando as 2 seleções classificadas para formar as TOP 16 seleções
            top16 += tab_classif.index[:2].tolist()
            # preenchendo as seleções de acordo com a classificação obtida durante a Fase 1
            tab_classif_nomes = tab_classif.index.to_list()
            info.at[tab_classif_nomes[0], '1st'] = 1
            info.at[tab_classif_nomes[1], '2nd'] = 1
            info.at[tab_classif_nomes[2], '3rd'] = 1
            info.at[tab_classif_nomes[3], '4th'] = 1

        # Simulando os jogos das Oitavas de Final
        # Resultando nos Finalistas das Quartas de Final
        qf1 = top16[0] #JogoMataMata(top16[0], top16[3])   # 1º A x 2º B
        qf2 = top16[2] #JogoMataMata(top16[2], top16[1])   # 1º B x 2º A
        qf3 = top16[4] #JogoMataMata(top16[4], top16[7])   # 1º C x 2º D
        qf4 = top16[6] #JogoMataMata(top16[6], top16[5])   # 1º D x 2º C
        qf5 = top16[11] #JogoMataMata(top16[8], top16[11])  # 1º E x 2º F
        qf6 = top16[10] #JogoMataMata(top16[10], top16[9])  # 1º F x 2º E
        qf7 = top16[12] #JogoMataMata(top16[12], top16[15]) # 1º G x 2º H
        qf8 = top16[14] #JogoMataMata(top16[14], top16[13]) # 1º H x 2º G

        # TOP 8 seleções que passam para a próxima fase (Quartas)
        top8 = [qf1, qf2, qf3, qf4, qf5, qf6, qf7, qf8]

        # Simulando os jogos das Quartas de Final
        # Resultando nos Finalistas da Semifinal
        sf1 = JogoMataMata(qf1, qf3)
        sf2 = JogoMataMata(qf2, qf4)
        sf3 = JogoMataMata(qf5, qf7)
        sf4 = JogoMataMata(qf6, qf8)

        # TOP 4 seleções que passam para a próxima fase (Semifinal)
        top4 = [sf1, sf2, sf3, sf4]

        # Simulando os jogos das Semifinais
        # Resultando nos Finalistas da Final
        f1 = JogoMataMata(sf1, sf3)
        f2 = JogoMataMata(sf2, sf4)

        # Jogo para definir o 3º lugar
        # Encontrar o primeiro perdedor
        if f1 == sf1:
            perdedor1 = sf3
        else:
            perdedor1 = sf1

        # Encontrar o segundo perdedor
        if f2 == sf2:
            perdedor2 = sf4
        else:
            perdedor2 = sf2

        lugar3 = JogoMataMata(perdedor1, perdedor2)

        # TOP 2 seleções que passam para a próxima fase (Final)
        top2 = [f1, f2]

        # Simulando o jogo da Final
        # Resultando no Campeão da Copa
        top1 = JogoMataMata(f1, f2)

        # Resultado do 2º lugar
        if top1 == f1:
            lugar2 = f2
        else:
            lugar2 = f1

    # Guardando a informação na tabela criada
    info.at[top16, 'Oitavas'] = 1
    info.at[top8, 'Quartas'] = 1
    info.at[top4, 'Semis'] = 1
    info.at[top2, 'Final'] = 1
    info.at[top1, 'Campeão'] = 1
    info.at[lugar2, '2 lugar'] = 1
    info.at[lugar3, '3 lugar'] = 1

    return [info, top16, top8]

In [ ]:
# TOP16
SimulaCopa(selecoes, 'Dia 12', 'Fase 1')[1]

['Holanda',
 'Senegal',
 'Inglaterra',
 'Estados Unidos',
 'Argentina',
 'Polônia',
 'França',
 'Austrália',
 'Japão',
 'Espanha',
 'Marrocos',
 'Croácia',
 'Brasil',
 'Suíça',
 'Portugal',
 'Coreia do Sul']

In [ ]:
# TOP8
SimulaCopa(selecoes, 'Dia 12', 'Oitavas')[2]

['Holanda',
 'Inglaterra',
 'Argentina',
 'França',
 'Croácia',
 'Marrocos',
 'Brasil',
 'Portugal']

In [ ]:
SimulaCopa(selecoes, 'Dia 12', 'Oitavas')[0]

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar
Seleção,,,,,,,,,,,
Catar,0,0,0,1,0,0,0,0,0,0,0
Equador,0,0,1,0,0,0,0,0,0,0,0
Senegal,0,1,0,0,1,0,0,0,0,0,0
Holanda,1,0,0,0,1,1,0,0,0,0,0
Inglaterra,1,0,0,0,1,1,0,0,0,0,0
Irã,0,0,1,0,0,0,0,0,0,0,0
Estados Unidos,0,1,0,0,1,0,0,0,0,0,0
País de Gales,0,0,0,1,0,0,0,0,0,0,0
Argentina,1,0,0,0,1,1,1,1,0,1,0
Arábia Saudita,0,0,0,1,0,0,0,0,0,0,0
México,0,0,1,0,0,0,0,0,0,0,0
Polônia,0,1,0,0,1,0,0,0,0,0,0
Dinamarca,0,0,0,1,0,0,0,0,0,0,0
Tunísia,0,0,1,0,0,0,0,0,0,0,0
França,1,0,0,0,1,1,1,0,0,0,1
Austrália,0,1,0,0,1,0,0,0,0,0,0
Alemanha,0,0,1,0,0,0,0,0,0,0,0
Japão,1,0,0,0,1,0,0,0,0,0,0
Espanha,0,1,0,0,1,0,0,0,0,0,0
Costa Rica,0,0,0,1,0,0,0,0,0,0,0
Marrocos,1,0,0,0,1,1,1,1,1,0,0
Croácia,0,1,0,0,1,1,1,0,0,0,0
Bélgica,0,0,1,0,0,0,0,0,0,0,0
Canadá,0,0,0,1,0,0,0,0,0,0,0
Suíça,0,1,0,0,1,0,0,0,0,0,0
Camarões,0,0,1,0,0,0,0,0,0,0,0
Brasil,1,0,0,0,1,1,0,0,0,0,0
Sérvia,0,0,0,1,0,0,0,0,0,0,0
Uruguai,0,0,1,0,0,0,0,0,0,0,0
Coreia do Sul,0,1,0,0,1,0,0,0,0,0,0
Portugal,1,0,0,0,1,1,0,0,0,0,0
Gana,0,0,0,1,0,0,0,0,0,0,0

In [ ]:
# Validando os valores
SimulaCopa(selecoes, 'Dia 12', 'Oitavas')[0].sum()

1st         8
2nd         8
3rd         8
4th         8
Oitavas    16
Quartas     8
Semis       4
Final       2
Campeão     1
2 lugar     1
3 lugar     1
dtype: int64

## **Simular várias vezes Copa do Mundo**

In [ ]:
# Função que simula a copa n vezes
# A função recebe a tabela de seleções e a quantidade de simulações ('S')
# A função retorna uma tabela com todas as simulações com a frequência relativa e ordenada pelo 'Campeão'
def SimulacaoTotal(dados, dia, etapa, S = 1000):
    print('IA: "Iniciando simulação..."')
    info = SimulaCopa(dados, dia, etapa)[0]
    for i in range(S-1):
        info += SimulaCopa(dados, dia, etapa)[0]
        if (i+2)%(S/10) == 0:
            print('IA: "Simulações de Copas do Mundo: {:.0f}% completas'.format(100*((i+2)/S)))
    print('IA: "Simulação Finalizada!"')
    return info.sort_values(by = 'Campeão', ascending = False)/S

### **Dia 0**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 0'

S = 100000
dia = 'Dia 0'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia0.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.59736,0.25113,0.10983,0.04168,0.84849,0.56643,0.35039,0.21647,0.13144,0.08503,0.08493,Dia 0
Bélgica,0.57643,0.25989,0.12104,0.04264,0.83632,0.53947,0.33447,0.20396,0.12234,0.08162,0.08122,Dia 0
Argentina,0.52993,0.29001,0.14000,0.04006,0.81994,0.49153,0.30047,0.16749,0.09485,0.07264,0.07877,Dia 0
França,0.51725,0.29492,0.13424,0.05359,0.81217,0.48251,0.29338,0.16310,0.09044,0.07266,0.07551,Dia 0
Inglaterra,0.44267,0.27133,0.17513,0.11087,0.71400,0.45973,0.25247,0.13555,0.07203,0.06352,0.06644,Dia 0
Espanha,0.44490,0.28840,0.17717,0.08953,0.73330,0.40263,0.21533,0.11564,0.05822,0.05742,0.05438,Dia 0
Holanda,0.53272,0.28952,0.12861,0.04915,0.82224,0.44312,0.22297,0.11135,0.05384,0.05751,0.05796,Dia 0
Portugal,0.46043,0.32502,0.17925,0.03530,0.78545,0.41105,0.20916,0.10723,0.05191,0.05532,0.05265,Dia 0
Dinamarca,0.33171,0.35864,0.20733,0.10232,0.69035,0.35318,0.18760,0.09102,0.04218,0.04884,0.04816,Dia 0
México,0.30667,0.36202,0.23819,0.09312,0.66869,0.33442,0.17448,0.08214,0.03794,0.04420,0.04431,Dia 0
Alemanha,0.32799,0.31570,0.22381,0.13250,0.64369,0.32278,0.15927,0.07819,0.03610,0.04209,0.04069,Dia 0
Uruguai,0.37108,0.35365,0.22388,0.05139,0.72473,0.35070,0.16603,0.07842,0.03532,0.04310,0.04204,Dia 0
Croácia,0.24370,0.34435,0.26292,0.14903,0.58805,0.29211,0.13665,0.06407,0.02774,0.03633,0.03416,Dia 0
Estados Unidos,0.25401,0.27951,0.25585,0.21063,0.53352,0.29738,0.13819,0.06267,0.02755,0.03512,0.03582,Dia 0
Suíça,0.22429,0.34338,0.27130,0.16103,0.56767,0.28453,0.13009,0.05971,0.02549,0.03422,0.03216,Dia 0
Senegal,0.32072,0.36445,0.21031,0.10452,0.68517,0.30331,0.12499,0.05069,0.01984,0.03085,0.03143,Dia 0
País de Gales,0.16673,0.23525,0.28614,0.31188,0.40198,0.20194,0.08486,0.03434,0.01338,0.02096,0.02106,Dia 0
Irã,0.13659,0.21391,0.28288,0.36662,0.35050,0.16617,0.06507,0.02411,0.00927,0.01484,0.01570,Dia 0
Marrocos,0.13416,0.26274,0.34521,0.25789,0.39690,0.16498,0.06441,0.02474,0.00885,0.01589,0.01576,Dia 0
Japão,0.14812,0.23781,0.31834,0.29573,0.38593,0.14977,0.05900,0.02259,0.00790,0.01469,0.01358,Dia 0
Sérvia,0.12504,0.25806,0.33911,0.27779,0.38310,0.16118,0.06011,0.02215,0.00788,0.01427,0.01450,Dia 0
Polônia,0.13734,0.26226,0.38453,0.21587,0.39960,0.15429,0.06288,0.02246,0.00744,0.01502,0.01523,Dia 0
Coreia do Sul,0.15719,0.27528,0.42306,0.14447,0.43247,0.15162,0.05620,0.01968,0.00646,0.01322,0.01251,Dia 0
Tunísia,0.08957,0.19288,0.34824,0.36931,0.28245,0.09510,0.03379,0.01048,0.00322,0.00726,0.00764,Dia 0
Costa Rica,0.07899,0.15809,0.28068,0.48224,0.23708,0.07503,0.02395,0.00755,0.00225,0.00530,0.00501,Dia 0
Austrália,0.06147,0.15356,0.31019,0.47478,0.21503,0.06381,0.02058,0.00582,0.00159,0.00423,0.00430,Dia 0
Camarões,0.05331,0.14743,0.27976,0.51950,0.20074,0.06578,0.01881,0.00536,0.00141,0.00395,0.00410,Dia 0
Equador,0.08828,0.19582,0.34708,0.36882,0.28410,0.07850,0.02076,0.00493,0.00122,0.00371,0.00411,Dia 0
Canadá,0.04571,0.13302,0.27083,0.55044,0.17873,0.05323,0.01472,0.00395,0.00104,0.00291,0.00262,Dia 0
Catar,0.05828,0.15021,0.31400,0.47751,0.20849,0.04985,0.01112,0.00257,0.00056,0.00201,0.00187,Dia 0
Arábia Saudita,0.02606,0.08571,0.23728,0.65095,0.11177,0.02516,0.00639,0.00142,0.00028,0.00114,0.00118,Dia 0
Gana,0.01130,0.04605,0.17381,0.76884,0.05735,0.00871,0.00141,0.00015,0.00002,0.00013,0.00020,Dia 0

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 0'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia0.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.15151,0.28206,0.21604,0.13392,0.08503,0.13144,Dia 0
Bélgica,0.16368,0.29685,0.20500,0.13051,0.08162,0.12234,Dia 0
Argentina,0.18006,0.32841,0.19106,0.13298,0.07264,0.09485,Dia 0
França,0.18783,0.32966,0.18913,0.13028,0.07266,0.09044,Dia 0
Inglaterra,0.28600,0.25427,0.20726,0.11692,0.06352,0.07203,Dia 0
Espanha,0.26670,0.33067,0.18730,0.09969,0.05742,0.05822,Dia 0
Holanda,0.17776,0.37912,0.22015,0.11162,0.05751,0.05384,Dia 0
Portugal,0.21455,0.37440,0.20189,0.10193,0.05532,0.05191,Dia 0
Dinamarca,0.30965,0.33717,0.16558,0.09658,0.04884,0.04218,Dia 0
México,0.33131,0.33427,0.15994,0.09234,0.04420,0.03794,Dia 0
Alemanha,0.35631,0.32091,0.16351,0.08108,0.04209,0.03610,Dia 0
Uruguai,0.27527,0.37403,0.18467,0.08761,0.04310,0.03532,Dia 0
Croácia,0.41195,0.29594,0.15546,0.07258,0.03633,0.02774,Dia 0
Estados Unidos,0.46648,0.23614,0.15919,0.07552,0.03512,0.02755,Dia 0
Suíça,0.43233,0.28314,0.15444,0.07038,0.03422,0.02549,Dia 0
Senegal,0.31483,0.38186,0.17832,0.07430,0.03085,0.01984,Dia 0
País de Gales,0.59802,0.20004,0.11708,0.05052,0.02096,0.01338,Dia 0
Irã,0.64950,0.18433,0.10110,0.04096,0.01484,0.00927,Dia 0
Marrocos,0.60310,0.23192,0.10057,0.03967,0.01589,0.00885,Dia 0
Japão,0.61407,0.23616,0.09077,0.03641,0.01469,0.00790,Dia 0
Sérvia,0.61690,0.22192,0.10107,0.03796,0.01427,0.00788,Dia 0
Polônia,0.60040,0.24531,0.09141,0.04042,0.01502,0.00744,Dia 0
Coreia do Sul,0.56753,0.28085,0.09542,0.03652,0.01322,0.00646,Dia 0
Tunísia,0.71755,0.18735,0.06131,0.02331,0.00726,0.00322,Dia 0
Costa Rica,0.76292,0.16205,0.05108,0.01640,0.00530,0.00225,Dia 0
Austrália,0.78497,0.15122,0.04323,0.01476,0.00423,0.00159,Dia 0
Camarões,0.79926,0.13496,0.04697,0.01345,0.00395,0.00141,Dia 0
Equador,0.71590,0.20560,0.05774,0.01583,0.00371,0.00122,Dia 0
Canadá,0.82127,0.12550,0.03851,0.01077,0.00291,0.00104,Dia 0
Catar,0.79151,0.15864,0.03873,0.00855,0.00201,0.00056,Dia 0
Arábia Saudita,0.88823,0.08661,0.01877,0.00497,0.00114,0.00028,Dia 0
Gana,0.94265,0.04864,0.00730,0.00126,0.00013,0.00002,Dia 0

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 0'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia0.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.84849,0.667574,0.618594,0.617797,0.607197,Dia 0
Bélgica,0.83632,0.645052,0.619997,0.609801,0.599823,Dia 0
Argentina,0.81994,0.599471,0.611295,0.557427,0.566302,Dia 0
França,0.81217,0.594100,0.608029,0.555934,0.554506,Dia 0
Inglaterra,0.71400,0.643880,0.549170,0.536895,0.531391,Dia 0
Espanha,0.73330,0.549066,0.534809,0.537036,0.503459,Dia 0
Holanda,0.82224,0.538918,0.503182,0.499395,0.483520,Dia 0
Portugal,0.78545,0.523331,0.508843,0.512670,0.484100,Dia 0
Dinamarca,0.69035,0.511596,0.531174,0.485181,0.463415,Dia 0
México,0.66869,0.500112,0.521739,0.470770,0.461894,Dia 0
Alemanha,0.64369,0.501453,0.493432,0.490927,0.461696,Dia 0
Uruguai,0.72473,0.483904,0.473425,0.472324,0.450395,Dia 0
Croácia,0.58805,0.496743,0.467803,0.468862,0.432964,Dia 0
Estados Unidos,0.53352,0.557392,0.464692,0.453506,0.439604,Dia 0
Suíça,0.56767,0.501224,0.457210,0.458990,0.426897,Dia 0
Senegal,0.68517,0.442678,0.412087,0.405552,0.391399,Dia 0
País de Gales,0.40198,0.502363,0.420224,0.404667,0.389633,Dia 0
Irã,0.35050,0.474094,0.391587,0.370524,0.384488,Dia 0
Marrocos,0.39690,0.415671,0.390411,0.384102,0.357720,Dia 0
Japão,0.38593,0.388076,0.393937,0.382881,0.349712,Dia 0
Sérvia,0.38310,0.420726,0.372937,0.368491,0.355756,Dia 0
Polônia,0.39960,0.386111,0.407544,0.357188,0.331256,Dia 0
Coreia do Sul,0.43247,0.350591,0.370664,0.350178,0.328252,Dia 0
Tunísia,0.28245,0.336697,0.355310,0.310151,0.307252,Dia 0
Costa Rica,0.23708,0.316475,0.319206,0.315240,0.298013,Dia 0
Austrália,0.21503,0.296749,0.322520,0.282799,0.273196,Dia 0
Camarões,0.20074,0.327688,0.285953,0.284955,0.263060,Dia 0
Equador,0.28410,0.276311,0.264459,0.237476,0.247465,Dia 0
Canadá,0.17873,0.297824,0.276536,0.268342,0.263291,Dia 0
Catar,0.20849,0.239100,0.223069,0.231115,0.217899,Dia 0
Arábia Saudita,0.11177,0.225105,0.253975,0.222222,0.197183,Dia 0
Gana,0.05735,0.151874,0.161883,0.106383,0.133333,Dia 0

### **Dia 1**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 1'

S = 100000
dia = 'Dia 1'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia1.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.60002,0.24945,0.11032,0.04021,0.84947,0.56708,0.35407,0.21654,0.13184,0.08470,0.08664,Dia 1
Bélgica,0.57206,0.26202,0.12208,0.04384,0.83408,0.53754,0.33280,0.20085,0.11850,0.08235,0.08189,Dia 1
Inglaterra,0.69021,0.19965,0.09150,0.01864,0.88986,0.59056,0.32323,0.17361,0.09195,0.08166,0.08343,Dia 1
Argentina,0.53315,0.28907,0.13832,0.03946,0.82222,0.48943,0.29603,0.16533,0.09175,0.07358,0.07613,Dia 1
França,0.52055,0.29280,0.13399,0.05266,0.81335,0.48578,0.29036,0.16206,0.08920,0.07286,0.07481,Dia 1
Holanda,0.80221,0.15492,0.03864,0.00423,0.95713,0.51497,0.25967,0.12680,0.06178,0.06502,0.06892,Dia 1
Espanha,0.44334,0.29243,0.17412,0.09011,0.73577,0.40551,0.21718,0.11598,0.06014,0.05584,0.05494,Dia 1
Portugal,0.45752,0.32418,0.18208,0.03622,0.78170,0.40672,0.20487,0.10260,0.04964,0.05296,0.05301,Dia 1
Dinamarca,0.32893,0.35979,0.20872,0.10256,0.68872,0.35347,0.18350,0.08885,0.04191,0.04694,0.04757,Dia 1
México,0.30295,0.36246,0.24158,0.09301,0.66541,0.33234,0.16820,0.07947,0.03620,0.04327,0.04258,Dia 1
Alemanha,0.32758,0.31531,0.22491,0.13220,0.64289,0.32129,0.15884,0.07768,0.03514,0.04254,0.04044,Dia 1
Uruguai,0.37513,0.35424,0.22051,0.05012,0.72937,0.35359,0.16875,0.07778,0.03496,0.04282,0.04306,Dia 1
Croácia,0.24500,0.34194,0.26563,0.14743,0.58694,0.29155,0.13557,0.06282,0.02697,0.03585,0.03361,Dia 1
Estados Unidos,0.16261,0.34306,0.30263,0.19170,0.50567,0.27395,0.12683,0.05759,0.02492,0.03267,0.03248,Dia 1
Suíça,0.22208,0.34504,0.27145,0.16143,0.56712,0.28523,0.13000,0.05842,0.02431,0.03411,0.03145,Dia 1
País de Gales,0.12030,0.29245,0.32874,0.25851,0.41275,0.20057,0.08300,0.03371,0.01314,0.02057,0.02008,Dia 1
Senegal,0.05271,0.42509,0.36368,0.15852,0.47780,0.19308,0.07918,0.03219,0.01293,0.01926,0.01936,Dia 1
Marrocos,0.13689,0.26418,0.34125,0.25768,0.40107,0.16594,0.06494,0.02439,0.00855,0.01584,0.01559,Dia 1
Japão,0.15058,0.23599,0.31811,0.29532,0.38657,0.15061,0.05857,0.02230,0.00804,0.01426,0.01364,Dia 1
Polônia,0.13844,0.26224,0.38387,0.21545,0.40068,0.15430,0.06148,0.02251,0.00786,0.01465,0.01496,Dia 1
Sérvia,0.12387,0.25765,0.33568,0.28280,0.38152,0.15953,0.06041,0.02262,0.00770,0.01492,0.01408,Dia 1
Coreia do Sul,0.15548,0.27464,0.42422,0.14566,0.43012,0.15037,0.05370,0.01875,0.00593,0.01282,0.01192,Dia 1
Irã,0.02688,0.16484,0.27713,0.53115,0.19172,0.08403,0.03177,0.01218,0.00434,0.00784,0.00770,Dia 1
Tunísia,0.08690,0.19533,0.34597,0.37180,0.28223,0.09395,0.03304,0.01023,0.00312,0.00711,0.00711,Dia 1
Costa Rica,0.07850,0.15627,0.28286,0.48237,0.23477,0.07446,0.02378,0.00735,0.00234,0.00501,0.00507,Dia 1
Equador,0.13912,0.37741,0.44297,0.04050,0.51653,0.13241,0.03486,0.00899,0.00216,0.00683,0.00672,Dia 1
Camarões,0.05403,0.14786,0.28255,0.51556,0.20189,0.06842,0.02017,0.00601,0.00164,0.00437,0.00421,Dia 1
Austrália,0.06362,0.15208,0.31132,0.47298,0.21570,0.06551,0.02027,0.00583,0.00145,0.00438,0.00399,Dia 1
Canadá,0.04605,0.13186,0.27104,0.55105,0.17791,0.05310,0.01506,0.00441,0.00111,0.00330,0.00304,Dia 1
Arábia Saudita,0.02546,0.08623,0.23623,0.65208,0.11169,0.02522,0.00610,0.00135,0.00030,0.00105,0.00102,Dia 1
Catar,0.00596,0.04258,0.15471,0.79675,0.04854,0.01043,0.00248,0.00065,0.00015,0.00050,0.00041,Dia 1
Gana,0.01187,0.04694,0.17319,0.76800,0.05881,0.00906,0.00129,0.00015,0.00003,0.00012,0.00014,Dia 1

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 1'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia1.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.15053,0.28239,0.21301,0.13753,0.08470,0.13184,Dia 1
Bélgica,0.16592,0.29654,0.20474,0.13195,0.08235,0.11850,Dia 1
Inglaterra,0.11014,0.29930,0.26733,0.14962,0.08166,0.09195,Dia 1
Argentina,0.17778,0.33279,0.19340,0.13070,0.07358,0.09175,Dia 1
França,0.18665,0.32757,0.19542,0.12830,0.07286,0.08920,Dia 1
Holanda,0.04287,0.44216,0.25530,0.13287,0.06502,0.06178,Dia 1
Espanha,0.26423,0.33026,0.18833,0.10120,0.05584,0.06014,Dia 1
Portugal,0.21830,0.37498,0.20185,0.10227,0.05296,0.04964,Dia 1
Dinamarca,0.31128,0.33525,0.16997,0.09465,0.04694,0.04191,Dia 1
México,0.33459,0.33307,0.16414,0.08873,0.04327,0.03620,Dia 1
Alemanha,0.35711,0.32160,0.16245,0.08116,0.04254,0.03514,Dia 1
Uruguai,0.27063,0.37578,0.18484,0.09097,0.04282,0.03496,Dia 1
Croácia,0.41306,0.29539,0.15598,0.07275,0.03585,0.02697,Dia 1
Estados Unidos,0.49433,0.23172,0.14712,0.06924,0.03267,0.02492,Dia 1
Suíça,0.43288,0.28189,0.15523,0.07158,0.03411,0.02431,Dia 1
País de Gales,0.58725,0.21218,0.11757,0.04929,0.02057,0.01314,Dia 1
Senegal,0.52220,0.28472,0.11390,0.04699,0.01926,0.01293,Dia 1
Marrocos,0.59893,0.23513,0.10100,0.04055,0.01584,0.00855,Dia 1
Japão,0.61343,0.23596,0.09204,0.03627,0.01426,0.00804,Dia 1
Polônia,0.59932,0.24638,0.09282,0.03897,0.01465,0.00786,Dia 1
Sérvia,0.61848,0.22199,0.09912,0.03779,0.01492,0.00770,Dia 1
Coreia do Sul,0.56988,0.27975,0.09667,0.03495,0.01282,0.00593,Dia 1
Irã,0.80828,0.10769,0.05226,0.01959,0.00784,0.00434,Dia 1
Tunísia,0.71777,0.18828,0.06091,0.02281,0.00711,0.00312,Dia 1
Costa Rica,0.76523,0.16031,0.05068,0.01643,0.00501,0.00234,Dia 1
Equador,0.48347,0.38412,0.09755,0.02587,0.00683,0.00216,Dia 1
Camarões,0.79811,0.13347,0.04825,0.01416,0.00437,0.00164,Dia 1
Austrália,0.78430,0.15019,0.04524,0.01444,0.00438,0.00145,Dia 1
Canadá,0.82209,0.12481,0.03804,0.01065,0.00330,0.00111,Dia 1
Arábia Saudita,0.88831,0.08647,0.01912,0.00475,0.00105,0.00030,Dia 1
Catar,0.95146,0.03811,0.00795,0.00183,0.00050,0.00015,Dia 1
Gana,0.94119,0.04975,0.00777,0.00114,0.00012,0.00003,Dia 1

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 1'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia1.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.84947,0.667569,0.624374,0.611574,0.608848,Dia 1
Bélgica,0.83408,0.644471,0.619117,0.603516,0.589993,Dia 1
Inglaterra,0.88986,0.663655,0.547328,0.537110,0.529635,Dia 1
Argentina,0.82222,0.595254,0.604846,0.558491,0.554951,Dia 1
França,0.81335,0.597258,0.597719,0.558135,0.550413,Dia 1
Holanda,0.95713,0.538036,0.504243,0.488312,0.487224,Dia 1
Espanha,0.73577,0.551137,0.535572,0.534027,0.518538,Dia 1
Portugal,0.78170,0.520302,0.503713,0.500805,0.483821,Dia 1
Dinamarca,0.68872,0.513227,0.519139,0.484196,0.471694,Dia 1
México,0.66541,0.499451,0.506108,0.472473,0.455518,Dia 1
Alemanha,0.64289,0.499759,0.494382,0.489046,0.452369,Dia 1
Uruguai,0.72937,0.484788,0.477248,0.460919,0.449473,Dia 1
Croácia,0.58694,0.496729,0.464997,0.463377,0.429322,Dia 1
Estados Unidos,0.50567,0.541756,0.462968,0.454072,0.432714,Dia 1
Suíça,0.56712,0.502945,0.455773,0.449385,0.416125,Dia 1
País de Gales,0.41275,0.485936,0.413821,0.406145,0.389795,Dia 1
Senegal,0.47780,0.404102,0.410089,0.406542,0.401678,Dia 1
Marrocos,0.40107,0.413743,0.391346,0.375577,0.350554,Dia 1
Japão,0.38657,0.389606,0.388885,0.380741,0.360538,Dia 1
Polônia,0.40068,0.385095,0.398445,0.366135,0.349178,Dia 1
Sérvia,0.38152,0.418143,0.378675,0.374441,0.340407,Dia 1
Coreia do Sul,0.43012,0.349600,0.357119,0.349162,0.316267,Dia 1
Irã,0.19172,0.438295,0.378079,0.383381,0.356322,Dia 1
Tunísia,0.28223,0.332885,0.351676,0.309625,0.304985,Dia 1
Costa Rica,0.23477,0.317161,0.319366,0.309083,0.318367,Dia 1
Equador,0.51653,0.256345,0.263273,0.257889,0.240267,Dia 1
Camarões,0.20189,0.338897,0.294797,0.297967,0.272879,Dia 1
Austrália,0.21570,0.303709,0.309418,0.287617,0.248714,Dia 1
Canadá,0.17791,0.298466,0.283616,0.292829,0.251701,Dia 1
Arábia Saudita,0.11169,0.225804,0.241872,0.221311,0.222222,Dia 1
Catar,0.04854,0.214874,0.237776,0.262097,0.230769,Dia 1
Gana,0.05881,0.154055,0.142384,0.116279,0.200000,Dia 1

### **Dia 2**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 2'

S = 100000
dia = 'Dia 2'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia2.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.59059,0.25285,0.11387,0.04269,0.84344,0.56389,0.34924,0.21726,0.13014,0.08712,0.08206,Dia 2
Bélgica,0.56794,0.26305,0.12470,0.04431,0.83099,0.53685,0.33209,0.20073,0.11862,0.08211,0.08203,Dia 2
França,0.70721,0.20723,0.07683,0.00873,0.91444,0.59837,0.35538,0.19786,0.11186,0.08600,0.09235,Dia 2
Inglaterra,0.69143,0.19782,0.09201,0.01874,0.88925,0.58808,0.32642,0.17584,0.09546,0.08038,0.08506,Dia 2
Holanda,0.80240,0.15460,0.03845,0.00455,0.95700,0.52089,0.28081,0.13895,0.06659,0.07236,0.07259,Dia 2
Espanha,0.43260,0.29426,0.18244,0.09070,0.72686,0.39964,0.21466,0.11679,0.06089,0.05590,0.05427,Dia 2
Argentina,0.26589,0.19352,0.27202,0.26857,0.45941,0.27392,0.16388,0.09176,0.05082,0.04094,0.04270,Dia 2
Portugal,0.44797,0.32831,0.18690,0.03682,0.77628,0.40416,0.20571,0.10362,0.05031,0.05331,0.05255,Dia 2
Dinamarca,0.20494,0.41552,0.26527,0.11427,0.62046,0.35885,0.18843,0.09093,0.04234,0.04859,0.04863,Dia 2
Alemanha,0.33683,0.30896,0.22221,0.13200,0.64579,0.32095,0.15964,0.07883,0.03641,0.04242,0.04051,Dia 2
Uruguai,0.38169,0.35052,0.21811,0.04968,0.73221,0.35505,0.16640,0.07896,0.03538,0.04358,0.04285,Dia 2
México,0.31906,0.28426,0.23481,0.16187,0.60332,0.29936,0.15262,0.07280,0.03398,0.03882,0.03960,Dia 2
Croácia,0.24904,0.34512,0.26212,0.14372,0.59416,0.29649,0.14045,0.06596,0.02874,0.03722,0.03436,Dia 2
Suíça,0.22867,0.34539,0.26648,0.15946,0.57406,0.29037,0.13219,0.06105,0.02647,0.03458,0.03211,Dia 2
Estados Unidos,0.16283,0.34422,0.30097,0.19198,0.50705,0.27156,0.13263,0.06003,0.02640,0.03363,0.03504,Dia 2
Senegal,0.05268,0.42513,0.36331,0.15888,0.47781,0.19261,0.08138,0.03350,0.01355,0.01995,0.02019,Dia 2
País de Gales,0.11952,0.29192,0.33038,0.25818,0.41144,0.19716,0.08534,0.03398,0.01302,0.02096,0.02128,Dia 2
Marrocos,0.13845,0.26326,0.34593,0.25236,0.40171,0.16895,0.06617,0.02593,0.00956,0.01637,0.01608,Dia 2
Polônia,0.19213,0.27171,0.26120,0.27496,0.46384,0.17527,0.07030,0.02538,0.00870,0.01668,0.01735,Dia 2
Japão,0.15348,0.23858,0.31827,0.28967,0.39206,0.15074,0.06021,0.02326,0.00816,0.01510,0.01554,Dia 2
Sérvia,0.12516,0.25334,0.33646,0.28504,0.37850,0.15787,0.06048,0.02291,0.00796,0.01495,0.01454,Dia 2
Coreia do Sul,0.15970,0.27556,0.42624,0.13850,0.43526,0.15373,0.05315,0.01807,0.00603,0.01204,0.01248,Dia 2
Irã,0.02622,0.16604,0.27664,0.53110,0.19226,0.08397,0.03494,0.01278,0.00464,0.00814,0.00857,Dia 2
Tunísia,0.07540,0.25141,0.38452,0.28867,0.32681,0.13250,0.04641,0.01468,0.00412,0.01056,0.01029,Dia 2
Equador,0.13852,0.37758,0.44281,0.04109,0.51610,0.13493,0.03632,0.00939,0.00235,0.00704,0.00701,Dia 2
Costa Rica,0.07709,0.15820,0.27708,0.48763,0.23529,0.07387,0.02401,0.00785,0.00227,0.00558,0.00512,Dia 2
Camarões,0.05558,0.14842,0.28319,0.51281,0.20400,0.06634,0.01939,0.00556,0.00156,0.00400,0.00401,Dia 2
Austrália,0.01245,0.12584,0.27338,0.58833,0.13829,0.05197,0.01611,0.00455,0.00125,0.00330,0.00320,Dia 2
Arábia Saudita,0.22292,0.25051,0.23197,0.29460,0.47343,0.10976,0.02641,0.00593,0.00117,0.00476,0.00417,Dia 2
Canadá,0.04457,0.12857,0.26725,0.55961,0.17314,0.05251,0.01479,0.00410,0.00113,0.00297,0.00281,Dia 2
Catar,0.00640,0.04269,0.15543,0.79548,0.04909,0.01080,0.00262,0.00056,0.00012,0.00044,0.00043,Dia 2
Gana,0.01064,0.04561,0.16875,0.77500,0.05625,0.00859,0.00142,0.00020,0.00000,0.00020,0.00022,Dia 2

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 2'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia2.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.15656,0.27955,0.21465,0.13198,0.08712,0.13014,Dia 2
Bélgica,0.16901,0.29414,0.20476,0.13136,0.08211,0.11862,Dia 2
França,0.08556,0.31607,0.24299,0.15752,0.08600,0.11186,Dia 2
Inglaterra,0.11075,0.30117,0.26166,0.15058,0.08038,0.09546,Dia 2
Holanda,0.04300,0.43611,0.24008,0.14186,0.07236,0.06659,Dia 2
Espanha,0.27314,0.32722,0.18498,0.09787,0.05590,0.06089,Dia 2
Argentina,0.54059,0.18549,0.11004,0.07212,0.04094,0.05082,Dia 2
Portugal,0.22372,0.37212,0.19845,0.10209,0.05331,0.05031,Dia 2
Dinamarca,0.37954,0.26161,0.17042,0.09750,0.04859,0.04234,Dia 2
Alemanha,0.35421,0.32484,0.16131,0.08081,0.04242,0.03641,Dia 2
Uruguai,0.26779,0.37716,0.18865,0.08744,0.04358,0.03538,Dia 2
México,0.39668,0.30396,0.14674,0.07982,0.03882,0.03398,Dia 2
Croácia,0.40584,0.29767,0.15604,0.07449,0.03722,0.02874,Dia 2
Suíça,0.42594,0.28369,0.15818,0.07114,0.03458,0.02647,Dia 2
Estados Unidos,0.49295,0.23549,0.13893,0.07260,0.03363,0.02640,Dia 2
Senegal,0.52219,0.28520,0.11123,0.04788,0.01995,0.01355,Dia 2
País de Gales,0.58856,0.21428,0.11182,0.05136,0.02096,0.01302,Dia 2
Marrocos,0.59829,0.23276,0.10278,0.04024,0.01637,0.00956,Dia 2
Polônia,0.53616,0.28857,0.10497,0.04492,0.01668,0.00870,Dia 2
Japão,0.60794,0.24132,0.09053,0.03695,0.01510,0.00816,Dia 2
Sérvia,0.62150,0.22063,0.09739,0.03757,0.01495,0.00796,Dia 2
Coreia do Sul,0.56474,0.28153,0.10058,0.03508,0.01204,0.00603,Dia 2
Irã,0.80774,0.10829,0.04903,0.02216,0.00814,0.00464,Dia 2
Tunísia,0.67319,0.19431,0.08609,0.03173,0.01056,0.00412,Dia 2
Equador,0.48390,0.38117,0.09861,0.02693,0.00704,0.00235,Dia 2
Costa Rica,0.76471,0.16142,0.04986,0.01616,0.00558,0.00227,Dia 2
Camarões,0.79600,0.13766,0.04695,0.01383,0.00400,0.00156,Dia 2
Austrália,0.86171,0.08632,0.03586,0.01156,0.00330,0.00125,Dia 2
Arábia Saudita,0.52657,0.36367,0.08335,0.02048,0.00476,0.00117,Dia 2
Canadá,0.82686,0.12063,0.03772,0.01069,0.00297,0.00113,Dia 2
Catar,0.95091,0.03829,0.00818,0.00206,0.00044,0.00012,Dia 2
Gana,0.94375,0.04766,0.00717,0.00122,0.00020,0.00000,Dia 2

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 2'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia2.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.84344,0.668560,0.619341,0.622094,0.599006,Dia 2
Bélgica,0.83099,0.646037,0.618590,0.604445,0.590943,Dia 2
França,0.91444,0.654357,0.593913,0.556756,0.565349,Dia 2
Inglaterra,0.88925,0.661321,0.555061,0.538692,0.542880,Dia 2
Holanda,0.95700,0.544295,0.539097,0.494819,0.479237,Dia 2
Espanha,0.72686,0.549817,0.537133,0.544070,0.521363,Dia 2
Argentina,0.45941,0.596243,0.598277,0.559922,0.553836,Dia 2
Portugal,0.77628,0.520637,0.508982,0.503719,0.485524,Dia 2
Dinamarca,0.62046,0.578361,0.525094,0.482566,0.465633,Dia 2
Alemanha,0.64579,0.496988,0.497398,0.493799,0.461880,Dia 2
Uruguai,0.73221,0.484902,0.468666,0.474519,0.448075,Dia 2
México,0.60332,0.496188,0.509821,0.477002,0.466758,Dia 2
Croácia,0.59416,0.499007,0.473709,0.469633,0.435719,Dia 2
Suíça,0.57406,0.505818,0.455247,0.461835,0.433579,Dia 2
Estados Unidos,0.50705,0.535568,0.488400,0.452613,0.439780,Dia 2
Senegal,0.47781,0.403110,0.422512,0.411649,0.404478,Dia 2
País de Gales,0.41144,0.479195,0.432846,0.398172,0.383167,Dia 2
Marrocos,0.40171,0.420577,0.391654,0.391869,0.368685,Dia 2
Polônia,0.46384,0.377867,0.401095,0.361024,0.342790,Dia 2
Japão,0.39206,0.384482,0.399429,0.386315,0.350817,Dia 2
Sérvia,0.37850,0.417094,0.383100,0.378803,0.347447,Dia 2
Coreia do Sul,0.43526,0.353191,0.345736,0.339981,0.333702,Dia 2
Irã,0.19226,0.436752,0.416101,0.365770,0.363067,Dia 2
Tunísia,0.32681,0.405434,0.350264,0.316311,0.280654,Dia 2
Equador,0.51610,0.261442,0.269177,0.258535,0.250266,Dia 2
Costa Rica,0.23529,0.313953,0.325030,0.326947,0.289172,Dia 2
Camarões,0.20400,0.325196,0.292282,0.286746,0.280576,Dia 2
Austrália,0.13829,0.375804,0.309987,0.282433,0.274725,Dia 2
Arábia Saudita,0.47343,0.231840,0.240616,0.224536,0.197302,Dia 2
Canadá,0.17314,0.303281,0.281661,0.277214,0.275610,Dia 2
Catar,0.04909,0.220004,0.242593,0.213740,0.214286,Dia 2
Gana,0.05625,0.152711,0.165308,0.140845,0.000000,Dia 2

### **Dia 3**

In [ ]:
# Simulando a copa 100000 vezes para 'Dia 3'

S = 100000
dia = 'Dia 3'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia3.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Bélgica,0.68742,0.20330,0.09708,0.01220,0.89072,0.57996,0.36018,0.21643,0.12961,0.08682,0.08844,Dia 3
Brasil,0.59207,0.24942,0.11530,0.04321,0.84149,0.56064,0.34388,0.21178,0.12645,0.08533,0.08226,Dia 3
França,0.70652,0.20772,0.07677,0.00899,0.91424,0.59961,0.35581,0.19869,0.11156,0.08713,0.09246,Dia 3
Inglaterra,0.68809,0.20199,0.09129,0.01863,0.89008,0.58841,0.32764,0.17798,0.09709,0.08089,0.08549,Dia 3
Espanha,0.69806,0.20128,0.09560,0.00506,0.89934,0.51155,0.27465,0.14920,0.07573,0.07347,0.06794,Dia 3
Holanda,0.80470,0.15340,0.03759,0.00431,0.95810,0.52022,0.27891,0.13777,0.06675,0.07102,0.07189,Dia 3
Argentina,0.26569,0.19572,0.27181,0.26678,0.46141,0.27357,0.16513,0.09262,0.05088,0.04174,0.04225,Dia 3
Portugal,0.44982,0.32916,0.18495,0.03607,0.77898,0.40645,0.20148,0.10190,0.04977,0.05213,0.05214,Dia 3
Dinamarca,0.20791,0.41606,0.26428,0.11175,0.62397,0.36145,0.18754,0.09123,0.04189,0.04934,0.04828,Dia 3
Uruguai,0.38031,0.35182,0.21902,0.04885,0.73213,0.35584,0.16793,0.07914,0.03481,0.04433,0.04261,Dia 3
México,0.32142,0.27980,0.23595,0.16283,0.60122,0.29950,0.15264,0.07107,0.03168,0.03939,0.03982,Dia 3
Estados Unidos,0.16691,0.34399,0.29827,0.19083,0.51090,0.27352,0.13400,0.06087,0.02665,0.03422,0.03438,Dia 3
Croácia,0.17480,0.37332,0.30052,0.15136,0.54812,0.26753,0.12552,0.05905,0.02521,0.03384,0.03090,Dia 3
Suíça,0.22802,0.34941,0.26337,0.15920,0.57743,0.28980,0.13066,0.05847,0.02494,0.03353,0.03300,Dia 3
Alemanha,0.03653,0.26333,0.46825,0.23189,0.29986,0.13480,0.06890,0.03335,0.01629,0.01706,0.01806,Dia 3
Japão,0.25770,0.45986,0.25856,0.02388,0.71756,0.26976,0.10640,0.04147,0.01488,0.02659,0.02601,Dia 3
Senegal,0.05168,0.42673,0.36467,0.15692,0.47841,0.19419,0.08166,0.03352,0.01390,0.01962,0.02072,Dia 3
País de Gales,0.11890,0.28921,0.33235,0.25954,0.40811,0.19544,0.08616,0.03497,0.01303,0.02194,0.02133,Dia 3
Marrocos,0.12070,0.30463,0.35589,0.21878,0.42533,0.17398,0.06922,0.02717,0.00964,0.01753,0.01616,Dia 3
Polônia,0.19189,0.27091,0.26232,0.27488,0.46280,0.17455,0.06829,0.02395,0.00865,0.01530,0.01677,Dia 3
Sérvia,0.12419,0.25125,0.33655,0.28801,0.37544,0.15863,0.05910,0.02261,0.00811,0.01450,0.01370,Dia 3
Coreia do Sul,0.15903,0.27474,0.42579,0.14044,0.43377,0.15302,0.05282,0.01793,0.00596,0.01197,0.01211,Dia 3
Irã,0.02610,0.16481,0.27809,0.53100,0.19091,0.08458,0.03540,0.01351,0.00467,0.00884,0.00849,Dia 3
Tunísia,0.07330,0.25208,0.38568,0.28894,0.32538,0.13197,0.04621,0.01398,0.00426,0.00972,0.01082,Dia 3
Equador,0.13791,0.37679,0.44391,0.04139,0.51470,0.13282,0.03692,0.00909,0.00215,0.00694,0.00732,Dia 3
Camarões,0.05572,0.14992,0.28478,0.50958,0.20564,0.06704,0.01912,0.00579,0.00153,0.00426,0.00433,Dia 3
Arábia Saudita,0.22100,0.25357,0.22992,0.29551,0.47457,0.10869,0.02561,0.00549,0.00122,0.00427,0.00464,Dia 3
Austrália,0.01227,0.12414,0.27327,0.59032,0.13641,0.05066,0.01557,0.00463,0.00120,0.00343,0.00316,Dia 3
Canadá,0.01708,0.11875,0.24651,0.61766,0.13583,0.03871,0.01084,0.00317,0.00068,0.00249,0.00212,Dia 3
Costa Rica,0.00771,0.07553,0.17759,0.73917,0.08324,0.02371,0.00802,0.00225,0.00061,0.00164,0.00185,Dia 3
Catar,0.00571,0.04308,0.15383,0.79738,0.04879,0.01082,0.00251,0.00069,0.00017,0.00052,0.00044,Dia 3
Gana,0.01084,0.04428,0.17024,0.77464,0.05512,0.00858,0.00128,0.00023,0.00003,0.00020,0.00011,Dia 3

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 3'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia3.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Bélgica,0.10928,0.31076,0.21978,0.14375,0.08682,0.12961,Dia 3
Brasil,0.15851,0.28085,0.21676,0.13210,0.08533,0.12645,Dia 3
França,0.08576,0.31463,0.24380,0.15712,0.08713,0.11156,Dia 3
Inglaterra,0.10992,0.30167,0.26077,0.14966,0.08089,0.09709,Dia 3
Espanha,0.10066,0.38779,0.23690,0.12545,0.07347,0.07573,Dia 3
Holanda,0.04190,0.43788,0.24131,0.14114,0.07102,0.06675,Dia 3
Argentina,0.53859,0.18784,0.10844,0.07251,0.04174,0.05088,Dia 3
Portugal,0.22102,0.37253,0.20497,0.09958,0.05213,0.04977,Dia 3
Dinamarca,0.37603,0.26252,0.17391,0.09631,0.04934,0.04189,Dia 3
Uruguai,0.26787,0.37629,0.18791,0.08879,0.04433,0.03481,Dia 3
México,0.39878,0.30172,0.14686,0.08157,0.03939,0.03168,Dia 3
Estados Unidos,0.48910,0.23738,0.13952,0.07313,0.03422,0.02665,Dia 3
Croácia,0.45188,0.28059,0.14201,0.06647,0.03384,0.02521,Dia 3
Suíça,0.42257,0.28763,0.15914,0.07219,0.03353,0.02494,Dia 3
Alemanha,0.70014,0.16506,0.06590,0.03555,0.01706,0.01629,Dia 3
Japão,0.28244,0.44780,0.16336,0.06493,0.02659,0.01488,Dia 3
Senegal,0.52159,0.28422,0.11253,0.04814,0.01962,0.01390,Dia 3
País de Gales,0.59189,0.21267,0.10928,0.05119,0.02194,0.01303,Dia 3
Marrocos,0.57467,0.25135,0.10476,0.04205,0.01753,0.00964,Dia 3
Polônia,0.53720,0.28825,0.10626,0.04434,0.01530,0.00865,Dia 3
Sérvia,0.62456,0.21681,0.09953,0.03649,0.01450,0.00811,Dia 3
Coreia do Sul,0.56623,0.28075,0.10020,0.03489,0.01197,0.00596,Dia 3
Irã,0.80909,0.10633,0.04918,0.02189,0.00884,0.00467,Dia 3
Tunísia,0.67462,0.19341,0.08576,0.03223,0.00972,0.00426,Dia 3
Equador,0.48530,0.38188,0.09590,0.02783,0.00694,0.00215,Dia 3
Camarões,0.79436,0.13860,0.04792,0.01333,0.00426,0.00153,Dia 3
Arábia Saudita,0.52543,0.36588,0.08308,0.02012,0.00427,0.00122,Dia 3
Austrália,0.86359,0.08575,0.03509,0.01094,0.00343,0.00120,Dia 3
Canadá,0.86417,0.09712,0.02787,0.00767,0.00249,0.00068,Dia 3
Costa Rica,0.91676,0.05953,0.01569,0.00577,0.00164,0.00061,Dia 3
Catar,0.95121,0.03797,0.00831,0.00182,0.00052,0.00017,Dia 3
Gana,0.94488,0.04654,0.00730,0.00105,0.00020,0.00003,Dia 3

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 3'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia3.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Bélgica,0.89072,0.651114,0.621043,0.600894,0.598854,Dia 3
Brasil,0.84149,0.666247,0.613370,0.615854,0.597082,Dia 3
França,0.91424,0.655856,0.593402,0.558416,0.561478,Dia 3
Inglaterra,0.89008,0.661075,0.556823,0.543218,0.545511,Dia 3
Espanha,0.89934,0.568806,0.536898,0.543237,0.507574,Dia 3
Holanda,0.95810,0.542970,0.536139,0.493959,0.484503,Dia 3
Argentina,0.46141,0.592900,0.603612,0.560891,0.549341,Dia 3
Portugal,0.77898,0.521772,0.495707,0.505757,0.488420,Dia 3
Dinamarca,0.62397,0.579275,0.518855,0.486456,0.459169,Dia 3
Uruguai,0.73213,0.486034,0.471926,0.471268,0.439853,Dia 3
México,0.60122,0.498154,0.509649,0.465605,0.445758,Dia 3
Estados Unidos,0.51090,0.535369,0.489909,0.454254,0.437818,Dia 3
Croácia,0.54812,0.488087,0.469181,0.470443,0.426926,Dia 3
Suíça,0.57743,0.501879,0.450863,0.447497,0.426544,Dia 3
Alemanha,0.29986,0.449543,0.511128,0.484035,0.488456,Dia 3
Japão,0.71756,0.375941,0.394425,0.389756,0.358814,Dia 3
Senegal,0.47841,0.405907,0.420516,0.410482,0.414678,Dia 3
País de Gales,0.40811,0.478890,0.440851,0.405873,0.372605,Dia 3
Marrocos,0.42533,0.409047,0.397862,0.392517,0.354803,Dia 3
Polônia,0.46280,0.377161,0.391235,0.350710,0.361169,Dia 3
Sérvia,0.37544,0.422518,0.372565,0.382572,0.358691,Dia 3
Coreia do Sul,0.43377,0.352768,0.345184,0.339455,0.332404,Dia 3
Irã,0.19091,0.443036,0.418539,0.381638,0.345670,Dia 3
Tunísia,0.32538,0.405587,0.350155,0.302532,0.304721,Dia 3
Equador,0.51470,0.258053,0.277970,0.246208,0.236524,Dia 3
Camarões,0.20564,0.326007,0.285203,0.302824,0.264249,Dia 3
Arábia Saudita,0.47457,0.229028,0.235624,0.214369,0.222222,Dia 3
Austrália,0.13641,0.371380,0.307343,0.297367,0.259179,Dia 3
Canadá,0.13583,0.284989,0.280031,0.292435,0.214511,Dia 3
Costa Rica,0.08324,0.284839,0.338254,0.280549,0.271111,Dia 3
Catar,0.04879,0.221767,0.231978,0.274900,0.246377,Dia 3
Gana,0.05512,0.155660,0.149184,0.179688,0.130435,Dia 3

### **Dia 4**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 4'

S = 100000
dia = 'Dia 4'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia4.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.73393,0.22094,0.04029,0.00484,0.95487,0.64088,0.39879,0.24833,0.15075,0.09758,0.09422,Dia 4
Bélgica,0.68673,0.20419,0.09727,0.01181,0.89092,0.58274,0.35762,0.21484,0.12691,0.08793,0.08898,Dia 4
França,0.70854,0.20765,0.07537,0.00844,0.91619,0.60244,0.35934,0.19915,0.10983,0.08932,0.09269,Dia 4
Inglaterra,0.69067,0.19809,0.09212,0.01912,0.88876,0.58739,0.32498,0.17113,0.08992,0.08121,0.08633,Dia 4
Espanha,0.69727,0.20075,0.09648,0.00550,0.89802,0.50801,0.26073,0.14416,0.07341,0.07075,0.06372,Dia 4
Holanda,0.80307,0.15442,0.03821,0.00430,0.95749,0.51713,0.27981,0.13548,0.06497,0.07051,0.07338,Dia 4
Argentina,0.26671,0.19586,0.27229,0.26514,0.46257,0.27204,0.16407,0.09124,0.05023,0.04101,0.04333,Dia 4
Portugal,0.54691,0.27421,0.17007,0.00881,0.82112,0.41832,0.20680,0.10339,0.04939,0.05400,0.05405,Dia 4
Dinamarca,0.20355,0.41258,0.26918,0.11469,0.61613,0.35807,0.18669,0.08836,0.04156,0.04680,0.04805,Dia 4
México,0.32038,0.28139,0.23393,0.16430,0.60177,0.29884,0.15081,0.07027,0.03164,0.03863,0.03997,Dia 4
Suíça,0.23464,0.49948,0.23604,0.02984,0.73412,0.36645,0.16389,0.07468,0.03154,0.04314,0.03959,Dia 4
Uruguai,0.28843,0.38131,0.27333,0.05693,0.66974,0.30095,0.14123,0.06751,0.02966,0.03785,0.03492,Dia 4
Estados Unidos,0.16206,0.34544,0.29996,0.19254,0.50750,0.27480,0.13532,0.06095,0.02739,0.03356,0.03457,Dia 4
Croácia,0.17717,0.37113,0.30061,0.15109,0.54830,0.26931,0.12229,0.05759,0.02482,0.03277,0.02963,Dia 4
Alemanha,0.03792,0.26212,0.46567,0.23429,0.30004,0.13539,0.06861,0.03362,0.01561,0.01801,0.01716,Dia 4
Japão,0.25658,0.46318,0.25681,0.02343,0.71976,0.26772,0.10318,0.03943,0.01399,0.02544,0.02452,Dia 4
Senegal,0.05134,0.42434,0.36606,0.15826,0.47568,0.19360,0.08170,0.03336,0.01293,0.02043,0.02097,Dia 4
País de Gales,0.11966,0.29269,0.33230,0.25535,0.41235,0.19920,0.08699,0.03337,0.01271,0.02066,0.02194,Dia 4
Marrocos,0.11976,0.30596,0.35567,0.21861,0.42572,0.17498,0.06577,0.02532,0.00915,0.01617,0.01551,Dia 4
Polônia,0.19514,0.26996,0.26239,0.27251,0.46510,0.17444,0.06966,0.02429,0.00856,0.01573,0.01707,Dia 4
Coreia do Sul,0.15949,0.30601,0.41530,0.11920,0.46550,0.14974,0.05210,0.01867,0.00597,0.01270,0.01202,Dia 4
Irã,0.02761,0.16378,0.27562,0.53299,0.19139,0.08279,0.03453,0.01185,0.00429,0.00756,0.00904,Dia 4
Sérvia,0.02102,0.21084,0.40598,0.36216,0.23186,0.09295,0.03338,0.01265,0.00426,0.00839,0.00742,Dia 4
Tunísia,0.07593,0.25351,0.38408,0.28648,0.32944,0.13533,0.04603,0.01380,0.00416,0.00964,0.01033,Dia 4
Equador,0.13980,0.37665,0.44209,0.04146,0.51645,0.13489,0.03640,0.00899,0.00207,0.00692,0.00711,Dia 4
Austrália,0.01198,0.12626,0.27137,0.59039,0.13824,0.05166,0.01614,0.00468,0.00132,0.00336,0.00319,Dia 4
Arábia Saudita,0.21777,0.25279,0.23139,0.29805,0.47056,0.10718,0.02504,0.00498,0.00093,0.00405,0.00451,Dia 4
Canadá,0.01634,0.11872,0.24645,0.61849,0.13506,0.03873,0.00990,0.00295,0.00063,0.00232,0.00209,Dia 4
Camarões,0.01041,0.06874,0.31769,0.60316,0.07915,0.02506,0.00728,0.00199,0.00060,0.00139,0.00160,Dia 4
Costa Rica,0.00823,0.07395,0.18104,0.73678,0.08218,0.02312,0.00757,0.00225,0.00059,0.00166,0.00161,Dia 4
Catar,0.00579,0.04459,0.15364,0.79598,0.05038,0.01020,0.00249,0.00057,0.00019,0.00038,0.00037,Dia 4
Gana,0.00517,0.03847,0.14130,0.81506,0.04364,0.00565,0.00086,0.00015,0.00002,0.00013,0.00011,Dia 4

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 4'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia4.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.04513,0.31399,0.24209,0.15046,0.09758,0.15075,Dia 4
Bélgica,0.10908,0.30818,0.22512,0.14278,0.08793,0.12691,Dia 4
França,0.08381,0.31375,0.24310,0.16019,0.08932,0.10983,Dia 4
Inglaterra,0.11124,0.30137,0.26241,0.15385,0.08121,0.08992,Dia 4
Espanha,0.10198,0.39001,0.24728,0.11657,0.07075,0.07341,Dia 4
Holanda,0.04251,0.44036,0.23732,0.14433,0.07051,0.06497,Dia 4
Argentina,0.53743,0.19053,0.10797,0.07283,0.04101,0.05023,Dia 4
Portugal,0.17888,0.40280,0.21152,0.10341,0.05400,0.04939,Dia 4
Dinamarca,0.38387,0.25806,0.17138,0.09833,0.04680,0.04156,Dia 4
México,0.39823,0.30293,0.14803,0.08054,0.03863,0.03164,Dia 4
Suíça,0.26588,0.36767,0.20256,0.08921,0.04314,0.03154,Dia 4
Uruguai,0.33026,0.36879,0.15972,0.07372,0.03785,0.02966,Dia 4
Estados Unidos,0.49250,0.23270,0.13948,0.07437,0.03356,0.02739,Dia 4
Croácia,0.45170,0.27899,0.14702,0.06470,0.03277,0.02482,Dia 4
Alemanha,0.69996,0.16465,0.06678,0.03499,0.01801,0.01561,Dia 4
Japão,0.28024,0.45204,0.16454,0.06375,0.02544,0.01399,Dia 4
Senegal,0.52432,0.28208,0.11190,0.04834,0.02043,0.01293,Dia 4
País de Gales,0.58765,0.21315,0.11221,0.05362,0.02066,0.01271,Dia 4
Marrocos,0.57428,0.25074,0.10921,0.04045,0.01617,0.00915,Dia 4
Polônia,0.53490,0.29066,0.10478,0.04537,0.01573,0.00856,Dia 4
Coreia do Sul,0.53450,0.31576,0.09764,0.03343,0.01270,0.00597,Dia 4
Irã,0.80861,0.10860,0.04826,0.02268,0.00756,0.00429,Dia 4
Sérvia,0.76814,0.13891,0.05957,0.02073,0.00839,0.00426,Dia 4
Tunísia,0.67056,0.19411,0.08930,0.03223,0.00964,0.00416,Dia 4
Equador,0.48355,0.38156,0.09849,0.02741,0.00692,0.00207,Dia 4
Austrália,0.86176,0.08658,0.03552,0.01146,0.00336,0.00132,Dia 4
Arábia Saudita,0.52944,0.36338,0.08214,0.02006,0.00405,0.00093,Dia 4
Canadá,0.86494,0.09633,0.02883,0.00695,0.00232,0.00063,Dia 4
Camarões,0.92085,0.05409,0.01778,0.00529,0.00139,0.00060,Dia 4
Costa Rica,0.91782,0.05906,0.01555,0.00532,0.00166,0.00059,Dia 4
Catar,0.94962,0.04018,0.00771,0.00192,0.00038,0.00019,Dia 4
Gana,0.95636,0.03799,0.00479,0.00071,0.00013,0.00002,Dia 4

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 4'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia4.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.95487,0.671170,0.622254,0.622709,0.607055,Dia 4
Bélgica,0.89092,0.654088,0.613687,0.600749,0.590719,Dia 4
França,0.91619,0.657549,0.596474,0.554210,0.551494,Dia 4
Inglaterra,0.88876,0.660910,0.553261,0.526586,0.525448,Dia 4
Espanha,0.89802,0.565700,0.513238,0.552909,0.509226,Dia 4
Holanda,0.95749,0.540089,0.541083,0.484186,0.479554,Dia 4
Argentina,0.46257,0.588106,0.603110,0.556104,0.550526,Dia 4
Portugal,0.82112,0.509451,0.494358,0.499952,0.477706,Dia 4
Dinamarca,0.61613,0.581160,0.521379,0.473298,0.470349,Dia 4
México,0.60177,0.496602,0.504651,0.465951,0.450263,Dia 4
Suíça,0.73412,0.499169,0.447237,0.455671,0.422335,Dia 4
Uruguai,0.66974,0.449353,0.469281,0.478015,0.439342,Dia 4
Estados Unidos,0.50750,0.541478,0.492431,0.450414,0.449385,Dia 4
Croácia,0.54830,0.491173,0.454086,0.470930,0.430978,Dia 4
Alemanha,0.30004,0.451240,0.506758,0.490016,0.464307,Dia 4
Japão,0.71976,0.371957,0.385403,0.382148,0.354806,Dia 4
Senegal,0.47568,0.406996,0.422004,0.408323,0.387590,Dia 4
País de Gales,0.41235,0.483085,0.436697,0.383607,0.380881,Dia 4
Marrocos,0.42572,0.411021,0.375872,0.384978,0.361374,Dia 4
Polônia,0.46510,0.375059,0.399335,0.348694,0.352408,Dia 4
Coreia do Sul,0.46550,0.321676,0.347936,0.358349,0.319764,Dia 4
Irã,0.19139,0.432572,0.417079,0.343180,0.362025,Dia 4
Sérvia,0.23186,0.400888,0.359118,0.378969,0.336759,Dia 4
Tunísia,0.32944,0.410788,0.340132,0.299804,0.301449,Dia 4
Equador,0.51645,0.261187,0.269850,0.246978,0.230256,Dia 4
Austrália,0.13824,0.373698,0.312427,0.289963,0.282051,Dia 4
Arábia Saudita,0.47056,0.227771,0.233626,0.198882,0.186747,Dia 4
Canadá,0.13506,0.286761,0.255616,0.297980,0.213559,Dia 4
Camarões,0.07915,0.316614,0.290503,0.273352,0.301508,Dia 4
Costa Rica,0.08218,0.281334,0.327422,0.297226,0.262222,Dia 4
Catar,0.05038,0.202461,0.244118,0.228916,0.333333,Dia 4
Gana,0.04364,0.129468,0.152212,0.174419,0.133333,Dia 4

### **Dia 5**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 5'

S = 100000
dia = 'Dia 5'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia5.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.73394,0.22166,0.04010,0.00430,0.95560,0.64153,0.39759,0.24890,0.14907,0.09983,0.09270,Dia 5
Bélgica,0.68824,0.20376,0.09596,0.01204,0.89200,0.58509,0.35872,0.21482,0.12749,0.08733,0.08948,Dia 5
França,0.70555,0.21003,0.07599,0.00843,0.91558,0.60010,0.35326,0.19519,0.10816,0.08703,0.09219,Dia 5
Inglaterra,0.74700,0.24875,0.00425,0.00000,0.99575,0.63584,0.35350,0.18721,0.10084,0.08637,0.09328,Dia 5
Espanha,0.69679,0.20210,0.09612,0.00499,0.89889,0.50987,0.26385,0.14530,0.07467,0.07063,0.06434,Dia 5
Holanda,0.64105,0.32420,0.03475,0.00000,0.96525,0.51161,0.27126,0.13154,0.06428,0.06726,0.07135,Dia 5
Portugal,0.54858,0.27217,0.17067,0.00858,0.82075,0.41460,0.20529,0.10356,0.04946,0.05410,0.05288,Dia 5
Argentina,0.26648,0.19387,0.27322,0.26643,0.46035,0.27276,0.16304,0.08980,0.04942,0.04038,0.04225,Dia 5
Dinamarca,0.20641,0.41354,0.26523,0.11482,0.61995,0.35785,0.18782,0.08956,0.04140,0.04816,0.04800,Dia 5
México,0.31982,0.28179,0.23589,0.16250,0.60161,0.30033,0.15291,0.06988,0.03217,0.03771,0.04072,Dia 5
Uruguai,0.28903,0.38052,0.27321,0.05724,0.66955,0.30249,0.14279,0.06854,0.03064,0.03790,0.03545,Dia 5
Suíça,0.23430,0.49943,0.23622,0.03005,0.73373,0.36663,0.16280,0.07388,0.03051,0.04337,0.03926,Dia 5
Croácia,0.17438,0.37226,0.30244,0.15092,0.54664,0.26682,0.11998,0.05756,0.02421,0.03335,0.02946,Dia 5
Estados Unidos,0.11153,0.34606,0.39282,0.14959,0.45759,0.24352,0.12116,0.05318,0.02257,0.03061,0.03220,Dia 5
Alemanha,0.03656,0.26422,0.46532,0.23390,0.30078,0.13621,0.06850,0.03277,0.01524,0.01753,0.01784,Dia 5
Senegal,0.17610,0.39049,0.42981,0.00360,0.56659,0.23587,0.09954,0.03885,0.01460,0.02425,0.02565,Dia 5
Japão,0.25845,0.45844,0.25929,0.02382,0.71689,0.26580,0.10184,0.03893,0.01336,0.02557,0.02379,Dia 5
Irã,0.14003,0.34159,0.40917,0.10921,0.48162,0.21975,0.09068,0.03339,0.01164,0.02175,0.02225,Dia 5
Marrocos,0.12008,0.30496,0.35284,0.22212,0.42504,0.17328,0.06617,0.02596,0.00936,0.01660,0.01504,Dia 5
Polônia,0.19255,0.27102,0.26161,0.27482,0.46357,0.17736,0.07010,0.02483,0.00894,0.01589,0.01678,Dia 5
Coreia do Sul,0.15725,0.30787,0.41673,0.11815,0.46512,0.14927,0.05149,0.01782,0.00513,0.01269,0.01162,Dia 5
Sérvia,0.02125,0.21069,0.40524,0.36282,0.23194,0.09495,0.03540,0.01343,0.00455,0.00888,0.00921,Dia 5
Tunísia,0.07572,0.25193,0.38565,0.28670,0.32765,0.13416,0.04717,0.01435,0.00414,0.01021,0.01050,Dia 5
Equador,0.18285,0.28531,0.53184,0.00000,0.46816,0.12324,0.03446,0.00854,0.00208,0.00646,0.00668,Dia 5
País de Gales,0.00144,0.06360,0.19376,0.74120,0.06504,0.03017,0.01359,0.00510,0.00195,0.00315,0.00381,Dia 5
Austrália,0.01232,0.12450,0.27313,0.59005,0.13682,0.05028,0.01590,0.00433,0.00113,0.00320,0.00354,Dia 5
Arábia Saudita,0.22115,0.25332,0.22928,0.29625,0.47447,0.10716,0.02561,0.00508,0.00091,0.00417,0.00458,Dia 5
Costa Rica,0.00820,0.07524,0.17927,0.73729,0.08344,0.02463,0.00822,0.00239,0.00080,0.00159,0.00201,Dia 5
Canadá,0.01730,0.11902,0.24876,0.61492,0.13632,0.03830,0.00979,0.00304,0.00072,0.00232,0.00179,Dia 5
Camarões,0.01051,0.06822,0.31844,0.60283,0.07873,0.02520,0.00694,0.00224,0.00056,0.00168,0.00125,Dia 5
Catar,0.00000,0.00000,0.00360,0.99640,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 5
Gana,0.00514,0.03944,0.13939,0.81603,0.04458,0.00533,0.00063,0.00003,0.00000,0.00003,0.00010,Dia 5

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 5'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia5.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.04440,0.31407,0.24394,0.14869,0.09983,0.14907,Dia 5
Bélgica,0.10800,0.30691,0.22637,0.14390,0.08733,0.12749,Dia 5
França,0.08442,0.31548,0.24684,0.15807,0.08703,0.10816,Dia 5
Inglaterra,0.00425,0.35991,0.28234,0.16629,0.08637,0.10084,Dia 5
Espanha,0.10111,0.38902,0.24602,0.11855,0.07063,0.07467,Dia 5
Holanda,0.03475,0.45364,0.24035,0.13972,0.06726,0.06428,Dia 5
Portugal,0.17925,0.40615,0.20931,0.10173,0.05410,0.04946,Dia 5
Argentina,0.53965,0.18759,0.10972,0.07324,0.04038,0.04942,Dia 5
Dinamarca,0.38005,0.26210,0.17003,0.09826,0.04816,0.04140,Dia 5
México,0.39839,0.30128,0.14742,0.08303,0.03771,0.03217,Dia 5
Uruguai,0.33045,0.36706,0.15970,0.07425,0.03790,0.03064,Dia 5
Suíça,0.26627,0.36710,0.20383,0.08892,0.04337,0.03051,Dia 5
Croácia,0.45336,0.27982,0.14684,0.06242,0.03335,0.02421,Dia 5
Estados Unidos,0.54241,0.21407,0.12236,0.06798,0.03061,0.02257,Dia 5
Alemanha,0.69922,0.16457,0.06771,0.03573,0.01753,0.01524,Dia 5
Senegal,0.43341,0.33072,0.13633,0.06069,0.02425,0.01460,Dia 5
Japão,0.28311,0.45109,0.16396,0.06291,0.02557,0.01336,Dia 5
Irã,0.51838,0.26187,0.12907,0.05729,0.02175,0.01164,Dia 5
Marrocos,0.57496,0.25176,0.10711,0.04021,0.01660,0.00936,Dia 5
Polônia,0.53643,0.28621,0.10726,0.04527,0.01589,0.00894,Dia 5
Coreia do Sul,0.53488,0.31585,0.09778,0.03367,0.01269,0.00513,Dia 5
Sérvia,0.76806,0.13699,0.05955,0.02197,0.00888,0.00455,Dia 5
Tunísia,0.67235,0.19349,0.08699,0.03282,0.01021,0.00414,Dia 5
Equador,0.53184,0.34492,0.08878,0.02592,0.00646,0.00208,Dia 5
País de Gales,0.93496,0.03487,0.01658,0.00849,0.00315,0.00195,Dia 5
Austrália,0.86318,0.08654,0.03438,0.01157,0.00320,0.00113,Dia 5
Arábia Saudita,0.52553,0.36731,0.08155,0.02053,0.00417,0.00091,Dia 5
Costa Rica,0.91656,0.05881,0.01641,0.00583,0.00159,0.00080,Dia 5
Canadá,0.86368,0.09802,0.02851,0.00675,0.00232,0.00072,Dia 5
Camarões,0.92127,0.05353,0.01826,0.00470,0.00168,0.00056,Dia 5
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 5
Gana,0.95542,0.03925,0.00470,0.00060,0.00003,0.00000,Dia 5

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 5'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia5.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.95560,0.671337,0.619753,0.626022,0.598915,Dia 5
Bélgica,0.89200,0.655930,0.613102,0.598851,0.593474,Dia 5
França,0.91558,0.655432,0.588669,0.552539,0.554127,Dia 5
Inglaterra,0.99575,0.638554,0.555957,0.529590,0.538646,Dia 5
Espanha,0.89889,0.567222,0.517485,0.550692,0.513902,Dia 5
Holanda,0.96525,0.530028,0.530209,0.484922,0.488673,Dia 5
Portugal,0.82075,0.505148,0.495152,0.504457,0.477598,Dia 5
Argentina,0.46035,0.592506,0.597742,0.550785,0.550334,Dia 5
Dinamarca,0.61995,0.577224,0.524857,0.476840,0.462260,Dia 5
México,0.60161,0.499210,0.509140,0.457001,0.460361,Dia 5
Uruguai,0.66955,0.451781,0.472049,0.480006,0.447038,Dia 5
Suíça,0.73373,0.499680,0.444044,0.453808,0.412967,Dia 5
Croácia,0.54664,0.488109,0.449666,0.479747,0.420605,Dia 5
Estados Unidos,0.45759,0.532179,0.497536,0.438924,0.424408,Dia 5
Alemanha,0.30078,0.452856,0.502900,0.478394,0.465060,Dia 5
Senegal,0.56659,0.416297,0.422012,0.390295,0.375804,Dia 5
Japão,0.71689,0.370768,0.383145,0.382266,0.343180,Dia 5
Irã,0.48162,0.456273,0.412651,0.368218,0.348607,Dia 5
Marrocos,0.42504,0.407679,0.381867,0.392323,0.360555,Dia 5
Polônia,0.46357,0.382596,0.395241,0.354208,0.360048,Dia 5
Coreia do Sul,0.46512,0.320928,0.344945,0.346087,0.287879,Dia 5
Sérvia,0.23194,0.409373,0.372828,0.379379,0.338794,Dia 5
Tunísia,0.32765,0.409461,0.351595,0.304219,0.288502,Dia 5
Equador,0.46816,0.263243,0.279617,0.247824,0.243560,Dia 5
País de Gales,0.06504,0.463868,0.450447,0.375276,0.382353,Dia 5
Austrália,0.13682,0.367490,0.316229,0.272327,0.260970,Dia 5
Arábia Saudita,0.47447,0.225852,0.238988,0.198360,0.179134,Dia 5
Costa Rica,0.08344,0.295182,0.333739,0.290754,0.334728,Dia 5
Canadá,0.13632,0.280957,0.255614,0.310521,0.236842,Dia 5
Camarões,0.07873,0.320081,0.275397,0.322767,0.250000,Dia 5
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 5
Gana,0.04458,0.119560,0.118199,0.047619,0.000000,Dia 5

### **Dia 6**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 6'

S = 100000
dia = 'Dia 6'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia6.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.73173,0.22434,0.03929,0.00464,0.95607,0.63931,0.39620,0.24477,0.14523,0.09954,0.09467,Dia 6
Bélgica,0.68829,0.20402,0.09472,0.01297,0.89231,0.58754,0.35959,0.21427,0.12538,0.08889,0.08922,Dia 6
França,0.99987,0.00013,0.00000,0.00000,1.00000,0.64431,0.37658,0.20861,0.11454,0.09407,0.09770,Dia 6
Inglaterra,0.74621,0.24913,0.00466,0.00000,0.99534,0.63603,0.33934,0.17832,0.09462,0.08370,0.09036,Dia 6
Argentina,0.58715,0.17282,0.23863,0.00140,0.75997,0.47292,0.28727,0.15826,0.08640,0.07186,0.07405,Dia 6
Espanha,0.69618,0.20164,0.09688,0.00530,0.89782,0.50757,0.26179,0.14187,0.07226,0.06961,0.06321,Dia 6
Holanda,0.63976,0.32545,0.03479,0.00000,0.96521,0.51088,0.26378,0.12594,0.06010,0.06584,0.07034,Dia 6
Portugal,0.54687,0.27135,0.17300,0.00878,0.81822,0.41642,0.20543,0.10213,0.04927,0.05286,0.05316,Dia 6
Dinamarca,0.00000,0.58360,0.29317,0.12323,0.58360,0.29787,0.15745,0.07390,0.03391,0.03999,0.04031,Dia 6
Suíça,0.23666,0.49794,0.23577,0.02963,0.73460,0.36421,0.16402,0.07291,0.03008,0.04283,0.04056,Dia 6
Uruguai,0.28915,0.38073,0.27163,0.05849,0.66988,0.30470,0.14330,0.06708,0.02974,0.03734,0.03564,Dia 6
Croácia,0.17581,0.36845,0.30419,0.15155,0.54426,0.26853,0.12076,0.05567,0.02368,0.03199,0.02939,Dia 6
Estados Unidos,0.11188,0.34650,0.39226,0.14936,0.45838,0.24648,0.11747,0.05221,0.02318,0.02903,0.02928,Dia 6
México,0.00000,0.35928,0.31471,0.32601,0.35928,0.14638,0.07279,0.03378,0.01552,0.01826,0.01952,Dia 6
Alemanha,0.03645,0.26316,0.46793,0.23246,0.29961,0.13405,0.06780,0.03220,0.01511,0.01709,0.01810,Dia 6
Senegal,0.17593,0.38899,0.43146,0.00362,0.56492,0.23417,0.09536,0.03866,0.01497,0.02369,0.02337,Dia 6
Japão,0.25888,0.46109,0.25539,0.02464,0.71997,0.26745,0.10218,0.03877,0.01349,0.02528,0.02460,Dia 6
Polônia,0.38292,0.30499,0.31209,0.00000,0.68791,0.27172,0.10773,0.03795,0.01293,0.02502,0.02574,Dia 6
Irã,0.14037,0.34105,0.40888,0.10970,0.48142,0.21833,0.08600,0.03180,0.01158,0.02022,0.02014,Dia 6
Marrocos,0.11891,0.30693,0.35311,0.22105,0.42584,0.17186,0.06436,0.02492,0.00886,0.01606,0.01495,Dia 6
Coreia do Sul,0.15905,0.30770,0.41470,0.11855,0.46675,0.15020,0.05349,0.01938,0.00599,0.01339,0.01180,Dia 6
Sérvia,0.02144,0.21007,0.40814,0.36035,0.23151,0.09465,0.03459,0.01260,0.00419,0.00841,0.00853,Dia 6
Austrália,0.00013,0.36553,0.54183,0.09251,0.36566,0.11275,0.03646,0.00949,0.00222,0.00727,0.00777,Dia 6
Equador,0.18431,0.28556,0.53013,0.00000,0.46987,0.12403,0.03184,0.00828,0.00206,0.00622,0.00593,Dia 6
País de Gales,0.00154,0.06332,0.19420,0.74094,0.06486,0.03008,0.01296,0.00508,0.00179,0.00329,0.00312,Dia 6
Canadá,0.01699,0.12060,0.24798,0.61443,0.13759,0.03964,0.01087,0.00311,0.00080,0.00231,0.00215,Dia 6
Costa Rica,0.00849,0.07411,0.17980,0.73760,0.08260,0.02336,0.00753,0.00234,0.00076,0.00158,0.00162,Dia 6
Camarões,0.01017,0.06765,0.31680,0.60538,0.07782,0.02519,0.00721,0.00202,0.00051,0.00151,0.00160,Dia 6
Tunísia,0.00000,0.05074,0.16500,0.78426,0.05074,0.01743,0.00612,0.00172,0.00043,0.00129,0.00140,Dia 6
Arábia Saudita,0.02993,0.16291,0.13457,0.67259,0.19284,0.03662,0.00885,0.00180,0.00039,0.00141,0.00168,Dia 6
Gana,0.00493,0.04022,0.14067,0.81418,0.04515,0.00532,0.00088,0.00016,0.00001,0.00015,0.00009,Dia 6
Catar,0.00000,0.00000,0.00362,0.99638,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 6

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 6'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia6.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.04393,0.31676,0.24311,0.15143,0.09954,0.14523,Dia 6
Bélgica,0.10769,0.30477,0.22795,0.14532,0.08889,0.12538,Dia 6
França,0.00000,0.35569,0.26773,0.16797,0.09407,0.11454,Dia 6
Inglaterra,0.00466,0.35931,0.29669,0.16102,0.08370,0.09462,Dia 6
Argentina,0.24003,0.28705,0.18565,0.12901,0.07186,0.08640,Dia 6
Espanha,0.10218,0.39025,0.24578,0.11992,0.06961,0.07226,Dia 6
Holanda,0.03479,0.45433,0.24710,0.13784,0.06584,0.06010,Dia 6
Portugal,0.18178,0.40180,0.21099,0.10330,0.05286,0.04927,Dia 6
Dinamarca,0.41640,0.28573,0.14042,0.08355,0.03999,0.03391,Dia 6
Suíça,0.26540,0.37039,0.20019,0.09111,0.04283,0.03008,Dia 6
Uruguai,0.33012,0.36518,0.16140,0.07622,0.03734,0.02974,Dia 6
Croácia,0.45574,0.27573,0.14777,0.06509,0.03199,0.02368,Dia 6
Estados Unidos,0.54162,0.21190,0.12901,0.06526,0.02903,0.02318,Dia 6
México,0.64072,0.21290,0.07359,0.03901,0.01826,0.01552,Dia 6
Alemanha,0.70039,0.16556,0.06625,0.03560,0.01709,0.01511,Dia 6
Senegal,0.43508,0.33075,0.13881,0.05670,0.02369,0.01497,Dia 6
Japão,0.28003,0.45252,0.16527,0.06341,0.02528,0.01349,Dia 6
Polônia,0.31209,0.41619,0.16399,0.06978,0.02502,0.01293,Dia 6
Irã,0.51858,0.26309,0.13233,0.05420,0.02022,0.01158,Dia 6
Marrocos,0.57416,0.25398,0.10750,0.03944,0.01606,0.00886,Dia 6
Coreia do Sul,0.53325,0.31655,0.09671,0.03411,0.01339,0.00599,Dia 6
Sérvia,0.76849,0.13686,0.06006,0.02199,0.00841,0.00419,Dia 6
Austrália,0.63434,0.25291,0.07629,0.02697,0.00727,0.00222,Dia 6
Equador,0.53013,0.34584,0.09219,0.02356,0.00622,0.00206,Dia 6
País de Gales,0.93514,0.03478,0.01712,0.00788,0.00329,0.00179,Dia 6
Canadá,0.86241,0.09795,0.02877,0.00776,0.00231,0.00080,Dia 6
Costa Rica,0.91740,0.05924,0.01583,0.00519,0.00158,0.00076,Dia 6
Camarões,0.92218,0.05263,0.01798,0.00519,0.00151,0.00051,Dia 6
Tunísia,0.94926,0.03331,0.01131,0.00440,0.00129,0.00043,Dia 6
Arábia Saudita,0.80716,0.15622,0.02777,0.00705,0.00141,0.00039,Dia 6
Gana,0.95485,0.03983,0.00444,0.00072,0.00015,0.00001,Dia 6
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 6

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 6'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia6.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.95607,0.668685,0.619731,0.617794,0.593333,Dia 6
Bélgica,0.89231,0.658448,0.612026,0.595873,0.585150,Dia 6
França,1.00000,0.644310,0.584470,0.553959,0.549063,Dia 6
Inglaterra,0.99534,0.639008,0.533528,0.525491,0.530619,Dia 6
Argentina,0.75997,0.622288,0.607439,0.550910,0.545937,Dia 6
Espanha,0.89782,0.565336,0.515771,0.541923,0.509340,Dia 6
Holanda,0.96521,0.529294,0.516325,0.477443,0.477211,Dia 6
Portugal,0.81822,0.508934,0.493324,0.497152,0.482424,Dia 6
Dinamarca,0.58360,0.510401,0.528586,0.469355,0.458863,Dia 6
Suíça,0.73460,0.495794,0.450345,0.444519,0.412563,Dia 6
Uruguai,0.66988,0.454858,0.470299,0.468109,0.443351,Dia 6
Croácia,0.54426,0.493386,0.449708,0.460997,0.425364,Dia 6
Estados Unidos,0.45838,0.537720,0.476590,0.444454,0.443976,Dia 6
México,0.35928,0.407426,0.497267,0.464075,0.459443,Dia 6
Alemanha,0.29961,0.447415,0.505781,0.474926,0.469255,Dia 6
Senegal,0.56492,0.414519,0.407226,0.405411,0.387222,Dia 6
Japão,0.71997,0.371474,0.382053,0.379428,0.347949,Dia 6
Polônia,0.68791,0.394994,0.396474,0.352270,0.340711,Dia 6
Irã,0.48142,0.453513,0.393899,0.369767,0.364151,Dia 6
Marrocos,0.42584,0.403579,0.374491,0.387197,0.355538,Dia 6
Coreia do Sul,0.46675,0.321800,0.356125,0.362311,0.309082,Dia 6
Sérvia,0.23151,0.408838,0.365452,0.364267,0.332540,Dia 6
Austrália,0.36566,0.308347,0.323370,0.260285,0.233930,Dia 6
Equador,0.46987,0.263967,0.256712,0.260050,0.248792,Dia 6
País de Gales,0.06486,0.463768,0.430851,0.391975,0.352362,Dia 6
Canadá,0.13759,0.288102,0.274218,0.286109,0.257235,Dia 6
Costa Rica,0.08260,0.282809,0.322346,0.310757,0.324786,Dia 6
Camarões,0.07782,0.323696,0.286225,0.280166,0.252475,Dia 6
Tunísia,0.05074,0.343516,0.351119,0.281046,0.250000,Dia 6
Arábia Saudita,0.19284,0.189898,0.241671,0.203390,0.216667,Dia 6
Gana,0.04515,0.117829,0.165414,0.181818,0.062500,Dia 6
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 6

### **Dia 7**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 7'

S = 100000
dia = 'Dia 7'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia7.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.73337,0.22170,0.04019,0.00474,0.95507,0.64035,0.39926,0.24657,0.14921,0.09736,0.09580,Dia 7
França,0.99991,0.00009,0.00000,0.00000,1.00000,0.64520,0.37805,0.21984,0.12014,0.09970,0.09137,Dia 7
Inglaterra,0.74536,0.24982,0.00482,0.00000,0.99518,0.63189,0.33733,0.18482,0.09827,0.08655,0.08553,Dia 7
Argentina,0.58296,0.17462,0.24127,0.00115,0.75758,0.47477,0.28667,0.15940,0.09019,0.06921,0.07422,Dia 7
Espanha,0.72491,0.22783,0.04726,0.00000,0.95274,0.54355,0.28020,0.15091,0.07791,0.07300,0.07128,Dia 7
Bélgica,0.25758,0.26802,0.44175,0.03265,0.52560,0.33666,0.20224,0.12207,0.07127,0.05080,0.04973,Dia 7
Holanda,0.63905,0.32490,0.03605,0.00000,0.96395,0.50962,0.26169,0.12947,0.06322,0.06625,0.06849,Dia 7
Portugal,0.54638,0.27306,0.17151,0.00905,0.81944,0.41671,0.22063,0.10826,0.05153,0.05673,0.05789,Dia 7
Dinamarca,0.00000,0.58377,0.29505,0.12118,0.58377,0.29712,0.15915,0.07488,0.03580,0.03908,0.04214,Dia 7
Suíça,0.23486,0.50209,0.23345,0.02960,0.73695,0.36567,0.17318,0.07701,0.03189,0.04512,0.04396,Dia 7
Uruguai,0.29254,0.37870,0.27066,0.05810,0.67124,0.30523,0.15255,0.07063,0.03189,0.03874,0.03882,Dia 7
Croácia,0.32885,0.25292,0.41823,0.00000,0.58177,0.29233,0.13536,0.06172,0.02777,0.03395,0.03410,Dia 7
Alemanha,0.00000,0.43047,0.13575,0.43378,0.43047,0.22373,0.11476,0.05332,0.02474,0.02858,0.03004,Dia 7
Estados Unidos,0.11359,0.34507,0.39120,0.15014,0.45866,0.24722,0.11770,0.05201,0.02276,0.02925,0.03069,Dia 7
Marrocos,0.41357,0.47906,0.10737,0.00000,0.89263,0.37147,0.14195,0.05348,0.01889,0.03459,0.03495,Dia 7
Senegal,0.17633,0.39176,0.42839,0.00352,0.56809,0.23946,0.09681,0.03982,0.01555,0.02427,0.02412,Dia 7
México,0.00000,0.35896,0.31477,0.32627,0.35896,0.14625,0.07158,0.03427,0.01549,0.01878,0.01898,Dia 7
Polônia,0.38663,0.30392,0.30945,0.00000,0.69055,0.27147,0.10854,0.03895,0.01320,0.02575,0.02634,Dia 7
Irã,0.13962,0.34124,0.40782,0.11132,0.48086,0.21820,0.08749,0.03290,0.01185,0.02105,0.02117,Dia 7
Japão,0.22739,0.06324,0.70932,0.00005,0.29063,0.12086,0.04416,0.01709,0.00625,0.01084,0.01020,Dia 7
Coreia do Sul,0.15626,0.30731,0.41766,0.11877,0.46357,0.14775,0.05339,0.01879,0.00607,0.01272,0.01170,Dia 7
Sérvia,0.02140,0.20818,0.40992,0.36050,0.22958,0.09361,0.03819,0.01373,0.00478,0.00895,0.00911,Dia 7
Costa Rica,0.04770,0.27846,0.10767,0.56617,0.32616,0.11140,0.03557,0.01086,0.00323,0.00763,0.00780,Dia 7
Austrália,0.00009,0.36551,0.54026,0.09414,0.36560,0.11047,0.03541,0.00966,0.00254,0.00712,0.00732,Dia 7
Equador,0.18462,0.28334,0.53204,0.00000,0.46796,0.12333,0.03246,0.00858,0.00230,0.00628,0.00646,Dia 7
País de Gales,0.00143,0.06387,0.19616,0.73854,0.06530,0.03028,0.01276,0.00497,0.00166,0.00331,0.00305,Dia 7
Tunísia,0.00000,0.05063,0.16469,0.78468,0.05063,0.01686,0.00571,0.00188,0.00062,0.00126,0.00123,Dia 7
Camarões,0.01037,0.06803,0.31644,0.60516,0.07840,0.02475,0.00764,0.00220,0.00055,0.00165,0.00177,Dia 7
Arábia Saudita,0.03041,0.16250,0.13451,0.67258,0.19291,0.03786,0.00865,0.00179,0.00042,0.00137,0.00160,Dia 7
Gana,0.00482,0.04093,0.14017,0.81408,0.04575,0.00593,0.00092,0.00012,0.00001,0.00011,0.00014,Dia 7
Canadá,0.00000,0.00000,0.03265,0.96735,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 7
Catar,0.00000,0.00000,0.00352,0.99648,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 7

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 7'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia7.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.04493,0.31472,0.24109,0.15269,0.09736,0.14921,Dia 7
França,0.00000,0.35480,0.26715,0.15821,0.09970,0.12014,Dia 7
Inglaterra,0.00482,0.36329,0.29456,0.15251,0.08655,0.09827,Dia 7
Argentina,0.24242,0.28281,0.18810,0.12727,0.06921,0.09019,Dia 7
Espanha,0.04726,0.40919,0.26335,0.12929,0.07300,0.07791,Dia 7
Bélgica,0.47440,0.18894,0.13442,0.08017,0.05080,0.07127,Dia 7
Holanda,0.03605,0.45433,0.24793,0.13222,0.06625,0.06322,Dia 7
Portugal,0.18056,0.40273,0.19608,0.11237,0.05673,0.05153,Dia 7
Dinamarca,0.41623,0.28665,0.13797,0.08427,0.03908,0.03580,Dia 7
Suíça,0.26305,0.37128,0.19249,0.09617,0.04512,0.03189,Dia 7
Uruguai,0.32876,0.36601,0.15268,0.08192,0.03874,0.03189,Dia 7
Croácia,0.41823,0.28944,0.15697,0.07364,0.03395,0.02777,Dia 7
Alemanha,0.56953,0.20674,0.10897,0.06144,0.02858,0.02474,Dia 7
Estados Unidos,0.54134,0.21144,0.12952,0.06569,0.02925,0.02276,Dia 7
Marrocos,0.10737,0.52116,0.22952,0.08847,0.03459,0.01889,Dia 7
Senegal,0.43191,0.32863,0.14265,0.05699,0.02427,0.01555,Dia 7
México,0.64104,0.21271,0.07467,0.03731,0.01878,0.01549,Dia 7
Polônia,0.30945,0.41908,0.16293,0.06959,0.02575,0.01320,Dia 7
Irã,0.51914,0.26266,0.13071,0.05459,0.02105,0.01185,Dia 7
Japão,0.70937,0.16977,0.07670,0.02707,0.01084,0.00625,Dia 7
Coreia do Sul,0.53643,0.31582,0.09436,0.03460,0.01272,0.00607,Dia 7
Sérvia,0.77042,0.13597,0.05542,0.02446,0.00895,0.00478,Dia 7
Costa Rica,0.67384,0.21476,0.07583,0.02471,0.00763,0.00323,Dia 7
Austrália,0.63440,0.25513,0.07506,0.02575,0.00712,0.00254,Dia 7
Equador,0.53204,0.34463,0.09087,0.02388,0.00628,0.00230,Dia 7
País de Gales,0.93470,0.03502,0.01752,0.00779,0.00331,0.00166,Dia 7
Tunísia,0.94937,0.03377,0.01115,0.00383,0.00126,0.00062,Dia 7
Camarões,0.92160,0.05365,0.01711,0.00544,0.00165,0.00055,Dia 7
Arábia Saudita,0.80709,0.15505,0.02921,0.00686,0.00137,0.00042,Dia 7
Gana,0.95425,0.03982,0.00501,0.00080,0.00011,0.00001,Dia 7
Canadá,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 7
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 7

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 7'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia7.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,0.95507,0.670474,0.623503,0.617567,0.605143,Dia 7
França,1.00000,0.645200,0.585942,0.581510,0.546488,Dia 7
Inglaterra,0.99518,0.634950,0.533843,0.547891,0.531707,Dia 7
Argentina,0.75758,0.626693,0.603808,0.556040,0.565809,Dia 7
Espanha,0.95274,0.570512,0.515500,0.538580,0.516268,Dia 7
Bélgica,0.52560,0.640525,0.600725,0.603590,0.583845,Dia 7
Holanda,0.96395,0.528679,0.513500,0.494746,0.488298,Dia 7
Portugal,0.81944,0.508530,0.529457,0.490686,0.475984,Dia 7
Dinamarca,0.58377,0.508968,0.535642,0.470500,0.478098,Dia 7
Suíça,0.73695,0.496194,0.473596,0.444682,0.414102,Dia 7
Uruguai,0.67124,0.454726,0.499787,0.462996,0.451508,Dia 7
Croácia,0.58177,0.502484,0.463038,0.455969,0.449935,Dia 7
Alemanha,0.43047,0.519734,0.512940,0.464622,0.463991,Dia 7
Estados Unidos,0.45866,0.539005,0.476094,0.441886,0.437608,Dia 7
Marrocos,0.89263,0.416152,0.382130,0.376752,0.353216,Dia 7
Senegal,0.56809,0.421518,0.404285,0.411321,0.390507,Dia 7
México,0.35896,0.407427,0.489436,0.478765,0.451999,Dia 7
Polônia,0.69055,0.393121,0.399823,0.358854,0.338896,Dia 7
Irã,0.48086,0.453770,0.400962,0.376043,0.360182,Dia 7
Japão,0.29063,0.415855,0.365381,0.387002,0.365711,Dia 7
Coreia do Sul,0.46357,0.318722,0.361354,0.351939,0.323044,Dia 7
Sérvia,0.22958,0.407745,0.407969,0.359518,0.348143,Dia 7
Costa Rica,0.32616,0.341550,0.319300,0.305313,0.297422,Dia 7
Austrália,0.36560,0.302161,0.320540,0.272804,0.262940,Dia 7
Equador,0.46796,0.263548,0.263196,0.264325,0.268065,Dia 7
País de Gales,0.06530,0.463706,0.421400,0.389498,0.334004,Dia 7
Tunísia,0.05063,0.333004,0.338671,0.329247,0.329787,Dia 7
Camarões,0.07840,0.315689,0.308687,0.287958,0.250000,Dia 7
Arábia Saudita,0.19291,0.196257,0.228473,0.206936,0.234637,Dia 7
Gana,0.04575,0.129617,0.155143,0.130435,0.083333,Dia 7
Canadá,0.00000,NaN,NaN,NaN,NaN,Dia 7
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 7

### **Dia 8**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 8'

S = 100000
dia = 'Dia 8'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia8.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.97523,0.02477,0.00000,0.00000,1.00000,0.70556,0.44075,0.27659,0.16680,0.10979,0.10266,Dia 8
França,0.99987,0.00013,0.00000,0.00000,1.00000,0.64653,0.37894,0.22146,0.11850,0.10296,0.08861,Dia 8
Inglaterra,0.74462,0.25069,0.00469,0.00000,0.99531,0.63472,0.33823,0.18613,0.09768,0.08845,0.08476,Dia 8
Argentina,0.58453,0.17512,0.23922,0.00113,0.75965,0.47297,0.28685,0.15446,0.08659,0.06787,0.07768,Dia 8
Espanha,0.72589,0.22735,0.04676,0.00000,0.95324,0.54518,0.27048,0.14562,0.07527,0.07035,0.06713,Dia 8
Portugal,0.99323,0.00677,0.00000,0.00000,1.00000,0.57794,0.30998,0.15058,0.07186,0.07872,0.08117,Dia 8
Bélgica,0.25686,0.26706,0.44265,0.03343,0.52392,0.33427,0.19397,0.11605,0.06824,0.04781,0.04805,Dia 8
Holanda,0.64048,0.32399,0.03553,0.00000,0.96447,0.50994,0.25992,0.12525,0.06076,0.06449,0.07011,Dia 8
Dinamarca,0.00000,0.58504,0.29041,0.12455,0.58504,0.29774,0.15850,0.06999,0.03349,0.03650,0.04470,Dia 8
Croácia,0.32987,0.25372,0.41641,0.00000,0.58359,0.29240,0.13148,0.06067,0.02659,0.03408,0.03363,Dia 8
Suíça,0.02477,0.65570,0.28707,0.03246,0.68047,0.30754,0.14905,0.06447,0.02609,0.03838,0.03877,Dia 8
Uruguai,0.00000,0.65137,0.20884,0.13979,0.65137,0.23754,0.11471,0.05609,0.02585,0.03024,0.02776,Dia 8
Alemanha,0.00000,0.43082,0.13409,0.43509,0.43082,0.22431,0.11515,0.05271,0.02409,0.02862,0.02950,Dia 8
Estados Unidos,0.11317,0.34609,0.39044,0.15030,0.45926,0.24673,0.11751,0.05163,0.02274,0.02889,0.03087,Dia 8
Marrocos,0.41327,0.47922,0.10751,0.00000,0.89249,0.37049,0.13714,0.05231,0.01871,0.03360,0.03231,Dia 8
México,0.00000,0.35743,0.31657,0.32600,0.35743,0.14541,0.07171,0.03564,0.01598,0.01966,0.01776,Dia 8
Senegal,0.17548,0.39067,0.43011,0.00374,0.56615,0.23532,0.09477,0.03847,0.01478,0.02369,0.02356,Dia 8
Polônia,0.38603,0.30418,0.30979,0.00000,0.69021,0.27175,0.10903,0.03709,0.01229,0.02480,0.02669,Dia 8
Irã,0.14062,0.34001,0.40862,0.11075,0.48063,0.21962,0.08779,0.03184,0.01119,0.02065,0.02134,Dia 8
Japão,0.22547,0.06331,0.71116,0.00006,0.28878,0.12206,0.04229,0.01621,0.00559,0.01062,0.01000,Dia 8
Sérvia,0.00000,0.26939,0.29692,0.43369,0.26939,0.10061,0.04054,0.01446,0.00485,0.00961,0.00997,Dia 8
Costa Rica,0.04864,0.27852,0.10799,0.56485,0.32716,0.11129,0.03532,0.01074,0.00302,0.00772,0.00773,Dia 8
Austrália,0.00013,0.36374,0.54358,0.09255,0.36387,0.11164,0.03629,0.00895,0.00241,0.00654,0.00838,Dia 8
País de Gales,0.00159,0.06321,0.19625,0.73895,0.06480,0.03084,0.01413,0.00526,0.00210,0.00316,0.00368,Dia 8
Equador,0.18404,0.28534,0.53062,0.00000,0.46938,0.12283,0.03231,0.00808,0.00195,0.00613,0.00664,Dia 8
Coreia do Sul,0.00000,0.12417,0.18020,0.69563,0.12417,0.03101,0.01091,0.00383,0.00121,0.00262,0.00248,Dia 8
Tunísia,0.00000,0.05109,0.16601,0.78290,0.05109,0.01728,0.00577,0.00163,0.00059,0.00104,0.00122,Dia 8
Camarões,0.00000,0.05014,0.41601,0.53385,0.05014,0.01432,0.00441,0.00135,0.00037,0.00098,0.00100,Dia 8
Arábia Saudita,0.02944,0.16327,0.13442,0.67287,0.19271,0.03668,0.00825,0.00184,0.00033,0.00151,0.00141,Dia 8
Gana,0.00677,0.21769,0.61096,0.16458,0.22446,0.02548,0.00382,0.00060,0.00008,0.00052,0.00043,Dia 8
Canadá,0.00000,0.00000,0.03343,0.96657,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 8
Catar,0.00000,0.00000,0.00374,0.99626,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 8

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 8'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia8.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.00000,0.29444,0.26481,0.16416,0.10979,0.16680,Dia 8
França,0.00000,0.35347,0.26759,0.15748,0.10296,0.11850,Dia 8
Inglaterra,0.00469,0.36059,0.29649,0.15210,0.08845,0.09768,Dia 8
Argentina,0.24035,0.28668,0.18612,0.13239,0.06787,0.08659,Dia 8
Espanha,0.04676,0.40806,0.27470,0.12486,0.07035,0.07527,Dia 8
Portugal,0.00000,0.42206,0.26796,0.15940,0.07872,0.07186,Dia 8
Bélgica,0.47608,0.18965,0.14030,0.07792,0.04781,0.06824,Dia 8
Holanda,0.03553,0.45453,0.25002,0.13467,0.06449,0.06076,Dia 8
Dinamarca,0.41496,0.28730,0.13924,0.08851,0.03650,0.03349,Dia 8
Croácia,0.41641,0.29119,0.16092,0.07081,0.03408,0.02659,Dia 8
Suíça,0.31953,0.37293,0.15849,0.08458,0.03838,0.02609,Dia 8
Uruguai,0.34863,0.41383,0.12283,0.05862,0.03024,0.02585,Dia 8
Alemanha,0.56918,0.20651,0.10916,0.06244,0.02862,0.02409,Dia 8
Estados Unidos,0.54074,0.21253,0.12922,0.06588,0.02889,0.02274,Dia 8
Marrocos,0.10751,0.52200,0.23335,0.08483,0.03360,0.01871,Dia 8
México,0.64257,0.21202,0.07370,0.03607,0.01966,0.01598,Dia 8
Senegal,0.43385,0.33083,0.14055,0.05630,0.02369,0.01478,Dia 8
Polônia,0.30979,0.41846,0.16272,0.07194,0.02480,0.01229,Dia 8
Irã,0.51937,0.26101,0.13183,0.05595,0.02065,0.01119,Dia 8
Japão,0.71122,0.16672,0.07977,0.02608,0.01062,0.00559,Dia 8
Sérvia,0.73061,0.16878,0.06007,0.02608,0.00961,0.00485,Dia 8
Costa Rica,0.67284,0.21587,0.07597,0.02458,0.00772,0.00302,Dia 8
Austrália,0.63613,0.25223,0.07535,0.02734,0.00654,0.00241,Dia 8
País de Gales,0.93520,0.03396,0.01671,0.00887,0.00316,0.00210,Dia 8
Equador,0.53062,0.34655,0.09052,0.02423,0.00613,0.00195,Dia 8
Coreia do Sul,0.87583,0.09316,0.02010,0.00708,0.00262,0.00121,Dia 8
Tunísia,0.94891,0.03381,0.01151,0.00414,0.00104,0.00059,Dia 8
Camarões,0.94986,0.03582,0.00991,0.00306,0.00098,0.00037,Dia 8
Arábia Saudita,0.80729,0.15603,0.02843,0.00641,0.00151,0.00033,Dia 8
Gana,0.77554,0.19898,0.02166,0.00322,0.00052,0.00008,Dia 8
Canadá,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 8
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 8

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 8'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia8.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.00000,0.705560,0.624681,0.627544,0.603059,Dia 8
França,1.00000,0.646530,0.586114,0.584420,0.535085,Dia 8
Inglaterra,0.99531,0.637711,0.532881,0.550306,0.524794,Dia 8
Argentina,0.75965,0.622616,0.606487,0.538470,0.560598,Dia 8
Espanha,0.95324,0.571923,0.496130,0.538376,0.516893,Dia 8
Portugal,1.00000,0.577940,0.536353,0.485773,0.477221,Dia 8
Bélgica,0.52392,0.638017,0.580279,0.598288,0.588022,Dia 8
Holanda,0.96447,0.528726,0.509707,0.481879,0.485110,Dia 8
Dinamarca,0.58504,0.508922,0.532344,0.441577,0.478497,Dia 8
Croácia,0.58359,0.501037,0.449658,0.461439,0.438273,Dia 8
Suíça,0.68047,0.451952,0.484652,0.432539,0.404684,Dia 8
Uruguai,0.65137,0.364678,0.482908,0.488972,0.460866,Dia 8
Alemanha,0.43082,0.520658,0.513352,0.457751,0.457029,Dia 8
Estados Unidos,0.45926,0.537234,0.476270,0.439367,0.440442,Dia 8
Marrocos,0.89249,0.415119,0.370158,0.381435,0.357675,Dia 8
México,0.35743,0.406821,0.493157,0.497002,0.448373,Dia 8
Senegal,0.56615,0.415650,0.402728,0.405930,0.384195,Dia 8
Polônia,0.69021,0.393721,0.401214,0.340182,0.331356,Dia 8
Irã,0.48063,0.456942,0.399736,0.362684,0.351445,Dia 8
Japão,0.28878,0.422675,0.346469,0.383306,0.344849,Dia 8
Sérvia,0.26939,0.373473,0.402942,0.356685,0.335408,Dia 8
Costa Rica,0.32716,0.340170,0.317369,0.304077,0.281192,Dia 8
Austrália,0.36387,0.306813,0.325063,0.246624,0.269274,Dia 8
País de Gales,0.06480,0.475926,0.458171,0.372258,0.399240,Dia 8
Equador,0.46938,0.261686,0.263046,0.250077,0.241337,Dia 8
Coreia do Sul,0.12417,0.249738,0.351822,0.351054,0.315927,Dia 8
Tunísia,0.05109,0.338227,0.333912,0.282496,0.361963,Dia 8
Camarões,0.05014,0.285600,0.307961,0.306122,0.274074,Dia 8
Arábia Saudita,0.19271,0.190338,0.224918,0.223030,0.179348,Dia 8
Gana,0.22446,0.113517,0.149922,0.157068,0.133333,Dia 8
Canadá,0.00000,NaN,NaN,NaN,NaN,Dia 8
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 8

### **Dia 9**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 9'

S = 100000
dia = 'Dia 9'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia9.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.97411,0.02589,0.00000,0.00000,1.00000,0.70892,0.44130,0.27249,0.16436,0.10813,0.10526,Dia 9
França,0.99986,0.00014,0.00000,0.00000,1.00000,0.64525,0.36501,0.21485,0.11468,0.10017,0.08365,Dia 9
Inglaterra,1.00000,0.00000,0.00000,0.00000,1.00000,0.63475,0.33328,0.18899,0.09721,0.09178,0.07822,Dia 9
Argentina,0.58365,0.17584,0.23918,0.00133,0.75949,0.47259,0.27727,0.15049,0.08449,0.06600,0.07465,Dia 9
Espanha,0.72706,0.22855,0.04439,0.00000,0.95561,0.54613,0.27063,0.14325,0.07359,0.06966,0.06972,Dia 9
Portugal,0.99283,0.00717,0.00000,0.00000,1.00000,0.57879,0.30993,0.14899,0.07048,0.07851,0.07980,Dia 9
Bélgica,0.25531,0.26841,0.44330,0.03298,0.52372,0.33261,0.19504,0.11718,0.06867,0.04851,0.04720,Dia 9
Holanda,1.00000,0.00000,0.00000,0.00000,1.00000,0.54163,0.28867,0.13434,0.06589,0.06845,0.07847,Dia 9
Estados Unidos,0.00000,1.00000,0.00000,0.00000,1.00000,0.45837,0.22645,0.09492,0.04204,0.05288,0.06145,Dia 9
Dinamarca,0.00000,0.58330,0.29407,0.12263,0.58330,0.29681,0.14984,0.06624,0.03131,0.03493,0.04258,Dia 9
Suíça,0.02589,0.65385,0.28829,0.03197,0.67974,0.30768,0.14857,0.06421,0.02643,0.03778,0.03799,Dia 9
Alemanha,0.00000,0.43294,0.13703,0.43003,0.43294,0.22610,0.11705,0.05488,0.02504,0.02984,0.02981,Dia 9
Croácia,0.32926,0.25499,0.41575,0.00000,0.58425,0.29232,0.13230,0.05864,0.02472,0.03392,0.03482,Dia 9
Uruguai,0.00000,0.64917,0.20943,0.14140,0.64917,0.23481,0.11291,0.05325,0.02441,0.02884,0.02786,Dia 9
Senegal,0.00000,1.00000,0.00000,0.00000,1.00000,0.36525,0.14290,0.06150,0.02336,0.03814,0.03431,Dia 9
Marrocos,0.41543,0.47660,0.10797,0.00000,0.89203,0.37217,0.13648,0.05012,0.01751,0.03261,0.03223,Dia 9
México,0.00000,0.35575,0.31721,0.32704,0.35575,0.14523,0.06890,0.03348,0.01521,0.01827,0.01666,Dia 9
Polônia,0.38703,0.30405,0.30892,0.00000,0.69108,0.27379,0.10147,0.03492,0.01214,0.02278,0.02509,Dia 9
Japão,0.22460,0.06440,0.71082,0.00018,0.28900,0.11992,0.04125,0.01539,0.00521,0.01018,0.00981,Dia 9
Sérvia,0.00000,0.26954,0.29694,0.43352,0.26954,0.09997,0.04030,0.01433,0.00495,0.00938,0.00941,Dia 9
Costa Rica,0.04834,0.27411,0.10776,0.56979,0.32245,0.11075,0.03495,0.01009,0.00322,0.00687,0.00722,Dia 9
Austrália,0.00014,0.36700,0.54111,0.09175,0.36714,0.11255,0.03304,0.00857,0.00248,0.00609,0.00708,Dia 9
Coreia do Sul,0.00000,0.12493,0.18344,0.69163,0.12493,0.03132,0.01089,0.00361,0.00127,0.00234,0.00261,Dia 9
Tunísia,0.00000,0.04956,0.16482,0.78562,0.04956,0.01681,0.00540,0.00157,0.00049,0.00108,0.00131,Dia 9
Camarões,0.00000,0.05072,0.41477,0.53451,0.05072,0.01408,0.00474,0.00138,0.00038,0.00100,0.00089,Dia 9
Arábia Saudita,0.02932,0.16436,0.13469,0.67163,0.19368,0.03697,0.00777,0.00180,0.00031,0.00149,0.00146,Dia 9
Gana,0.00717,0.21873,0.60713,0.16697,0.22590,0.02443,0.00366,0.00052,0.00015,0.00037,0.00044,Dia 9
Canadá,0.00000,0.00000,0.03298,0.96702,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Equador,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
País de Gales,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Irã,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Catar,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 9'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia9.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.00000,0.29108,0.26762,0.16881,0.10813,0.16436,Dia 9
França,0.00000,0.35475,0.28024,0.15016,0.10017,0.11468,Dia 9
Inglaterra,0.00000,0.36525,0.30147,0.14429,0.09178,0.09721,Dia 9
Argentina,0.24051,0.28690,0.19532,0.12678,0.06600,0.08449,Dia 9
Espanha,0.04439,0.40948,0.27550,0.12738,0.06966,0.07359,Dia 9
Portugal,0.00000,0.42121,0.26886,0.16094,0.07851,0.07048,Dia 9
Bélgica,0.47628,0.19111,0.13757,0.07786,0.04851,0.06867,Dia 9
Holanda,0.00000,0.45837,0.25296,0.15433,0.06845,0.06589,Dia 9
Estados Unidos,0.00000,0.54163,0.23192,0.13153,0.05288,0.04204,Dia 9
Dinamarca,0.41670,0.28649,0.14697,0.08360,0.03493,0.03131,Dia 9
Suíça,0.32026,0.37206,0.15911,0.08436,0.03778,0.02643,Dia 9
Alemanha,0.56706,0.20684,0.10905,0.06217,0.02984,0.02504,Dia 9
Croácia,0.41575,0.29193,0.16002,0.07366,0.03392,0.02472,Dia 9
Uruguai,0.35083,0.41436,0.12190,0.05966,0.02884,0.02441,Dia 9
Senegal,0.00000,0.63475,0.22235,0.08140,0.03814,0.02336,Dia 9
Marrocos,0.10797,0.51986,0.23569,0.08636,0.03261,0.01751,Dia 9
México,0.64425,0.21052,0.07633,0.03542,0.01827,0.01521,Dia 9
Polônia,0.30892,0.41729,0.17232,0.06655,0.02278,0.01214,Dia 9
Japão,0.71100,0.16908,0.07867,0.02586,0.01018,0.00521,Dia 9
Sérvia,0.73046,0.16957,0.05967,0.02597,0.00938,0.00495,Dia 9
Costa Rica,0.67755,0.21170,0.07580,0.02486,0.00687,0.00322,Dia 9
Austrália,0.63286,0.25459,0.07951,0.02447,0.00609,0.00248,Dia 9
Coreia do Sul,0.87507,0.09361,0.02043,0.00728,0.00234,0.00127,Dia 9
Tunísia,0.95044,0.03275,0.01141,0.00383,0.00108,0.00049,Dia 9
Camarões,0.94928,0.03664,0.00934,0.00336,0.00100,0.00038,Dia 9
Arábia Saudita,0.80632,0.15671,0.02920,0.00597,0.00149,0.00031,Dia 9
Gana,0.77410,0.20147,0.02077,0.00314,0.00037,0.00015,Dia 9
Canadá,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Equador,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
País de Gales,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Irã,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 9

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 9'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia9.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.00000,0.708920,0.622496,0.617471,0.603178,Dia 9
França,1.00000,0.645250,0.565688,0.588614,0.533768,Dia 9
Inglaterra,1.00000,0.634750,0.525057,0.567061,0.514366,Dia 9
Argentina,0.75949,0.622247,0.586703,0.542756,0.561433,Dia 9
Espanha,0.95561,0.571499,0.495541,0.529320,0.513717,Dia 9
Portugal,1.00000,0.578790,0.535479,0.480721,0.473052,Dia 9
Bélgica,0.52372,0.635091,0.586392,0.600800,0.586022,Dia 9
Holanda,1.00000,0.541630,0.532965,0.465376,0.490472,Dia 9
Estados Unidos,1.00000,0.458370,0.494033,0.419165,0.442899,Dia 9
Dinamarca,0.58330,0.508846,0.504835,0.442072,0.472675,Dia 9
Suíça,0.67974,0.452644,0.482872,0.432187,0.411618,Dia 9
Alemanha,0.43294,0.522243,0.517691,0.468859,0.456268,Dia 9
Croácia,0.58425,0.500334,0.452586,0.443235,0.421555,Dia 9
Uruguai,0.64917,0.361708,0.480857,0.471615,0.458404,Dia 9
Senegal,1.00000,0.365250,0.391239,0.430371,0.379837,Dia 9
Marrocos,0.89203,0.417217,0.366714,0.367233,0.349362,Dia 9
México,0.35575,0.408236,0.474420,0.485922,0.454301,Dia 9
Polônia,0.69108,0.396177,0.370613,0.344141,0.347652,Dia 9
Japão,0.28900,0.414948,0.343979,0.373091,0.338532,Dia 9
Sérvia,0.26954,0.370891,0.403121,0.355583,0.345429,Dia 9
Costa Rica,0.32245,0.343464,0.315576,0.288698,0.319128,Dia 9
Austrália,0.36714,0.306559,0.293558,0.259383,0.289382,Dia 9
Coreia do Sul,0.12493,0.250700,0.347701,0.331497,0.351801,Dia 9
Tunísia,0.04956,0.339185,0.321237,0.290741,0.312102,Dia 9
Camarões,0.05072,0.277603,0.336648,0.291139,0.275362,Dia 9
Arábia Saudita,0.19368,0.190882,0.210170,0.231660,0.172222,Dia 9
Gana,0.22590,0.108145,0.149816,0.142077,0.288462,Dia 9
Canadá,0.00000,NaN,NaN,NaN,NaN,Dia 9
Equador,0.00000,NaN,NaN,NaN,NaN,Dia 9
País de Gales,0.00000,NaN,NaN,NaN,NaN,Dia 9
Irã,0.00000,NaN,NaN,NaN,NaN,Dia 9
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 9

### **Dia 10**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 10'

S = 100000
dia = 'Dia 10'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia10.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.97452,0.02548,0.00000,0.00000,1.00000,0.70874,0.44040,0.26408,0.15929,0.10479,0.11002,Dia 10
Argentina,1.00000,0.00000,0.00000,0.00000,1.00000,0.76748,0.44831,0.23595,0.13203,0.10392,0.12332,Dia 10
França,1.00000,0.00000,0.00000,0.00000,1.00000,0.69532,0.39496,0.23079,0.12261,0.10818,0.09085,Dia 10
Inglaterra,1.00000,0.00000,0.00000,0.00000,1.00000,0.63606,0.34345,0.19590,0.09882,0.09708,0.07852,Dia 10
Espanha,0.72706,0.22577,0.04717,0.00000,0.95283,0.54375,0.26863,0.13979,0.07202,0.06777,0.06994,Dia 10
Portugal,0.99356,0.00644,0.00000,0.00000,1.00000,0.57892,0.31022,0.15146,0.06981,0.08165,0.07809,Dia 10
Bélgica,0.25704,0.26757,0.44248,0.03291,0.52461,0.33434,0.19651,0.11523,0.06744,0.04779,0.04946,Dia 10
Holanda,1.00000,0.00000,0.00000,0.00000,1.00000,0.54109,0.27113,0.12547,0.06154,0.06393,0.07568,Dia 10
Estados Unidos,0.00000,1.00000,0.00000,0.00000,1.00000,0.45891,0.21216,0.08896,0.03966,0.04930,0.05900,Dia 10
Croácia,0.33034,0.25179,0.41787,0.00000,0.58213,0.29327,0.13446,0.06015,0.02672,0.03343,0.03462,Dia 10
Suíça,0.02548,0.65305,0.28876,0.03271,0.67853,0.30816,0.14722,0.06365,0.02523,0.03842,0.03653,Dia 10
Senegal,0.00000,1.00000,0.00000,0.00000,1.00000,0.36394,0.14871,0.06489,0.02435,0.04054,0.03385,Dia 10
Alemanha,0.00000,0.43205,0.13609,0.43186,0.43205,0.22437,0.11618,0.05448,0.02418,0.03030,0.02903,Dia 10
Uruguai,0.00000,0.64959,0.20952,0.14089,0.64959,0.23346,0.11202,0.05112,0.02371,0.02741,0.02927,Dia 10
Marrocos,0.41262,0.48064,0.10674,0.00000,0.89326,0.37303,0.13759,0.05162,0.01825,0.03337,0.03164,Dia 10
Polônia,0.00000,1.00000,0.00000,0.00000,1.00000,0.30468,0.11288,0.04393,0.01446,0.02947,0.02413,Dia 10
Japão,0.22565,0.06169,0.71256,0.00010,0.28734,0.11819,0.04058,0.01475,0.00532,0.00943,0.00974,Dia 10
Austrália,0.00000,1.00000,0.00000,0.00000,1.00000,0.23252,0.06840,0.01727,0.00511,0.01216,0.01523,Dia 10
Sérvia,0.00000,0.27075,0.29632,0.43293,0.27075,0.09933,0.04028,0.01483,0.00497,0.00986,0.00886,Dia 10
Costa Rica,0.04729,0.28049,0.10418,0.56804,0.32778,0.11305,0.03622,0.01050,0.00298,0.00752,0.00793,Dia 10
Coreia do Sul,0.00000,0.12481,0.18243,0.69276,0.12481,0.03237,0.01126,0.00361,0.00113,0.00248,0.00277,Dia 10
Camarões,0.00000,0.05072,0.41492,0.53436,0.05072,0.01411,0.00460,0.00109,0.00029,0.00080,0.00106,Dia 10
Gana,0.00644,0.21916,0.60805,0.16635,0.22560,0.02491,0.00383,0.00048,0.00008,0.00040,0.00046,Dia 10
Canadá,0.00000,0.00000,0.03291,0.96709,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Equador,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Tunísia,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Dinamarca,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
México,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Arábia Saudita,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
País de Gales,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Irã,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Catar,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 10'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia10.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.00000,0.29126,0.26834,0.17632,0.10479,0.15929,Dia 10
Argentina,0.00000,0.23252,0.31917,0.21236,0.10392,0.13203,Dia 10
França,0.00000,0.30468,0.30036,0.16417,0.10818,0.12261,Dia 10
Inglaterra,0.00000,0.36394,0.29261,0.14755,0.09708,0.09882,Dia 10
Espanha,0.04717,0.40908,0.27512,0.12884,0.06777,0.07202,Dia 10
Portugal,0.00000,0.42108,0.26870,0.15876,0.08165,0.06981,Dia 10
Bélgica,0.47539,0.19027,0.13783,0.08128,0.04779,0.06744,Dia 10
Holanda,0.00000,0.45891,0.26996,0.14566,0.06393,0.06154,Dia 10
Estados Unidos,0.00000,0.54109,0.24675,0.12320,0.04930,0.03966,Dia 10
Croácia,0.41787,0.28886,0.15881,0.07431,0.03343,0.02672,Dia 10
Suíça,0.32147,0.37037,0.16094,0.08357,0.03842,0.02523,Dia 10
Senegal,0.00000,0.63606,0.21523,0.08382,0.04054,0.02435,Dia 10
Alemanha,0.56795,0.20768,0.10819,0.06170,0.03030,0.02418,Dia 10
Uruguai,0.35041,0.41613,0.12144,0.06090,0.02741,0.02371,Dia 10
Marrocos,0.10674,0.52023,0.23544,0.08597,0.03337,0.01825,Dia 10
Polônia,0.00000,0.69532,0.19180,0.06895,0.02947,0.01446,Dia 10
Japão,0.71266,0.16915,0.07761,0.02583,0.00943,0.00532,Dia 10
Austrália,0.00000,0.76748,0.16412,0.05113,0.01216,0.00511,Dia 10
Sérvia,0.72925,0.17142,0.05905,0.02545,0.00986,0.00497,Dia 10
Costa Rica,0.67222,0.21473,0.07683,0.02572,0.00752,0.00298,Dia 10
Coreia do Sul,0.87519,0.09244,0.02111,0.00765,0.00248,0.00113,Dia 10
Camarões,0.94928,0.03661,0.00951,0.00351,0.00080,0.00029,Dia 10
Gana,0.77440,0.20069,0.02108,0.00335,0.00040,0.00008,Dia 10
Canadá,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Equador,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Tunísia,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Dinamarca,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
México,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Arábia Saudita,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
País de Gales,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Irã,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 10

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 10'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia10.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.00000,0.708740,0.621384,0.599637,0.603188,Dia 10
Argentina,1.00000,0.767480,0.584132,0.526310,0.559568,Dia 10
França,1.00000,0.695320,0.568026,0.584338,0.531262,Dia 10
Inglaterra,1.00000,0.636060,0.539965,0.570389,0.504441,Dia 10
Espanha,0.95283,0.570668,0.494032,0.520381,0.515201,Dia 10
Portugal,1.00000,0.578920,0.535860,0.488234,0.460914,Dia 10
Bélgica,0.52461,0.637312,0.587755,0.586382,0.585264,Dia 10
Holanda,1.00000,0.541090,0.501081,0.462767,0.490476,Dia 10
Estados Unidos,1.00000,0.458910,0.462313,0.419306,0.445818,Dia 10
Croácia,0.58213,0.503788,0.458485,0.447345,0.444223,Dia 10
Suíça,0.67853,0.454158,0.477739,0.432346,0.396386,Dia 10
Senegal,1.00000,0.363940,0.408611,0.436353,0.375250,Dia 10
Alemanha,0.43205,0.519315,0.517805,0.468928,0.443833,Dia 10
Uruguai,0.64959,0.359396,0.479825,0.456347,0.463811,Dia 10
Marrocos,0.89326,0.417605,0.368844,0.375173,0.353545,Dia 10
Polônia,1.00000,0.304680,0.370487,0.389174,0.329160,Dia 10
Japão,0.28734,0.411325,0.343345,0.363480,0.360678,Dia 10
Austrália,1.00000,0.232520,0.294168,0.252485,0.295889,Dia 10
Sérvia,0.27075,0.366870,0.405517,0.368173,0.335131,Dia 10
Costa Rica,0.32778,0.344896,0.320389,0.289895,0.283810,Dia 10
Coreia do Sul,0.12481,0.259354,0.347853,0.320604,0.313019,Dia 10
Camarões,0.05072,0.278194,0.326010,0.236957,0.266055,Dia 10
Gana,0.22560,0.110417,0.153754,0.125326,0.166667,Dia 10
Canadá,0.00000,NaN,NaN,NaN,NaN,Dia 10
Equador,0.00000,NaN,NaN,NaN,NaN,Dia 10
Tunísia,0.00000,NaN,NaN,NaN,NaN,Dia 10
Dinamarca,0.00000,NaN,NaN,NaN,NaN,Dia 10
México,0.00000,NaN,NaN,NaN,NaN,Dia 10
Arábia Saudita,0.00000,NaN,NaN,NaN,NaN,Dia 10
País de Gales,0.00000,NaN,NaN,NaN,NaN,Dia 10
Irã,0.00000,NaN,NaN,NaN,NaN,Dia 10
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 10

### **Dia 11**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 11'

S = 100000
dia = 'Dia 11'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia11.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,0.97468,0.02532,0.00000,0.00000,1.00000,0.70765,0.47991,0.28804,0.17536,0.11268,0.11781,Dia 11
Argentina,1.00000,0.00000,0.00000,0.00000,1.00000,0.77235,0.45133,0.25037,0.14113,0.10924,0.11706,Dia 11
França,1.00000,0.00000,0.00000,0.00000,1.00000,0.69510,0.39546,0.22962,0.12283,0.10679,0.09367,Dia 11
Inglaterra,1.00000,0.00000,0.00000,0.00000,1.00000,0.63344,0.34139,0.19230,0.09853,0.09377,0.08133,Dia 11
Espanha,0.00000,1.00000,0.00000,0.00000,1.00000,0.65199,0.36405,0.18977,0.09544,0.09433,0.09381,Dia 11
Portugal,0.99319,0.00681,0.00000,0.00000,1.00000,0.57499,0.30244,0.14795,0.06986,0.07809,0.07797,Dia 11
Holanda,1.00000,0.00000,0.00000,0.00000,1.00000,0.54075,0.26889,0.12910,0.06299,0.06611,0.07182,Dia 11
Croácia,0.00000,1.00000,0.00000,0.00000,1.00000,0.58445,0.23764,0.10741,0.04919,0.05822,0.06122,Dia 11
Estados Unidos,0.00000,1.00000,0.00000,0.00000,1.00000,0.45925,0.21191,0.09360,0.04197,0.05163,0.05638,Dia 11
Suíça,0.02532,0.65504,0.28750,0.03214,0.68036,0.31033,0.14674,0.06414,0.02732,0.03682,0.03700,Dia 11
Uruguai,0.00000,0.65281,0.20942,0.13777,0.65281,0.23707,0.13000,0.05975,0.02724,0.03251,0.03405,Dia 11
Senegal,0.00000,1.00000,0.00000,0.00000,1.00000,0.36656,0.14950,0.06373,0.02487,0.03886,0.03582,Dia 11
Japão,1.00000,0.00000,0.00000,0.00000,1.00000,0.41555,0.13665,0.05023,0.01885,0.03138,0.03371,Dia 11
Marrocos,1.00000,0.00000,0.00000,0.00000,1.00000,0.34801,0.14240,0.05295,0.01845,0.03450,0.03429,Dia 11
Polônia,0.00000,1.00000,0.00000,0.00000,1.00000,0.30490,0.11365,0.04313,0.01465,0.02848,0.02580,Dia 11
Austrália,0.00000,1.00000,0.00000,0.00000,1.00000,0.22765,0.06787,0.01853,0.00509,0.01344,0.01429,Dia 11
Sérvia,0.00000,0.27023,0.29770,0.43207,0.27023,0.10028,0.03868,0.01335,0.00457,0.00878,0.00949,Dia 11
Coreia do Sul,0.00000,0.12363,0.17943,0.69694,0.12363,0.03014,0.01236,0.00419,0.00125,0.00294,0.00287,Dia 11
Camarões,0.00000,0.04941,0.41480,0.53579,0.04941,0.01449,0.00451,0.00116,0.00030,0.00086,0.00094,Dia 11
Gana,0.00681,0.21675,0.61115,0.16529,0.22356,0.02505,0.00462,0.00068,0.00011,0.00057,0.00067,Dia 11
Bélgica,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Canadá,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Catar,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Costa Rica,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Equador,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Tunísia,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Dinamarca,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
México,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Arábia Saudita,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
País de Gales,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Irã,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Alemanha,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 11'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia11.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.00000,0.29235,0.22774,0.19187,0.11268,0.17536,Dia 11
Argentina,0.00000,0.22765,0.32102,0.20096,0.10924,0.14113,Dia 11
França,0.00000,0.30490,0.29964,0.16584,0.10679,0.12283,Dia 11
Inglaterra,0.00000,0.36656,0.29205,0.14909,0.09377,0.09853,Dia 11
Espanha,0.00000,0.34801,0.28794,0.17428,0.09433,0.09544,Dia 11
Portugal,0.00000,0.42501,0.27255,0.15449,0.07809,0.06986,Dia 11
Holanda,0.00000,0.45925,0.27186,0.13979,0.06611,0.06299,Dia 11
Croácia,0.00000,0.41555,0.34681,0.13023,0.05822,0.04919,Dia 11
Estados Unidos,0.00000,0.54075,0.24734,0.11831,0.05163,0.04197,Dia 11
Suíça,0.31964,0.37003,0.16359,0.08260,0.03682,0.02732,Dia 11
Uruguai,0.34719,0.41574,0.10707,0.07025,0.03251,0.02724,Dia 11
Senegal,0.00000,0.63344,0.21706,0.08577,0.03886,0.02487,Dia 11
Japão,0.00000,0.58445,0.27890,0.08642,0.03138,0.01885,Dia 11
Marrocos,0.00000,0.65199,0.20561,0.08945,0.03450,0.01845,Dia 11
Polônia,0.00000,0.69510,0.19125,0.07052,0.02848,0.01465,Dia 11
Austrália,0.00000,0.77235,0.15978,0.04934,0.01344,0.00509,Dia 11
Sérvia,0.72977,0.16995,0.06160,0.02533,0.00878,0.00457,Dia 11
Coreia do Sul,0.87637,0.09349,0.01778,0.00817,0.00294,0.00125,Dia 11
Camarões,0.95059,0.03492,0.00998,0.00335,0.00086,0.00030,Dia 11
Gana,0.77644,0.19851,0.02043,0.00394,0.00057,0.00011,Dia 11
Bélgica,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Canadá,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Catar,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Costa Rica,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Equador,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Tunísia,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Dinamarca,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
México,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Arábia Saudita,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
País de Gales,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Irã,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11
Alemanha,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 11

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 11'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia11.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.00000,0.707650,0.678174,0.600196,0.608804,Dia 11
Argentina,1.00000,0.772350,0.584359,0.554738,0.563686,Dia 11
França,1.00000,0.695100,0.568925,0.580640,0.534927,Dia 11
Inglaterra,1.00000,0.633440,0.538946,0.563285,0.512376,Dia 11
Espanha,1.00000,0.651990,0.558367,0.521275,0.502925,Dia 11
Portugal,1.00000,0.574990,0.525992,0.489188,0.472187,Dia 11
Holanda,1.00000,0.540750,0.497254,0.480122,0.487916,Dia 11
Croácia,1.00000,0.584450,0.406604,0.451986,0.457965,Dia 11
Estados Unidos,1.00000,0.459250,0.461426,0.441697,0.448397,Dia 11
Suíça,0.68036,0.456126,0.472851,0.437100,0.425943,Dia 11
Uruguai,0.65281,0.363153,0.548361,0.459615,0.455900,Dia 11
Senegal,1.00000,0.366560,0.407846,0.426288,0.390240,Dia 11
Japão,1.00000,0.415550,0.328841,0.367581,0.375274,Dia 11
Marrocos,1.00000,0.348010,0.409184,0.371840,0.348442,Dia 11
Polônia,1.00000,0.304900,0.372745,0.379498,0.339671,Dia 11
Austrália,1.00000,0.227650,0.298133,0.273022,0.274690,Dia 11
Sérvia,0.27023,0.371091,0.385720,0.345140,0.342322,Dia 11
Coreia do Sul,0.12363,0.243792,0.410086,0.338997,0.298329,Dia 11
Camarões,0.04941,0.293260,0.311249,0.257206,0.258621,Dia 11
Gana,0.22356,0.112050,0.184431,0.147186,0.161765,Dia 11
Bélgica,0.00000,NaN,NaN,NaN,NaN,Dia 11
Canadá,0.00000,NaN,NaN,NaN,NaN,Dia 11
Catar,0.00000,NaN,NaN,NaN,NaN,Dia 11
Costa Rica,0.00000,NaN,NaN,NaN,NaN,Dia 11
Equador,0.00000,NaN,NaN,NaN,NaN,Dia 11
Tunísia,0.00000,NaN,NaN,NaN,NaN,Dia 11
Dinamarca,0.00000,NaN,NaN,NaN,NaN,Dia 11
México,0.00000,NaN,NaN,NaN,NaN,Dia 11
Arábia Saudita,0.00000,NaN,NaN,NaN,NaN,Dia 11
País de Gales,0.00000,NaN,NaN,NaN,NaN,Dia 11
Irã,0.00000,NaN,NaN,NaN,NaN,Dia 11
Alemanha,0.00000,NaN,NaN,NaN,NaN,Dia 11

### **Dia 12**

In [ ]:
# Simulando a copa 100.000 vezes para 'Dia 12'

S = 100000
dia = 'Dia 12'
etapa = 'Fase 1'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = dia
sim.to_excel('outputSimulaçõesCopaDoMundo_Dia12.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,1.0,0.0,0.0,0.0,1.0,0.75409,0.51441,0.30892,0.18585,0.12307,0.12829,Dia 12
Argentina,1.0,0.0,0.0,0.0,1.0,0.76943,0.45314,0.25091,0.14199,0.10892,0.11667,Dia 12
França,1.0,0.0,0.0,0.0,1.0,0.69762,0.39794,0.22982,0.12389,0.10593,0.09461,Dia 12
Inglaterra,1.0,0.0,0.0,0.0,1.0,0.63178,0.34005,0.19122,0.09963,0.09159,0.08257,Dia 12
Espanha,0.0,1.0,0.0,0.0,1.0,0.65174,0.36018,0.18737,0.09525,0.09212,0.09264,Dia 12
Portugal,1.0,0.0,0.0,0.0,1.0,0.55559,0.29200,0.14297,0.06792,0.07505,0.07623,Dia 12
Holanda,1.0,0.0,0.0,0.0,1.0,0.54218,0.26966,0.13149,0.06405,0.06744,0.06998,Dia 12
Croácia,0.0,1.0,0.0,0.0,1.0,0.58708,0.24366,0.10927,0.04859,0.06068,0.06178,Dia 12
Estados Unidos,0.0,1.0,0.0,0.0,1.0,0.45782,0.21124,0.09597,0.04273,0.05324,0.05489,Dia 12
Suíça,0.0,1.0,0.0,0.0,1.0,0.44441,0.20899,0.09277,0.03869,0.05408,0.05245,Dia 12
Senegal,0.0,1.0,0.0,0.0,1.0,0.36822,0.14975,0.06294,0.02389,0.03905,0.03644,Dia 12
Japão,1.0,0.0,0.0,0.0,1.0,0.41292,0.14103,0.05094,0.01846,0.03248,0.03588,Dia 12
Marrocos,1.0,0.0,0.0,0.0,1.0,0.34826,0.13883,0.05025,0.01801,0.03224,0.03342,Dia 12
Polônia,0.0,1.0,0.0,0.0,1.0,0.30238,0.11226,0.04266,0.01471,0.02795,0.02593,Dia 12
Coreia do Sul,0.0,1.0,0.0,0.0,1.0,0.24591,0.10090,0.03395,0.01119,0.02276,0.02378,Dia 12
Austrália,0.0,1.0,0.0,0.0,1.0,0.23057,0.06596,0.01855,0.00515,0.01340,0.01444,Dia 12
Camarões,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Bélgica,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Sérvia,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Uruguai,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Canadá,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Catar,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Alemanha,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Costa Rica,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Equador,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Tunísia,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Dinamarca,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
México,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Arábia Saudita,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
País de Gales,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Irã,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Gana,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Dia 12'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Dia12.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.0,0.24591,0.23968,0.20549,0.12307,0.18585,Dia 12
Argentina,0.0,0.23057,0.31629,0.20223,0.10892,0.14199,Dia 12
França,0.0,0.30238,0.29968,0.16812,0.10593,0.12389,Dia 12
Inglaterra,0.0,0.36822,0.29173,0.14883,0.09159,0.09963,Dia 12
Espanha,0.0,0.34826,0.29156,0.17281,0.09212,0.09525,Dia 12
Portugal,0.0,0.44441,0.26359,0.14903,0.07505,0.06792,Dia 12
Holanda,0.0,0.45782,0.27252,0.13817,0.06744,0.06405,Dia 12
Croácia,0.0,0.41292,0.34342,0.13439,0.06068,0.04859,Dia 12
Estados Unidos,0.0,0.54218,0.24658,0.11527,0.05324,0.04273,Dia 12
Suíça,0.0,0.55559,0.23542,0.11622,0.05408,0.03869,Dia 12
Senegal,0.0,0.63178,0.21847,0.08681,0.03905,0.02389,Dia 12
Japão,0.0,0.58708,0.27189,0.09009,0.03248,0.01846,Dia 12
Marrocos,0.0,0.65174,0.20943,0.08858,0.03224,0.01801,Dia 12
Polônia,0.0,0.69762,0.19012,0.06960,0.02795,0.01471,Dia 12
Coreia do Sul,0.0,0.75409,0.14501,0.06695,0.02276,0.01119,Dia 12
Austrália,0.0,0.76943,0.16461,0.04741,0.01340,0.00515,Dia 12
Camarões,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Bélgica,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Sérvia,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Uruguai,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Canadá,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Catar,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Alemanha,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Costa Rica,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Equador,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Tunísia,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Dinamarca,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
México,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Arábia Saudita,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
País de Gales,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Irã,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12
Gana,1.0,0.00000,0.00000,0.00000,0.00000,0.00000,Dia 12

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Dia 12'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Dia12.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.0,0.75409,0.682160,0.600533,0.601612,Dia 12
Argentina,1.0,0.76943,0.588929,0.553714,0.565900,Dia 12
França,1.0,0.69762,0.570425,0.577524,0.539074,Dia 12
Inglaterra,1.0,0.63178,0.538241,0.562329,0.521023,Dia 12
Espanha,1.0,0.65174,0.552644,0.520212,0.508352,Dia 12
Portugal,1.0,0.55559,0.525567,0.489623,0.475065,Dia 12
Holanda,1.0,0.54218,0.497362,0.487614,0.487109,Dia 12
Croácia,1.0,0.58708,0.415037,0.448453,0.444678,Dia 12
Estados Unidos,1.0,0.45782,0.461404,0.454317,0.445243,Dia 12
Suíça,1.0,0.44441,0.470264,0.443897,0.417053,Dia 12
Senegal,1.0,0.36822,0.406686,0.420301,0.379568,Dia 12
Japão,1.0,0.41292,0.341543,0.361200,0.362387,Dia 12
Marrocos,1.0,0.34826,0.398639,0.361953,0.358408,Dia 12
Polônia,1.0,0.30238,0.371255,0.380011,0.344820,Dia 12
Coreia do Sul,1.0,0.24591,0.410313,0.336472,0.329602,Dia 12
Austrália,1.0,0.23057,0.286074,0.281231,0.277628,Dia 12
Camarões,0.0,NaN,NaN,NaN,NaN,Dia 12
Bélgica,0.0,NaN,NaN,NaN,NaN,Dia 12
Sérvia,0.0,NaN,NaN,NaN,NaN,Dia 12
Uruguai,0.0,NaN,NaN,NaN,NaN,Dia 12
Canadá,0.0,NaN,NaN,NaN,NaN,Dia 12
Catar,0.0,NaN,NaN,NaN,NaN,Dia 12
Alemanha,0.0,NaN,NaN,NaN,NaN,Dia 12
Costa Rica,0.0,NaN,NaN,NaN,NaN,Dia 12
Equador,0.0,NaN,NaN,NaN,NaN,Dia 12
Tunísia,0.0,NaN,NaN,NaN,NaN,Dia 12
Dinamarca,0.0,NaN,NaN,NaN,NaN,Dia 12
México,0.0,NaN,NaN,NaN,NaN,Dia 12
Arábia Saudita,0.0,NaN,NaN,NaN,NaN,Dia 12
País de Gales,0.0,NaN,NaN,NaN,NaN,Dia 12
Irã,0.0,NaN,NaN,NaN,NaN,Dia 12
Gana,0.0,NaN,NaN,NaN,NaN,Dia 12

### **Oitavas**

In [ ]:
# Simulando a copa 100.000 vezes após as 'Oitavas'

S = 100000
dia = 'Dia 12'
etapa = 'Oitavas'
sim = SimulacaoTotal(selecoes, dia, etapa, S)
sim['dia'] = etapa
sim.to_excel('outputSimulaçõesCopaDoMundo_Oitavas.xlsx')
sim

IA: "Iniciando simulação..."
IA: "Simulações de Copas do Mundo: 10% completas
IA: "Simulações de Copas do Mundo: 20% completas
IA: "Simulações de Copas do Mundo: 30% completas
IA: "Simulações de Copas do Mundo: 40% completas
IA: "Simulações de Copas do Mundo: 50% completas
IA: "Simulações de Copas do Mundo: 60% completas
IA: "Simulações de Copas do Mundo: 70% completas
IA: "Simulações de Copas do Mundo: 80% completas
IA: "Simulações de Copas do Mundo: 90% completas
IA: "Simulações de Copas do Mundo: 100% completas
IA: "Simulação Finalizada!"

,1st,2nd,3rd,4th,Oitavas,Quartas,Semis,Final,Campeão,2 lugar,3 lugar,dia
Seleção,,,,,,,,,,,,
Brasil,1.0,0.0,0.0,0.0,1.0,1.0,0.65159,0.37268,0.22167,0.15101,0.17316,Oitavas
Argentina,1.0,0.0,0.0,0.0,1.0,1.0,0.56972,0.29046,0.16046,0.13000,0.16113,Oitavas
França,1.0,0.0,0.0,0.0,1.0,1.0,0.52040,0.31730,0.16004,0.15726,0.10625,Oitavas
Inglaterra,1.0,0.0,0.0,0.0,1.0,1.0,0.47960,0.28282,0.13849,0.14433,0.09895,Oitavas
Portugal,1.0,0.0,0.0,0.0,1.0,1.0,0.62331,0.27635,0.12174,0.15461,0.15818,Oitavas
Holanda,1.0,0.0,0.0,0.0,1.0,1.0,0.43028,0.19153,0.09312,0.09841,0.12107,Oitavas
Croácia,0.0,1.0,0.0,0.0,1.0,1.0,0.34841,0.14533,0.06400,0.08133,0.09523,Oitavas
Marrocos,1.0,0.0,0.0,0.0,1.0,1.0,0.37669,0.12353,0.04048,0.08305,0.08603,Oitavas
Suíça,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Bélgica,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Canadá,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Catar,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Camarões,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Espanha,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Sérvia,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Uruguai,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Coreia do Sul,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Costa Rica,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Alemanha,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Japão,1.0,0.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Equador,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Austrália,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Tunísia,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Dinamarca,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Polônia,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
México,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Arábia Saudita,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
País de Gales,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Estados Unidos,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Irã,0.0,0.0,1.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Senegal,0.0,1.0,0.0,0.0,1.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas
Gana,0.0,0.0,0.0,1.0,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.00000,Oitavas

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de cair por etapas

dia = 'Oitavas'

etapas = pd.DataFrame()
etapas['Cair na 1ª Fase'] = 1 - sim['Oitavas']
etapas['Cair nas Oitavas'] = sim['Oitavas'] - sim['Quartas']
etapas['Cair nas Quartas'] = sim['Quartas'] - sim['Semis']
etapas['Cair nas Semis'] = sim['Semis'] - sim['Final']
etapas['Cair na Final'] = sim['Final']  -  sim['Campeão']
etapas['Ganhar a Final'] = sim['Campeão']
etapas['dia'] = dia
etapas.to_excel('outputProbabilidadesPorEtapa_Oitavas.xlsx')
etapas

,Cair na 1ª Fase,Cair nas Oitavas,Cair nas Quartas,Cair nas Semis,Cair na Final,Ganhar a Final,dia
Seleção,,,,,,,
Brasil,0.0,0.0,0.34841,0.27891,0.15101,0.22167,Oitavas
Argentina,0.0,0.0,0.43028,0.27926,0.13000,0.16046,Oitavas
França,0.0,0.0,0.47960,0.20310,0.15726,0.16004,Oitavas
Inglaterra,0.0,0.0,0.52040,0.19678,0.14433,0.13849,Oitavas
Portugal,0.0,0.0,0.37669,0.34696,0.15461,0.12174,Oitavas
Holanda,0.0,0.0,0.56972,0.23875,0.09841,0.09312,Oitavas
Croácia,0.0,0.0,0.65159,0.20308,0.08133,0.06400,Oitavas
Marrocos,0.0,0.0,0.62331,0.25316,0.08305,0.04048,Oitavas
Suíça,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Bélgica,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Canadá,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Catar,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Camarões,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Espanha,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Sérvia,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Uruguai,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Coreia do Sul,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Costa Rica,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Alemanha,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Japão,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Equador,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Austrália,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Tunísia,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Dinamarca,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Polônia,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
México,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Arábia Saudita,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
País de Gales,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Estados Unidos,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Irã,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Senegal,0.0,1.0,0.00000,0.00000,0.00000,0.00000,Oitavas
Gana,1.0,0.0,0.00000,0.00000,0.00000,0.00000,Oitavas

In [ ]:
# Extraindo mais informações da Simulação
# Probabilidades de avançar por etapas

dia = 'Oitavas'

avanco = pd.DataFrame()
avanco['Avançar na 1ª Fase'] = sim['Oitavas']
avanco['Avançar nas Oitavas'] = sim['Quartas']/sim['Oitavas']
avanco['Avançar nas Quartas'] = sim['Semis']/sim['Quartas']
avanco['Avançar nas Semis'] = sim['Final']/sim['Semis']
avanco['Avançar na Final'] = sim['Campeão']/sim['Final']
avanco['dia'] = dia
avanco.to_excel('outputAvançoPorEtapa_Oitavas.xlsx')
avanco

,Avançar na 1ª Fase,Avançar nas Oitavas,Avançar nas Quartas,Avançar nas Semis,Avançar na Final,dia
Seleção,,,,,,
Brasil,1.0,1.0,0.65159,0.571955,0.594800,Oitavas
Argentina,1.0,1.0,0.56972,0.509829,0.552434,Oitavas
França,1.0,1.0,0.52040,0.609723,0.504381,Oitavas
Inglaterra,1.0,1.0,0.47960,0.589700,0.489675,Oitavas
Portugal,1.0,1.0,0.62331,0.443359,0.440528,Oitavas
Holanda,1.0,1.0,0.43028,0.445129,0.486190,Oitavas
Croácia,1.0,1.0,0.34841,0.417124,0.440377,Oitavas
Marrocos,1.0,1.0,0.37669,0.327935,0.327694,Oitavas
Suíça,1.0,0.0,NaN,NaN,NaN,Oitavas
Bélgica,0.0,NaN,NaN,NaN,NaN,Oitavas
Canadá,0.0,NaN,NaN,NaN,NaN,Oitavas
Catar,0.0,NaN,NaN,NaN,NaN,Oitavas
Camarões,0.0,NaN,NaN,NaN,NaN,Oitavas
Espanha,1.0,0.0,NaN,NaN,NaN,Oitavas
Sérvia,0.0,NaN,NaN,NaN,NaN,Oitavas
Uruguai,0.0,NaN,NaN,NaN,NaN,Oitavas
Coreia do Sul,1.0,0.0,NaN,NaN,NaN,Oitavas
Costa Rica,0.0,NaN,NaN,NaN,NaN,Oitavas
Alemanha,0.0,NaN,NaN,NaN,NaN,Oitavas
Japão,1.0,0.0,NaN,NaN,NaN,Oitavas
Equador,0.0,NaN,NaN,NaN,NaN,Oitavas
Austrália,1.0,0.0,NaN,NaN,NaN,Oitavas
Tunísia,0.0,NaN,NaN,NaN,NaN,Oitavas
Dinamarca,0.0,NaN,NaN,NaN,NaN,Oitavas
Polônia,1.0,0.0,NaN,NaN,NaN,Oitavas
México,0.0,NaN,NaN,NaN,NaN,Oitavas
Arábia Saudita,0.0,NaN,NaN,NaN,NaN,Oitavas
País de Gales,0.0,NaN,NaN,NaN,NaN,Oitavas
Estados Unidos,1.0,0.0,NaN,NaN,NaN,Oitavas
Irã,0.0,NaN,NaN,NaN,NaN,Oitavas
Senegal,1.0,0.0,NaN,NaN,NaN,Oitavas
Gana,0.0,NaN,NaN,NaN,NaN,Oitavas